### ISSUE TITLE
Linux download for Ubuntu 18.04 fails

### ISSUE THREAD

**Issue by peter-snr** [nodkz/mongodb-memory-server#100]
Hi,

I have tried to run mongodb-memory-server (mongodb-memory-server@2.6.2) as a fresh npm install on Ubuntu 1804.  

It is failing with an incorrect download location.  Please see the following stack trace: -

Determining test suites to run...  Mongo[40427] Starting MongoDB instance with following options: {"port":40427,"dbName":"jest","uri":"mongodb://127.0.0.1:40427/jest","storageEngine"
:"ephemeralForTest","dbPath":"/tmp/mongo-mem-15254m9v8farYN312"} +0ms
  Mongo[40427] MongoBinary options: {"downloadDir":"/home/jenkins/.mongodb-binaries","platform":"linux","arch":"x64","version":"3.2.18"} +2ms
  Mongo[40427] Downloading: https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1804-3.2.18.tgz +27ms
  Mongo[40427] renamed /home/jenkins/.mongodb-binaries/mongodb-linux-x86_64-ubuntu1804-3.2.18.tgz.downloading to /home/jenkins/.mongodb-binaries/mongodb-linux-x86_64-ubuntu1804-3.2.1
8.tgz +97ms
  Mongo[40427] Downloading: https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1804-3.2.18.tgz.md5 +1ms
  Mongo[40427] renamed /home/jenkins/.mongodb-binaries/mongodb-linux-x86_64-ubuntu1804-3.2.18.tgz.md5.downloading to /home/jenkins/.mongodb-binaries/mongodb-linux-x86_64-ubuntu1804-3
.2.18.tgz.md5 +10ms
  Mongo[40427] extract(): /home/jenkins/.mongodb-binaries/3.2.18 +1ms
Error: MongoBinaryDownload: missing mongod binary in /home/jenkins/.mongodb-binaries/mongodb-linux-x86_64-ubuntu1804-3.2.18.tgz
    at /var/lib/jenkins/workspace/PrismIS/node_modules/mongodb-memory-server/lib/util/MongoBinaryDownload.js:207:15
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/var/lib/jenkins/workspace/PrismIS/node_modules/mongodb-memory-server/lib/util/MongoBinaryDownload.js:28:103)
    at _next (/var/lib/jenkins/workspace/PrismIS/node_modules/mongodb-memory-server/lib/util/MongoBinaryDownload.js:30:194)
    at <anonymous>

Trying this URL: https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1804-3.2.18.tgz gives a 'permission denied'.

Kind regards.

Peter

**Comment by AJRdev** [comment]
@peter-snr Did you specified the version 3.2.18 of MongoDB for the binary download ? Because it is an invalid version.
Because by default if the version wasn't specified, the download link would have been : 
[](https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1804-latest.tgz)

**Comment by nodkz** [comment]
For MongoDB 3.x absent binaries for Ubuntu 18.04, so will be used 16.04 binaries.
Fixed in mongodb-memory-serve@2.7.0

Awaiting success Travis build, after that will be published new version to npm
