### ISSUE TITLE
Performance comparison showing the speed gain

### ISSUE THREAD

**Issue by goldbergyoni** [nodkz/mongodb-memory-server#105]
Hi,

We're [working here on testing best practices](https://github.com/i0natan/nodebestpractices) and focus now on performance optimization.

Did you perform any comparison between using this lib vs persisted Mongo? I'm curious what performance gain one might see

Thanks!

Yoni Goldberg

**Comment by nodkz** [comment]
Performance gain with parallel testing. In the following article showed 3x speed up: 
https://itnext.io/parallel-testing-a-graphql-server-with-jest-44e206f3e7d2
