### ISSUE TITLE
isRunning boolean is misleading/unused

### ISSUE THREAD

**Issue by dewhacker** [nodkz/mongodb-memory-server#108]
This appears to be unused or never set, `runningInstance` must be checked instead

**Comment by nodkz** [comment]
Can you open a Pull Request with removing these lines from the code?
https://github.com/nodkz/mongodb-memory-server/search?q=isRunning&unscoped_q=isRunning

**Comment by AJRdev** [comment]
Issue fixed in PR https://github.com/nodkz/mongodb-memory-server/pull/116 .
