### ISSUE TITLE
auth param not passed when instance.auth is true

### ISSUE THREAD

**Issue by StefanoDeVuono** [nodkz/mongodb-memory-server#111]
[PR 79](https://github.com/nodkz/mongodb-memory-server/pull/79) doesn't add `auth` to the command line arguments (`prepareCommandArgs()`) even when `instance.auth` is set to `true`.

**Comment by AJRdev** [comment]
@StefanoDeVuono I close this issue, since your PR has been merged, thanks for your contribution !
