### ISSUE TITLE
Documentation of --maxWorkers 4

### ISSUE THREAD

**Issue by aymericbouzy** [nodkz/mongodb-memory-server#117]
I have finally seen this section in the documentation https://github.com/nodkz/mongodb-memory-server#travis after thinking there was maybe a memory leak. Maybe consider moving it up to make it more visible? Would a PR on this matter be considered?

**Comment by nodkz** [comment]
Maybe better to add an outline. Something like this https://github.com/semantic-release/semantic-release#documentation

In readme too many things which should be upper than others for different peoples. So if you create PR with the outline it will be very helpful for newcomers. 😉
