### ISSUE TITLE
Add download hash checking

### ISSUE THREAD

**Issue by OmgImAlexis** [nodkz/mongodb-memory-server#12]
Without this if the binary is corrupted there's never an error shown to the user.

I unfortunately found this out after using <kbd>ctrl+c</kbd> at the start of my tests 4 hours ago while it was still downloading.

**Comment by nodkz** [comment]
Try to fix this problem on the next week. Thanks for reporting.

**Comment by nodkz** [comment]
Should be fixed in https://github.com/nodkz/mongodb-memory-server/commit/9a865d6e4aa621a6fcb3cdbbf75ef6a3c8d6e4df
