### ISSUE TITLE
Skip download and refer to dependency?

### ISSUE THREAD

**Issue by ClaytonAstrom** [nodkz/mongodb-memory-server#124]
I have in my package.json:
```json
    "mongodb-memory-server": "^2.9.1",
    "mongodb-prebuilt": "^6.4.0",
```
and when I try to start the mongo instance:
```ts
mongoServer = new MongoMemoryServer({
    binary: {
      // @ts-ignore
      systemBinary: './node_modules/.bin/mongod'
    }
  });
```
But it still seems to try and download the binary to cache.  Am I setting this up properly?  Or does it download regardless?

**Comment by krasimir** [comment]
@ClaytonAstrom what was the issue? I think I have a similar problem.
