### ISSUE TITLE
TypeScript declarations for MongoMemoryReplSet is missing constructor

### ISSUE THREAD

**Issue by erikhofer** [nodkz/mongodb-memory-server#125]
https://github.com/nodkz/mongodb-memory-server/blob/b59ed826dd4f3cd31ad6f05c890f70eaad034abd/src/MongoMemoryReplSet.d.ts#L45-L57

You can only call the constructor without arguments and thus not pass any configuration.

**Comment by AJRdev** [comment]
@erikhofer You can call the constructor of MongoMemoryReplSet with arguments, it is just the typescript definition of the constructor that is missing but the constructor is defined here :
 
https://github.com/nodkz/mongodb-memory-server/blob/b59ed826dd4f3cd31ad6f05c890f70eaad034abd/src/MongoMemoryReplSet.js#L54

But thanks for pointing it out, I will make PR unless you want to take care of it @erikhofer  ? :)

**Comment by AJRdev** [comment]
Issue fixed by the full typescript migration https://github.com/nodkz/mongodb-memory-server/pull/145
