### ISSUE TITLE
Fix readme for replica set

### ISSUE THREAD

**Issue by erikhofer** [nodkz/mongodb-memory-server#126]
> ### Replica Set start:
> ```js
> import { MongoMemoryReplSet } from 'mongodb-memory-server';
> 
> const replSet = new MongoMemoryReplSet();
> await replSet.waitUntilRunning();
> const uri = await mongod.getConnectionString();
> const port = await mongod.getPort();
> const dbPath = await mongod.getDbPath();
> const dbName = await mongod.getDbName();
> 
> // some code
> 
> // stop replica set manually
> replSet.stop();
> // or it should be stopped automatically when you exit from script
> ```

This looks like it was copy & pasted but not completely adapted to replica sets 🤔

**Comment by tamas-pap** [comment]
Can you please post a correct example of using the `MongoMemoryReplSet`? Thanks.

**Comment by erikhofer** [comment]
I think in principal this works but you can't get host and port, only the uri like this:

```js
const replSet = new MongoMemoryReplSet();
await replSet.waitUntilRunning();
const uri = replSet.getUri();
```
The problem is that `waitUntilRunning()` doesn't wait until the replica set can actually be used. There is a period of time where it is started but you can't perform write operations. I didn't get this to work so I gave up.

**Comment by tamas-pap** [comment]
@erikhofer Did you find any workaround, other than a `setTimeout` with some arbitrary `wait` time?

**Comment by tamas-pap** [comment]
This how I managed it to work (using `sleep` and appending the `replicaSet` param to the connection string.

```js
const assert = require("assert");
const sleep = require("sleep-promise");
const { MongoMemoryReplSet } = require("mongodb-memory-server");
const db = require("mongoose");

const run = async () => {
  const replSet = new MongoMemoryReplSet({
    instanceOpts: [
      { storageEngine: "wiredTiger" },
      { storageEngine: "wiredTiger" }
    ]
  });

  await replSet.waitUntilRunning();
  const uri = `${await replSet.getConnectionString()}?replicaSet=testset`;
  console.log(uri);
  const dbName = await replSet.getDbName();

  await sleep(2000);

  await db.connect(
    uri,
    { useNewUrlParser: true }
  );

  const Customer = db.model("Customer", new db.Schema({ name: String }));

  let session = null;

  return (
    Customer.createCollection()
      .then(() => db.startSession())
      .then(_session => {
        session = _session;
        // Start a transaction
        session.startTransaction();
        // This `create()` is part of the transaction because of the `session`
        // option.
        return Customer.create([{ name: "Test" }], { session: session });
      })
      // Transactions execute in isolation, so unless you pass a `session`
      // to `findOne()` you won't see the document until the transaction
      // is committed.
      .then(() => Customer.findOne({ name: "Test" }))
      .then(doc => assert.ok(!doc))
      // This `findOne()` will return the doc, because passing the `session`
      // means this `findOne()` will run as part of the transaction.
      .then(() => Customer.findOne({ name: "Test" }).session(session))
      .then(doc => console.log(doc))
      // Once the transaction is committed, the write operation becomes
      // visible outside of the transaction.
      .then(() => session.commitTransaction())
      .then(() => session.endSession())
      .then(() => Customer.findOne({ name: "Test" }))
      .then(doc => {
        console.log(doc);
        db.disconnect();
        replSet.stop();
      })
      .catch(console.log)
  );
};

run();
```

**Comment by erikhofer** [comment]
> @erikhofer Did you find any workaround, other than a `setTimeout` with some arbitrary `wait` time?

No I didn't. You can probably use a loop that tries to perform a write operation and sleeps some time if it fails with a maximum number of retries. This would solve the race condition but isn't very elegant...

**Comment by tamas-pap** [comment]
@erikhofer Yes, that could be an option for now, until it's fixed directly in the project.

**Comment by j** [comment]
Can't use transactions currently with this.  :-\

**Comment by bbhopesh** [comment]
@tamas-pap Instead of hard coding `testset`, you can do this `uri = `${await mongod.getConnectionString()}?replicaSet=${mongod.getInstanceOpts().replSet}`;`

but the major issue of adding sleep still remains.

**Comment by Hulcsa** [comment]
Anyone else getting this error when working with transactions?

"Transaction numbers are only allowed on storage engines that support document-level locking"

**Comment by nodkz** [comment]
### Before `<6.0.0`

```js
const uri = `${await replSet.getConnectionString()}?replicaSet=testset`;
```

### Starting from `>=6.0.0`

```js
const uri = await replSet.getConnectionString();
```

`?replicaSet=testset` returned by default from `getConnectionString()` method
