### ISSUE TITLE
AccessDenied on Linux

### ISSUE THREAD

**Issue by lirbank** [nodkz/mongodb-memory-server#133]
We use `mongodb-memory-server` with MongoDB 3.6.4. It works like a charm on MacOS, but on our CI server (Linux, vanilla docker image `node:11.8.0`) it tries to download a file for Debian 9.2 which is not accessible:
https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian92-3.6.4.tgz

The file for debian 8.1 is there though:
https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian81-3.6.4.tgz

Possibly related to #131

**Comment by lirbank** [comment]
Update: Using 3.6.5 instead of 3.6.4 works with both MacOS and debian 9.2 (docker `node:11.8.0`). Since it's a minor version bump I think this is an acceptable solution. 
https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian92-3.6.5.tgz

**Comment by hasezoey** [comment]
this *should* be fixed in later versions of this package

if this should still happen in 6.2+, please open a new issue
