### ISSUE TITLE
Integration tests failing

### ISSUE THREAD

**Issue by hanMarr** [nodkz/mongodb-memory-server#135]
After having multiple consecutive successful builds with mongodb-memory-server 3.0.0 with binary version 3.6.9, a reloading of our node_modules has caused our build to fail for multiple apps using this library. 

We have eliminated the possibility that this issue is on our end and have isolated it to the usage of the library. When we run the integration tests...

There are a series of errors starting with

`[LOCAL] [xyz] Error processing shipping update request "After applying the update, the (immutable) field '_id' was found to have been altered to _id: \"5c630d0833842648a3e0de17\"`

This error can be fixed by not removing the _id field, but if we do that, then that will introduce duplicated orders into our db. This fix (where we removed the _id field to prevent duplicate orders), has been running successfully with no issue up until the point where we needed to rebuild the node_modules. Is there some compatibility issue between the monogdb-memory-server versions with how we can handle the '_id' field?

After that initial error from above, our code start breaking and throwing errors because the code and can't find the pieces of the document it is looking for. Then, the tests concludes with the following:
```
[LOCAL] [abc] Update processing failed: "connect ECONNREFUSED 127.0.0.1:54525"
[LOCAL] [abc] optimisticUpdate attempt 1 failed. There are 3 attempts left.
stopping in-memory mongo...
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! direct-order-sales-updater@0.0.2 test: `nyc --reporter=lcov tape tests/*test.js  && node tests/integration-tests.js`
npm ERR! Exit status 2
```

As a temporary solution, we have disabled the integration tests but this cannot be a long term solution, as integration testing is an instrumental part of our build process.

**Comment by nodkz** [comment]
```js
const mongod = new MongoMemoryServer({
   ...otherSettings,
  debug: true
});
```
Will help to understand what exactly happens.

--------

Any errors with `_id` saving or updating documents is out of the scope of this package. Need to diagnose your drivers and test suites.

This package only 
- downloads required binaries according to your OS and selected version
- launch mongod on free port (launch several mongod in parallel, better one mongod per test suite)
- provides connection strings
- shutdown mongod

**Comment by hasezoey** [comment]
closing because stale for over 3 months
