### ISSUE TITLE
checkMD5 always fails due to recent "too small" validation being done to (small) md5 file

### ISSUE THREAD

**Issue by ronjouch** [nodkz/mongodb-memory-server#136]
I'm running:

```js
process.env.MONGOMS_MD5_CHECK = 'true';
mongoServer = new MongoMemoryServer({
  binary: {
    version: '3.6.8',
  },
});
```

Download goes just fine, but then mongoms aborts saying ` Error: Too small (76 bytes) mongod binary downloaded from https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1604-3.6.8.tgz`

Except it's not true! Manually checking the tgz downloaded in `~/.mongodb-binaries`, I confirmed the md5. And then,

```
20:14:19 ~/.mongodb-binaries ls -la mongo*
-rw-rw-r-- 1 ronanj ronanj 100520377 Feb 13 20:08 mongodb-linux-x86_64-ubuntu1604-3.6.8.tgz
-rw-rw-r-- 1 ronanj ronanj        76 Feb 13 20:08 mongodb-linux-x86_64-ubuntu1604-3.6.8.tgz.md5.downloading
                                  ^^
                                  It's the *checksum* file that is 76 bytes! :D
```

→ `httpDownload` should skip the new "too small" validation for the md5 file.

Also, I'd like to ask for md5 validation using the `binary: {checkMD5: true}` option (rather than writing to `process.env.MONGOMS_MD5_CHECK`), but it looks like the TS typings don't include this option, so tsc compilation fails.

**Comment by ronjouch** [comment]
@nodkz here's a mini-PR for both issues: https://github.com/nodkz/mongodb-memory-server/pull/137

**Comment by nodkz** [comment]
Thanks a lot. It was a urgent fix when i disabling md5 check and adding size checking. My miss. 🙃

Your fix already published on npm. 😉
