### ISSUE TITLE
Chokes if systemBinary path has spaces

### ISSUE THREAD

**Issue by dominic-p** [nodkz/mongodb-memory-server#139]
I realize that this is definitely an edge case (who has spaces in paths to binaries?), but I just ran into it, so I thought I would share.

The problem comes [from here](https://github.com/nodkz/mongodb-memory-server/blob/v3.1.1/src/util/MongoBinary.js#L158). I manually added quotes around the `binaryPath` bit and it solved the problem. It should be harmless if the path doesn't contain spaces, so it might be worth including quotes either way.

**Comment by DrogoNevets** [comment]
I have made a pull request to fix this
https://github.com/nodkz/mongodb-memory-server/pull/143

**Comment by nodkz** [comment]
@DrogoNevets please fix lint errors, and I'm ready to merge it and publish a new package version 😉

**Comment by DrogoNevets** [comment]
would you rather i allowed bitwise or re-wrote to not use bitwise at all?

**Comment by DrogoNevets** [comment]
I suggest the following:
/*eslint no-bitwise: ["error", { "allow": ["~"] }] */

best of all worlds?

**Comment by DrogoNevets** [comment]
updated and running on Travis etc
