### ISSUE TITLE
Question about TypeScript in the project

### ISSUE THREAD

**Issue by AJRdev** [nodkz/mongodb-memory-server#142]
Hi,

Having done some commits and code review of PRs on this project, I was pretty confused by the architecture of the code using Babel, Flow and TypeScript declarations files to build the project.

As I understand Flow types are used in .js files and Typescript declaration files are just used to help developers using this package with their own TypeScript projects to enable type-checking etc.. but wouldn't it be more simple to transfer the whole project to Typescript and not just use Typescript declaration files?

I'd see a couple of perks of doing so : 
* reduce the tooling around the project by getting rid of Babel (replaced by tsc) and flow by using TypeScript types
* improve DX by simplifying the code architecture by getting rid of *.d.ts files
* ease the maintenance of type modifications by centralizing the types in Typescript only and not in Flow and *.d.ts ( like the problem in this issue https://github.com/nodkz/mongodb-memory-server/issues/125 )
* simplify the npm build command by just running tsc

I admit that I've never used Flow before, so my choice of a typing framework is pretty biased since I only used TypeScript on my projects, but my initial thought was to improve the DX on this project for new contributors :)

Would love to have your thoughts on this suggestion @nodkz .

Cheers,
Andre.

**Comment by nodkz** [comment]
Great thoughts!

I'm also migrating from Flow to TS in our internal app. TS won the battle for me. So I don't see any problems to migrate, except for my current bandwidth.

If you have a willing and time you may start the migration 😉

**Comment by AJRdev** [comment]
@nodkz Awesome ! :) 

Ok I'll try to start that this week, shouldn't be too difficult to migrate to TS I think ;)
