### ISSUE TITLE
getConnectionString failing silently ubuntu 16.04

### ISSUE THREAD

**Issue by Cherviakov** [nodkz/mongodb-memory-server#144]
Linux myNix 4.13.0-39-generic #44~16.04.1-Ubuntu SMP Thu Apr 5 16:43:10 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
nodejs v10.15.1
mongodb-memory-server v3.1.1

I'm using MONGOMS_DOWNLOAD_DIR env var to download binnaries and later run script

```
const { MongoMemoryServer } = require('mongodb-memory-server');

new MongoMemoryServer().getConnectionString()
.then((res) => console.log('success', res))
.catch(err => console.error(err));
```
And nothing happening, nor error thrown not any result returned.
On another two machines with ubuntu 16.04 it does working without problem.

**Comment by nodkz** [comment]
Please provide debug output from console:

```
new MongoMemoryServer({ debug: true })...
```

**Comment by Cherviakov** [comment]
Mongo[37171] Starting MongoDB instance with following options: {"port":37171,"dbName":"4df957af-4e84-478f-98d9-253f216befa7","uri":"mongodb://127.0.0.1:37171/4df957af-4e84-478f-98d9-253f216befa7","storageEngine":"ephemeralForTest","dbPath":"/tmp/mongo-mem-28201wqhQD9yL0Lbo"} +0ms
  Mongo[37171] MongoBinary options: {"downloadDir":"/home/myNix","platform":"linux","arch":"x64","version":"4.0.3"} +2ms
  Mongo[37171] MongoBinary: found cached binary path for 4.0.3 +1ms
  Mongo[37171] MongoBinary: Mongod binary path: /home/jenkins/4.0.3/mongod +21ms
  Mongo[37171] MongoBinary: Download lock removed +10ms
  Mongo[37171] STDERR: /home/myNix/4.0.3/mongod: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory
  Mongo[37171]  +2ms
  Mongo[37171] CLOSE: 127 +1ms

**Comment by Cherviakov** [comment]
sudo apt-get install curl libcurl3 solving this

**Comment by matteoPhre** [comment]
Hi, same issue here. But i don't want to install libcurl3 on my Jenkins machine. Is the only available fix?

**Comment by Cherviakov** [comment]
What so bad about libcurl3? Well maybe you can try to copy libcurl.so.4, and any other files needed, manually and say magic words.

**Comment by matteoPhre** [comment]
Nothing bad but Jenkins machine have to be clear of all applications dependencies. It only needs node and npm package..if It needs other s.o. dependencies to make an npm package workshop, there Is something wrong

**Comment by nodkz** [comment]
Try to install other `mongod` versions without ssl. How i remember they do not require `libcurl`.

Anyway if you want to launch mongod on your Jenkins machine you must meet all its dependencies. Otherwise install mongod at another server and in such case you cannot use `mongodb-memory-server` and ask your QA team to rewrite tests 😜

**Comment by Cherviakov** [comment]
One time I decided that I am apready pro and tried to run one of my projects on minimal ubuntu. Ended up several hours installing all kinds of packages and s.o. libs. Try it yourself and you will find great deal about how much stuff you actually using by default without even thinking :)

**Comment by matteoPhre** [comment]
I'm not saying that i want minimal s.o. on Jenkins, i'm only saying that install one pkg to make an npm package of one application is not a best practice.

I think that the problem is with the latest release, because with other version of this package, everything works fine.

However i will stick version to working one.
Thanks

**Comment by avin-kavish** [comment]
How do I go about getting a version of mongo without ssl?

**Comment by Usama-Tahir** [comment]
I am using `Deepin OS` which is `debian` based and getting the following error.


```Autostarting MongoDB instance...
Called MongoMemoryServer.start() method:
mongosse opts  { poolSize: 10 }
Called MongoMemoryServer.ensureInstance() method:
Starting MongoDB instance with following options: {"port":37599,"dbName":"037042c8-9e84-4126-9b62-b10d9579869a","uri":"mongodb://127.0.0.1:37599/037042c8-9e84-4126-9b62-b10d9579869a","storageEngine":"ephemeralForTest","dbPath":"/tmp/mongo-mem-23969moRNDtLzcXzq","tmpDir":{"name":"/tmp/mongo-mem-23969moRNDtLzcXzq"}}
MongoBinary options: {"downloadDir":"/home/dev/projects/parsempo/v2/node_modules/.cache/mongodb-memory-server/mongodb-binaries","platform":"linux","arch":"x64","version":"3.6.3"}
MongoBinary: Mongod binary path: /home/dev/projects/parsempo/v2/node_modules/.cache/mongodb-memory-server/mongodb-binaries/3.6.3/mongod
Mongo[37599]: Called MongoInstance._launchKiller(parent: 23969, child: 23982):
MongoBinary: Download lock removed
Mongo[37599]: STDERR: /home/dev/projects/parsempo/v2/node_modules/.cache/mongodb-memory-server/mongodb-binaries/3.6.3/mongod: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

Mongo[37599]: CLOSE: 127
Mongo[37599]: [MongoKiller]: exit - [0,null]```

Any idea how can I solve this issue?

**Comment by Cherviakov** [comment]
@Usama-Tahir error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

**Comment by Usama-Tahir** [comment]
@Cherviakov I was able to solve this issue. 

this link helped me.

https://askubuntu.com/questions/339364/libssl-so-10-cannot-open-shared-object-file-no-such-file-or-directory
