### ISSUE TITLE
getInstanceData miss leding name

### ISSUE THREAD

**Issue by MihaFriskovec** [nodkz/mongodb-memory-server#152]
I find this method kinda confusing.
Let's say I'm stopping the server and then I want to check if the server has really stopped. I would probably try to do that with getInstanceData. As the name suggests this method returns information about the current instance.
But there are some problems, the method fires up new server even though I want to know the status of the current instance.
An example would be: I'm closing connection and shutting down the server at the end of a test and want to make sure that the server has successfully stopped. Instead of firing up a new instance I would expect to get back a message informing me that the server is successfully shut down.

But let's say it's just a miss leading name for a function and it is just a helper function to ensure the server is always running. Next question I have is, why does this method throws an error saying the database is not running and you should start it manually after it has started a new instance.

Here is a snippet from source code:
```javascript
async getInstanceData(): Promise<MongoInstanceDataT> {
    if (!this.runningInstance) {
      await this.start();
    }
    if (this.runningInstance) {
      return this.runningInstance;
    }
    throw new Error(
      'Database instance is not running. You should start database by calling start() method. BTW it should start automatically if opts.autoStart!=false. Also you may provide opts.debug=true for more info.'
    );
  }
```

**Comment by nodkz** [comment]
For you was added explicit `isRunning()` method.

```js
import MongoMemoryServer from 'mongodb-memory-server';

const mongod = new MongoMemoryServer();

const uri = await mongod.getConnectionString();
const port = await mongod.getPort();
const dbPath = await mongod.getDbPath();
const dbName = await mongod.getDbName();

// some code
//   ... where you may use `uri` for as a connection string for mongodb or mongoose

// you may check instance status, after you got `uri` it must be `true`
mongod.isRunning(); // return true

// you may stop mongod manually
await mongod.stop();

// when mongod killed, it's running status should be `false`
mongod.isRunning();

// even you forget to stop `mongod` when you exit from script
// special childProcess killer will shutdown it for you
```

**Comment by nodkz** [comment]
PS.

`getInstanceData()` works by design. We must ensure that ports are available and instance successfully started, before provide `uri` to user.

You may suggest a new better name ;)

**Comment by MihaFriskovec** [comment]
Ok, I understand. For the naming, I do have a suggestion.

`ensureInstance` - this is basically the same as `getInstanceData` and is used to ensure opened ports.

`getInstanceInfo` - method for checking the information about the current instance. This could replace `isRunning` since it can return `false` for the case the instance is not running. In case the instance is running it could just return instance data.

**Comment by nodkz** [comment]
Great suggestion!
Refactored!
