### ISSUE TITLE
`MongoMemoryReplSet` uses wrong import for `EventEmitter`

### ISSUE THREAD

**Issue by skrtheboss** [nodkz/mongodb-memory-server#157]
When i build my package with the latest `4.2.0` version, TypeScript thrwos an error: 
```
node_modules/mongodb-memory-server/lib/MongoMemoryReplSet.d.ts:2:8 - error TS1192: Module '"events"' has no default export.

2 import EventEmitter from 'events';
         ~~~~~~~~~~~~


Found 1 error.
```
---
This import should be used instead.
```typescript
import {EventEmitter} from 'events';
```

**Comment by nodkz** [comment]
Agreed open Pull Request please to this lib.

Anyway code works, but Flowtype and Typescript both have broken definitions 😭
- `import EventEmitter from 'events';` - understands Flow, but not TS
- `import { EventEmitter }  from 'events';` - understands TS, but not Flow

**Comment by nodkz** [comment]
Anyway, Typescript is in priority for us
