### ISSUE TITLE
Mongod binary is getting deleted by yarn

### ISSUE THREAD

**Issue by BrandonLWhite** [nodkz/mongodb-memory-server#159]
The projects I'm working on use the yarn package manager. We recently began integrating use of mongodb-memory-server with much delight.  However, we've noticed that yarn likes to delete subdirectories and files under node_modules that it determines do not correspond to installed packages.  Because of this, the /node_modules/.cache is being deleted whenever a yarn operation such as `yarn upgrade some-package@latest` is run.

I'm very much trying to avoid mongodb-memory-server needing to download the mongod binary during test execution with the preference being to download it on package installation of mongodb-memory-server.  The initial `yarn install` works fine.  But after that whenever you use yarn to make any changes to packages, the .cache file gets removed and the mongodb-memory-server post install script is NOT run.

In my limited research, it seems that Yarn does not like things writing to node_modules and they are [very opinionated about this stance](https://github.com/yarnpkg/yarn/issues/5709).
I'm wondering if there is a way for mongodb-memory-server to indicate that the mongod binary belongs to the package so as to prevent yarn from pruning it.

**Comment by nodkz** [comment]
According to this issue we should drop using `find-cache-dir` package and migrate on some another solution.

How do you think better to store cache somewhere globally or inside node_modules?

Related issue
https://github.com/nodkz/mongodb-memory-server/issues/95

**Comment by AJRdev** [comment]
@BrandonLWhite as a quick fix, couldn't you use the environment variable **MONGOMS_DOWNLOAD_DIR** to specify a binary download directory instead of the default /node_modules/.cache directory ?

**Comment by BrandonLWhite** [comment]
@AJRdev We avoid requiring special environment setups.  `yarn && yarn test` for example, must do everything needed for developers and CD/CI containers (eg Jenkins).  If you know of a way to set an environment var from a package please let me know!
I am using mongodb-memory-server in a private package library which is then a devDependency of dozens of other packages.  My goal is to manage all mongodb-memory-server settings from within my private package.
Out of scope for this ticket/issue, but I would like to see a way to configure the mongodb-memory-server binary from within the package.json of another package.  I hope to be able to look into this soon.  

The dream would be:

- Package myTestLib has mongodb-memory-server as a dependency.
- Package myTestLib contains a parameter for the mongod binary version, and possibly the download destination directory, in its package.json.
- Numerous other Node applications have myTestLib as a devDependency.  Running `yarn` (or `npm install`, for example) installs everything with no additional prerequisite environment variable setup. This includes downloading the right mongod version to the right location.

**Comment by martin-watts** [comment]
@nodkz  
> According to this issue we should drop using `find-cache-dir` package and migrate on some another solution.
> 
> How do you think better to store cache somewhere globally or inside node_modules?

You could do something like [Angular's webdriver-manager](https://github.com/angular/webdriver-manager) and just store the binaries in a sub-folder of node_modules/mongodb-memory-server/ by default. 

It seems to work ok most of the time, but occasionally the output folder goes walkabouts, and a `yarn webdriver-manager update` command needs to be issued.

I guess global is possible, (somewhere under process.env.APPDATA/process.env.HOME?) but potentially more likely to be a restricted write location, I'd have thought.

**Comment by nodkz** [comment]
I think that we should migrate repo to `Lerna` and create several packages for different purposes:
- mongodb-memory-server-core – core package with current code without auto download
- mongodb-memory-server-global – stores binaries in `appdata` or `home`, just contains postinstall 
- mongodb-memory-server – stores in `node_modules`, just contains postinstall script

With Lerna it's very easy to maintain. But installation of the needed package solve many problems and opens new possibilities for the community.

Also, maybe need to give to the current package a shorter name...

@AJRdev @martin-watts @BrandonLWhite What do you think?

**Comment by martin-watts** [comment]
@nodkz It's your call, but seems like lot of effort to split in to separate modules to solve this particular case.

I'd opt for sensible defaults with the ability to change it if necessary. 

Given `npm` and `yarn` stomp all over node_modules as they see fit, maybe go for the global option, but retain the MONGOMS environment variables so that people can change it as necessary.

An alternative would be to not auto-download, then require users to ensure the binaries are available by exporting an async prepare function for the consumer to call (e.g. in jest.setup.js):

```javascript
const MongoMemoryServer = require('mongodb-memory-server');

// I think Jest can do this, other libraries have their own place to perform async pre-steps
module.exports = async() => { 
  await MongoMemoryServer.prepare({
      version: '4',
      downloadDir: '~/.mongo-binaries',
      // etc... give options for all things that currently need to be set via env variable overrides 
  };
}
```

With all options being optional, and using sensible defaults if they aren't provided. 

Where `MongoMemoryServer.prepare` sets environment variables based on the config it receives, then does what the postinstall script does now.

**Comment by BrandonLWhite** [comment]
I aim to avoid the following:
- Any downloads during test execution.
- Any special environment variable setup beyond what can be done from package.json (but not in the script shell commands).

My hypothesis is that these goals can be achieved.  More investigation needs to be done.

- I recall reading in the yarn Issues some brief discussion of fixing yarn so that files produced as a result of postInstall would be preserved by the yarn integrity prune (or whatever they call it).  I want to fully explore what yarn (and npm if applicable) make available for packages to indicate additional files to preserve.  A good starting point will be to see how yarn behaves if mongodb-memory-server saves the binary under it's own subdirectory instead of crawling back up to node_modules/.cache and putting it there.  Just a hunch, but maybe breaking out of your package's subdirectory is frowned upon and yarn puts the kibosh on it.

- I want to explore possible ways to specify the Mongo version to download and use via package.json, or maybe some other file (eg .npmrc in the project)  Ideally I want to achieve this in my own intermediate testing utils module, but if it is only viable to do it in the top level package.json that might be acceptable.
My first wild attempt would be to see if there is a viable way to parse package.json of the dependent package from the postInstall script.

**Comment by nodkz** [comment]
In early versions, this package did not download binaries and force users to set big timeouts in their tests scripts. It was very uncomfortable.

@BrandonLWhite gives a great idea about the additional ways of providing configs via `package.json` or `.dotfile`. For example, how it did Jest – you may provide configs via `jest` property in `package.json`; or `jest.config.js` file in root directory of the project; or via `argv`.

So need to find a good package which provides such ability – read env, package.json, .dotfile in the desired order. As a candidate, I suggest the following package https://github.com/indexzero/nconf
But maybe exists better package.

**Comment by nodkz** [comment]
Folks, need your help. I want to rename this library in something short.

@kjarmicki making great feature #167 (adds an ability to provide configs via package.json's property  `config.mongoDbMemoryServer`). Also, we have awful `MONGOMS_*` env variables, and long package name `mongodb-memory-server` (which allows to launch mongo not only in memory).

So I decide to unify all names and setting with better library name with following restrictions:
- short name
- one-word
- same naming for packages, envs vars and config in package.json

So current candidates:
```
mongodb-test
mongotest
mongorunner
mongorun
mongolaunch
mongostart
mongoinit
mongodev
```

What name do you like or may suggest better?

**Comment by martin-watts** [comment]
I think of the package as being a mongodb manager: It's a shame that `mango`, `mangodb`, and `mongoman` are already taken. I also thought about `mongodbms` but `dbms` is already a well known term so it might confuse people.

I think `mongorun` or `mongorunner` would be my pick, seeing as people might be using it for things other than testing, and it also handles stopping the mongod instances.

That said: `mongodb-memory-server` is currently the 6th result when I search npm for 'mongodb', so... it might be a bit long and it might not accurately reflect all that the package can do, but do you want to risk giving it up?

**Comment by BrandonLWhite** [comment]
I suggest not changing the name.  For the environment vars, make them long and consistent too: `MONGODB_MEMORY_SERVER_*`.

I agree with avoiding throwing away the search results and references to this project.  Heck, it is directly referenced in Jest documentation.  Sure, most of the concerns in this library revolve around fetching, launching, and terminating the mongod process -- the in-memory aspect is just a small configuration detail.  Nevertheless, I think you will serve the most people by continuing to convey that this library is for  quick and easy throw-away in-memory MongoDB servers.  I believe the current name does this job better than any proposed thus far.

On another note, I'm very appreciative of the recent work to being done to improve the binary download version and location configurability!  I'm eager to uptake it in my projects.

**Comment by nodkz** [comment]
Just drop a line to @arunoda to transfer ownership of `mongotest` package. I think it's the best name for the current family of packages. It solves all our problems with naming and provides the clear meaning of package purposes.

**Comment by hasezoey** [comment]
@nodkz should this issue be closed? (in my eyes it is solved because of the `-global` package)
