### ISSUE TITLE
postinstall fail on certificate issue

### ISSUE THREAD

**Issue by talr1** [nodkz/mongodb-memory-server#162]
trying to install this package for the first time and it fails due to postinstall script and certificate issue.  i can bypass the postinstall script by using MONGOMS_DISABLE_POSTINSTALL but every developer will face the same issue and i'd like to avoid it.
possible suggestions:

1. make postinstall optional
2. have some options set in package.json to overcome this issue (i saw there is a thread about it)

and to the issue at hand....
what i need to do in order to solve the "Error: self signed certificate in certificate chain"  error?
i'd appreciate if this is not a manual process that needs to be set on the env as i'm not the only one working on the source code.
i'm using the package for testing, so it should be simple: clone src, run test....

Info: 
local dev machine: win10
CI/CD: Linux based
node: 10.15
mongodb-memory-server: "^4.2.1"

**********************************************************

```
>npm install mongodb-memory-server --save-dev

> mongodb-memory-server@4.2.1 postinstall [src]\node_modules\mongodb-memory-server
> node ./scripts/postinstall.js

mongodb-memory-server: checking MongoDB binaries cache...
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:631:8)
Emitted 'error' event at:
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mongodb-memory-server@4.2.1 postinstall: `node ./scripts/postinstall.js`
npm ERR! Exit status 1
```

*********************
Thanks

**Comment by roncsak** [comment]
I have the very same error.

**Comment by izidan** [comment]
would be nice to inherit the npm global config settings for strict-ssl as well as proxy/https-proxy settings

**Comment by nodkz** [comment]
@talr1  Use mongodb-memory-server-core package which dos not have postinstall script.

@izidan Pull request welcome 😉

**Comment by roncsak** [comment]
Inside MongoBinaryDownload.ts:

    interface HttpDownloadOptions {
      hostname: string;
      port: string;
      path: string;
      method: 'GET' | 'POST';
      rejectUnauthorized: boolean;
      agent: HttpsProxyAgent | undefined;
    }

    [...]

    async download(downloadUrl: string): Promise<string> {
      const proxy =
        process.env['yarn_https-proxy'] ||
        process.env.yarn_proxy ||
        process.env['npm_config_https-proxy'] ||
        process.env.npm_config_proxy ||
        process.env.https_proxy ||
        process.env.http_proxy ||
        process.env.HTTPS_PROXY ||
        process.env.HTTP_PROXY;

      const strictSsl= 
        (process.env['npm_config_strict-ssl'] == "false") ? false : true;

    [...]

    const downloadOptions: HttpDownloadOptions = {
      hostname: urlObject.hostname,
      port: urlObject.port || '443',
      path: urlObject.path,
      method: 'GET',
      rejectUnauthorized: strictSsl,
      agent: proxy ? new HttpsProxyAgent(proxy) : undefined,
    };

Would this resolve the problem?

**Comment by izidan** [comment]
yep, just tested locally by hard coding rejectUnauthorized: false and it worked. looking forward for releasing this change :)

**Comment by izidan** [comment]
@nodkz any chance of merging the simple fix above by @roncsak as this will also solve #172

**Comment by nodkz** [comment]
@izidan If somebody provides a Pull request with tests, I'll with love merge it.

Currently, I have no bandwidth to do it myself.
