### ISSUE TITLE
"MongoMemoryReplSet.waitUntilRunning" returning before all ready

### ISSUE THREAD

**Issue by mathieug** [nodkz/mongodb-memory-server#166]
I'm trying to use the replicaset feature from mongodb-memory-server.

With this snippet:
```ts
const test = require('ava');
const { MongoMemoryReplSet } = require('mongodb-memory-server');
const { MongoClient } = require('mongodb');

const mongoReplSet = new MongoMemoryReplSet({
  debug: true,
  replSet: {
    count: 3,
    configSettings: { electionTimeoutMillis: 500 }
  }
});

test.before('Init', async () => {
  await mongoReplSet.waitUntilRunning();

  process.env.MONGODB_URI = `${await mongoReplSet.getConnectionString()}?replicaSet=testset`;
  console.log('process.env.MONGODB_URI:', process.env.MONGODB_URI);

  process.env.MONGODB_DBNAME = await mongoReplSet.getDbName();
  console.log('process.env.MONGODB_DBNAME:', process.env.MONGODB_DBNAME);

  const mongoClient = await MongoClient.connect(process.env.MONGODB_URI, { useNewUrlParser: true });
  const dbConn = mongoClient.db(process.env.MONGODB_DBNAME);

  dbConn.on('close', () => logger.warn('MongoDB event `close`'));
  dbConn.on('error', (err) => logger.warn('MongoDB event `error`:', err)); // eslint-disable-line promise/prefer-await-to-callbacks
  dbConn.on('fullsetup', () => logger.info('MongoDB event `fullsetup`'));
  dbConn.on('reconnect', () => logger.info('MongoDB event `reconnect`'));
  dbConn.on('timeout', () => logger.warn('MongoDB event `timeout`'));
});

test('Success!', (t) => {
  t.truthy(true);
});
```

I get:
```txt
  MongoError {
    [Symbol(mongoErrorContextSymbol)]: {},
    message: 'no primary found in replicaset or invalid replica set name',
  }
```

**Comment by fracasula** [comment]
What if you use an `electionTimeoutMillis: 10000` (10 seconds) which is the MongoDB default? Do you still get the error?

**Comment by mathieug** [comment]
Still `MongoError: no primary found in replicaset or invalid replica set name`

![image](https://user-images.githubusercontent.com/951183/56145550-cbcd1080-5fa4-11e9-86e7-17210b971ba2.png)

**Comment by fracasula** [comment]
I had (actually still have) issues with the `waitUntilRunning` function which seems to be returning before the cluster is ready.

In my code I had to do the following:

```js
export const wait = (t: number) => new Promise(res => setTimeout(res, t))

// init your replica set here
// ...
await replicaSet.waitUntilRunning()
await wait(2000) // sleep a bit before connecting to the servers
```

Might be worth trying to see if that's the case.

**Comment by mathieug** [comment]
It works with `await wait(2000)`

**Comment by mathieug** [comment]
Same behavior with mongodb-memory-server version 5.0.4

**Comment by fracasula** [comment]
OK cool, guess you're having the same issue that I have. I didn't write that code and unfortunately I haven't had the time yet to look into it either.

**Comment by MickL** [comment]
I dont see this beeing fix or am I missing something? I tried all kind of timeouts:

```
const mongod = await MongoMemoryReplSet.create({
        replSet: {
            count: 4, // or 1
        },
    });
    await mongod.waitUntilRunning();
    await setTimeout(2000);
```

but I still get the error:
Unable to acquire lock '{13560221174976606282: Collection, 2031006128908136522, name}' within 5ms' milliseconds.

**Comment by hasezoey** [comment]
@MickL your issue looks different, please open a new issue providing all required information (including the [Debug Output](https://nodkz.github.io/mongodb-memory-server/docs/guides/enable-debug-mode))

also note that awaiting `.create` will wait until all are running and do not need a extra `.waitUntilRunning`
