### ISSUE TITLE
MongoDB version 3.0 doesn't work

### ISSUE THREAD

**Issue by LieAlbertTriAdrian** [nodkz/mongodb-memory-server#175]
```ts
const mongod = new MongoMemoryServer({                
    instance: {
        port: 15854,
        dbName: 'mock-db'
    },
    binary: {
        version: 'v3.0-latest'
    }
});

console.log('memory server');
(async function () {
    const mongoURI = await mongod.getConnectionString();
    
    console.log(mongoURI);    
})();
```

I tried to run this code using mongodb-memory-server@4.2.1 but the program closes silently. When I tried to run mongoDB using binary version of 3.4.20, it logs the mongoURL, hence the problem only exists when I run mongoDB 3.0.x. 

Anyone knows the root cause of this issue?

**Comment by hasezoey** [comment]
could you provide the OS you were using?

because maybe `linux/mongodb-linux-x86_64-SomeOS-v3.0-latest.tgz` just didnt exist

**Comment by hasezoey** [comment]
closing because stale for over 3 months
