### ISSUE TITLE
Access denied for binary download

### ISSUE THREAD

**Issue by rolurq** [nodkz/mongodb-memory-server#178]
When I try to run the server it fails with this error
```
Error: Too small (243 bytes) mongod binary downloaded from https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian-4.0.3.tgz
```
Then, checking the url shows this error
```xml
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>90F2D7CEEF06D5F1</RequestId>
  <HostId>
gVv8op4OfNK9bvtM/Kp4JPEzZmC1JWYTO4iv31JhWtzbPA0/Zezxfp0N8pADFiTG05GxlTSaJtI=
  </HostId>
</Error>
```

**Comment by fc53533** [comment]
same for `https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian92-3.6.3.tgz`

**Comment by 360disrupt** [comment]
Same here. Why do I need to download anyway, I got a local install of MongoDB 4.2.1 community, can I directly use that? If I don't specify the option 

```
    binary: {
        version: '4.2.0',
    },
```
It uses an older version (probably the binary which was downloaded before).

Is there a way to specify a path to the binary:
```
which mongod 
/usr/local/bin/mongod

```
I have s.th. like this in mind:

```
    binary: '/usr/local/bin/mongod',
```
Or isn't this working because the memory server is a complete diff. binary?

**Comment by hasezoey** [comment]
@360disrupt this package is build to use the specified versions (/ default), and not the "installed one", but would could change that with `MONGOMS_SYSTEM_BINARY` (and search for you installed `mongod`, like `which mongod`) 
-> or in JS:
```ts
new MongoMemoryServer({
  binary: {
    systemBinary: "path/to/mongod"
  }
});
```

---

as for @rolurq's original question, it seems like the version string was not generated right (missing the debian version)
-> @rolurq does it still happen with 6.2+(this package)?

---

as for @fc53533, it seems that this version is not available anymore

**Comment by hasezoey** [comment]
closing because stale for over 3 months
