### ISSUE TITLE
Ubuntu 19.04 Support

### ISSUE THREAD

**Issue by nafees-rawji** [nodkz/mongodb-memory-server#179]
I believe `MongoBinaryDownloadUrl.ts` is defaulting to the binaries for Ubuntu 1404 which are dependent on libcurl3, Ubuntu 19.04 comes pre-installed with libcurl4 (which cannot co-exist with libcurl3). As a result getConnectionString never resolves, and my unit tests time out. As far as I'm aware there currently are no binaries for Ubuntu 19.04 but I imagine the 1804 binaries would be better supported. Adding a case for Ubuntu 1904, to the code below (found in `MongoBinaryDownloadUrl.ts`) would likely fix the problem. I would submit the pull request myself but I'm not familiar with how to locally test npm packages.

```
if (os.release === '12.04') {
            name += '1204';
        }
        else if (os.release === '14.04') {
            name += '1404';
        }
        else if (os.release === '14.10') {
            name += '1410-clang';
        }
        else if (majorVer === 14) {
            name += '1404';
        }
        else if (os.release === '16.04') {
            name += '1604';
        }
        else if (majorVer === 16) {
            name += '1604';
        }
        else if (majorVer === 18) {
            if (this.version && this.version.indexOf('3.') === 0) {
                // For MongoDB 3.x using 1604 binaries, download distro does not have builds for Ubuntu 1804
                // https://www.mongodb.org/dl/linux/x86_64-ubuntu1604
                name += '1604';
            }
            else {
                // See fulllist of versions https://www.mongodb.org/dl/linux/x86_64-ubuntu1804
                name += '1804';
            }
        } else {
            name += '1404';
        }
        return name;
```

**Comment by hmarlo** [comment]
The function `os.release` in Ubuntu 19.04 returns me `'5.0.0-13-generic'` which looks like the kernel. So we should get the information from other source other than `os.release`.

**Comment by nodkz** [comment]
Please try v5.1.1

**Comment by hmarlo** [comment]
Working great for me!

**Comment by nodkz** [comment]
Credits to @adrienboulle #183 🙏👍

**Comment by maloguertin** [comment]
> Please try v5.1.1

This worked for me!

**Comment by henrikq** [comment]
@nodkz doesn't v5.1.1 work for me on ubuntu 19.04 (nor does 5.2.3). I get:

Mongo[33475]: STDERR: /home/henrikq/proj/pat/node_modules/.cache/mongodb-memory-server/mongodb-binaries/4.0.3/mongod: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

And ` libcrypto.so.1.0.0` doesn't seem to be in the repo:
https://packages.ubuntu.com/search?searchon=contents&keywords=libssl.so&mode=filename&suite=disco&arch=i386

Furthermore, I would expect to see the message above without a debug flag, and for getConnectionString to reject.

**Comment by nodkz** [comment]
@henrikq you can open pull request with error message for libcrypto.so and a solution how to fix it.

It can be done very easily by adding similar code like this
https://github.com/nodkz/mongodb-memory-server/blob/master/packages/mongodb-memory-server-core/src/util/MongoInstance.ts#L235-L238
