### ISSUE TITLE
More Windows space in path issues

### ISSUE THREAD

**Issue by dominic-p** [nodkz/mongodb-memory-server#180]
This is a follow up from #139.

I thought the fix for that issue solved it, but when I tested again today. I got a new error:

```
Mongo[53261] MongodbInstance: is failed: Error: spawn "C:\Path to Binaries\bin\mongod.EXE" ENOENT +14ms
(node:14412) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at MongodbInstance._launchKiller (C:\Path to Project\my-project\node_modules\mongodb-memory-server\lib\util\MongoInstance.js:152:148)
    at C:\Path to Project\my-project\node_modules\mongodb-memory-server\lib\util\MongoInstance.js:105:35
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Path to Project\my-project\node_modules\mongodb-memory-server\lib\util\MongoInstance.js:16:103)
    at _next (C:\Path to Project\my-project\node_modules\mongodb-memory-server\lib\util\MongoInstance.js:18:194)
```

I think the issue might be related to [this node.js bug](https://github.com/nodejs/node/issues/7367#issuecomment-229721296) which was not fixed. The workaround they mention is to quote the path to the command (already done in #139) and add `shell: true` to the spawn options.

I tried adding it [here](https://github.com/nodkz/mongodb-memory-server/blob/v5.1.0/packages/mongodb-memory-server-core/src/util/MongoInstance.ts#L157) and it solved the problem, but I don't know if that's a good idea to do in all cases.

Maybe something like [cross-spawn](https://www.npmjs.com/package/cross-spawn) would be a better option?

**Comment by nodkz** [comment]
Cross-spawn looks good.
Can you make pull request?

**Comment by dominic-p** [comment]
I can take a stab at it. Unfortunately, I don't have any TypeScript experience or yarn, so it will take some setup and a bit of time.

**Comment by dominic-p** [comment]
Ok, I gave it a shot. As I said in the PR, I couldn't figure out how to test it locally though.
