### ISSUE TITLE
Update Example to use { MongoMemoryServer }

### ISSUE THREAD

**Issue by webberwang** [nodkz/mongodb-memory-server#181]
```
import MongoMemoryServer from 'mongodb-memory-server';
```

doesn't work with Typescript

![codelab-ui____Code_UIB_codelab-ui__-_____packages_api_test_example_test_ts__codelab-ui_](https://user-images.githubusercontent.com/26264925/57177062-0217e600-6e15-11e9-9305-bb80305324d0.jpg)

```
import { MongoMemoryServer } from 'mongodb-memory-server';
```
works

![codelab-ui____Code_UIB_codelab-ui__-_____packages_api_test_example_test_ts__codelab-ui_](https://user-images.githubusercontent.com/26264925/57177036-c4b35880-6e14-11e9-84af-7bf4da920af6.jpg)

**Comment by shilangyu** [comment]
this can be closed now(?)
