### ISSUE TITLE
postinstall script fails on Amazon Linux box

### ISSUE THREAD

**Issue by Musikolo** [nodkz/mongodb-memory-server#184]
Hi,

I have noticed that the `postinstall` script fails downloading MongoDB binaries on a Amazon Linux box with Red Hat:
```
...etc...

> mongodb-memory-server@5.1.0 postinstall /home/bamboo/bamboo-agent-home/xml-data/build-dir/BS-BDSNSEV-JOB1/bd-lambdas/sns-event-recorder/node_modules/mongodb-memory-server
> node ./postinstall.js
mongodb-memory-server: checking MongoDB binaries cache...
Downloading MongoDB 4.0.3: NaN % (0mb / NaNmb)
failed to download/install MongoDB binaries. The error:
Error: Too small (243 bytes) mongod binary downloaded from https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-rhel-4.0.3.tgz

...etc...
```

 The problem seems to be caused by how the download URL is built. The URL that builds is:
 - https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-rhel-4.0.3.tgz

but it should built the following one instead:
 - https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-rhel70-4.0.3.tgz

Just in case it helps, I'm providing with some additional information about this box:
```
$> cat /etc/os-release

NAME="Amazon Linux AMI"
VERSION="2016.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2016.03"
PRETTY_NAME="Amazon Linux AMI 2016.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2016.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

$> uname -a
Linux ip-1-2-3-4 4.4.11-23.53.amzn1.x86_64 #1 SMP Wed Jun 1 22:22:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

On a side node, I think it would be nice to have a new `MONGO_BINARIES_DOWNLOAD_URL` environment variable that overrides all the inference process that directly downloads the file.

Thank you!

**Comment by silesky** [comment]
agree that MONGO_BINARIES_DOWNLOAD_URL would be useful

**Comment by duro** [comment]
@Musikolo @silesky I'm running into similar issues. I'm trying to run version 4.2.0 of MongoDB inside a circle build job which is using an Amazon Linux 2 docker image.

I documented my issue here: https://github.com/nodkz/mongodb-memory-server/issues/226#issuecomment-541241047

However, your suggestion of a MONGO_BINARIES_DOWNLOAD_URL env var, or a way to explicitly define the download URL in the server instantiation would be very helpful, as I can find the exact binary download URL I need here:

https://www.mongodb.org/dl/linux/x86_64-amazon2

**Comment by hasezoey** [comment]
@Musikolo is this still a problem in 6.1.0? (getos got replaced)

**Comment by Musikolo** [comment]
Hi @hasezoey,

No, the problem looks solved. With previous version `5.1.1`, we found the following nasty hack to work around the issue:
```
export MONGOMS_DOWNLOAD_MIRROR=https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-rhel70-4.0.3.tgz?dummy=
```

Now with version `6.1.1`, we no longer need that, and everything works as expected. The only thing we had to do is installing the `redhat-lsb-core` package, because the `lsb_release` command is now required. That's all.

Thank you so much for your help! ;-)

**Comment by hasezoey** [comment]
> because the lsb_release command is now required. That's all.

it is *not* required, steps it currently does:
- checks if `lsb_release` is an actual command (and executes it if possible)
- otherwise check for an `/etc/os-release` file (and read it)
- otherwise check for an `/etc/*-release` file (get the first one and read it)
- otherwise fail

**Comment by Musikolo** [comment]
Well, that could be case of what happened in our build server. This is what we got before installing `lsb_release` command:

```
build	23-Dec-2019 15:42:36	added 504 packages from 805 contributors in 7.53s
build	23-Dec-2019 15:42:45	
build	23-Dec-2019 15:42:45	> mongodb-memory-server@6.1.1 postinstall /home/bamboo/bamboo-agent-home/xml-data/build-dir/job1/test-app/node_modules/mongodb-memory-server
build	23-Dec-2019 15:42:45	> node ./postinstall.js
build	23-Dec-2019 15:42:45	
build	23-Dec-2019 15:42:45	mongodb-memory-server: checking MongoDB binaries cache...
build	23-Dec-2019 15:42:45	failed to download/install MongoDB binaries. The error:
build	23-Dec-2019 15:42:45	Error: Command failed: lsb_release -a
build	23-Dec-2019 15:42:45	/bin/sh: lsb_release: command not found
```

Not sure if more descriptive message would be any more helpful.

Thanks for the clarification.

**Comment by hasezoey** [comment]
@Musikolo 250651f36718b0fc871daef12640cca6218da6cf in #252 should fix this

**Comment by Throckmortra** [comment]
still seeing this on `6.2.4`

Centos 8

**Comment by hasezoey** [comment]
@Throckmortra please provide more infomation, like do you have an /etc/os-release file or any /etc/*-release file?

**Comment by Throckmortra** [comment]
@hasezoey yes

```
bash-4.4# cat /etc/os-release
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"
```

**Comment by Throckmortra** [comment]
@hasezoey let me know if you need anything else, I guess I'll set `MONGOMS_DOWNLOAD_MIRROR` for now

**Comment by hasezoey** [comment]
@Throckmortra when possible, could you provide the debug output of `mongo-memory-server`?

```ts
new MongoMemoryServer({
  debug: true // set this option
});
```
