### ISSUE TITLE
Options can only be set in outermost package.json

### ISSUE THREAD

**Issue by czr** [nodkz/mongodb-memory-server#187]
The README says that options can be [set in package.json](https://github.com/nodkz/mongodb-memory-server#options-which-can-be-set-via-packagejsons-config-section). Given the following project structure, the options can only be set in `project/package.json`, and not in `project/subproject/package.json`. (Any options set in `project/subproject/package.json` are ignored.):

    project
    |-- subproject
    |   |-- package.json
    |   +-- ...
    |-- package.json
    +-- ...

This seems counter-intuitive to me. I'd suggest that options set in the subproject should at least have higher precedence than options in the project.

The cause of this is the loop in [`getPackageJson()`](https://github.com/nodkz/mongodb-memory-server/blob/master/packages/mongodb-memory-server-core/src/util/resolve-config.ts#L11) which exhausts the find-package-json iterator, returning the last value rather than the first. Is there a specific need to use the outermost package.json? If not then I'd suggest just taking the first value and leaving it at that. If we do need values from the outermost package.json then I'd suggest that `resolveConfig()` could reconcile the values extracted from each package.json, giving priority to the subprojects first.

Thoughts? I'm happy to make a pull request.

**Comment by nodkz** [comment]
@kjarmicki can you explain why we are using the outermost package.json?
I agree with @czr that subproject package.json should have higher precedence.

PS. One more addition, for simplicity we should not merge configs from different package.json files. Must work only one package.json config.

**Comment by kjarmicki** [comment]
The main reason I decided to go with the topmost package.json was that due to how npm resolves dependencies I couldn't be sure whether the current package.json belongs to some installed module or to the main project.

Let's say that we'd go with the first package.json. Let's also say that we have a project that has dependency `A` and dependency `B` in the package.json and they both require mongodb-memory-server (possible, given the number of packages that [already depend on it](https://www.npmjs.com/package/mongodb-memory-server?activeTab=dependents)). Then the structure of the project looks like this:
```
package.json
node_modules
  - A
    package.json
    node_modules
      - mongodb-memory-server
  - B
    package.json
    node_modules
      - mongodb-memory-server
```
Now, if we'd check the first package.json, that would be `A`'s and `B`'s one for each installation, not the project's one. I couldn't figure out the better way to ensure that we're in the main project directory than going to topmost package.json.

**Comment by nodkz** [comment]
Thanks for the explanation! 👍

I think that we can take the first package.json file **which contains configs**. It will be something abnormal if some depended packages will contain mongodbMemoryServer configs in their package.json files.

What do you think?

**Comment by kjarmicki** [comment]
It's clearly a corner case but I wouldn't consider it abnormal. If some installed module depends on mongodb-memory-server then it's possible that it will have configuration for it declared in it's package.json. 

Take [this module](https://www.npmjs.com/package/@shelf/jest-mongodb) as an example. It wraps mongodb-memory-server but also contains tests of it's own. Let's say module author decided to test his module using particular mongodb version and declared that version in the module's package.json. If we'd look up for first package.json containing configuration then module's one would be picked up, not the main project's one.

Again, corner case :) but certainly possible.

**Comment by czr** [comment]
@nodkz and @kjarmicki, thanks for the explanations and discussion!

I have a suggestion: Currently we're starting the search at `__dirname`. I suggest instead that we start from `path.dirname(process.argv[1])` (or alternatively, `process.cwd()`) and use only the first package.json that we find.

That should work for the scenario @kjarmicki describes. The test scripts in (to use @kjarmicki's example) jest-mongodb would use the configuration in defined in jest-mongodb. It would mean that anyone writing tests that used jest-mongodb would have to do their own configuration in their own package.json, but that's probably desired. After all, my guess is that most people using these modules are doing local tests to see how their code will interact with a MongoDB instance that's part of their own infrastructure.

It would mean that you wouldn't be able to share configurations across multiple modules, but it sounds like that's not something that we want to do anyway.

Note that in the case of test scripts, `process.argv` may look something like this:

      [ '/Users/czr/.nvm/versions/node/v8.10.0/bin/node',
        '/Users/czr/Projects/Dashboard/dashboard/server/node_modules/.bin/jest' ]

So `process.argv[1]` will be `jest` rather than the test script itself. That's why I was wondering about `process.cwd()`.

Relevant docs:

* __dirname: https://nodejs.org/api/modules.html#modules_dirname
* process.argv: https://nodejs.org/docs/latest/api/process.html#process_process_argv
* process.cwd(): https://nodejs.org/docs/latest/api/process.html#process_process_cwd

**Comment by nodkz** [comment]
Need to look at the source code of prettier, eslint or jest itself. They use a similar pattern of providing configs via package.json or rcfiles and perfectly work with monorepos.

In the upcomming week I will have 3 talks, so have no time to dive to this problem. @czr hope you can take care of this problem. 🙏 Thanks.

**Comment by czr** [comment]
Yes, good point, we can look at what other projects do. I'll aim to take a look over the next few days and see what I can do.

**Comment by czr** [comment]
I took a look at those projects:

* Prettier has the advantage that it's looking for config for a given source file, so it can start its search at the source file's directory. (And it uses [cosmiconfig](https://github.com/davidtheclark/cosmiconfig) to do the search.) That's not relevant for us because we don't have a particular file that we're looking at. **However,** if the source code is passed in on stdin, then it will (simplifying slightly) search for config starting at the current working directory.
* ESLint similarly is loading config for each source file that it lints. (Though the code is rather more complex.)
* Jest starts its search from the current working directory (if `--projects` isn't specified).

On the basis of that, I'd recommend starting our search from `process.cwd()`. It seems reasonable to me to assume that if you're putting configuration in your package.json then you would also run the code from there. And other projects clearly make the same assumption.

If there are no objections, I'll make that change and submit a PR.

(I can imagine some tricky scenarios, e.g. using Jest to test several projects from a monorepo. I'll do some tests to see how that works.)
