### ISSUE TITLE
Unknown linux distro Arch linux

### ISSUE THREAD

**Issue by opensourcegeek** [nodkz/mongodb-memory-server#188]
For some reason the tests are looping through and I see the message 'Unknown linux distro Arch linux, falling back to legacy MongoDB build' - I haven't looked into the details, just checking if there is something trivial I'm missing.

**Comment by hasezoey** [comment]
arch linux is currently not handeled by the version-string factory

**Comment by Musikolo** [comment]
I have not issues using Arch Linux, at least, with version `5.1.1` and `6.1.1`. Everything worked as expected. Not sure if this was an old thing that was later fixed.

I hope it helps!

Thanks.

**Comment by hasezoey** [comment]
Closing in favor of #248
