### ISSUE TITLE
The replicaSet option is missing when get connection uri from getConnectionString

### ISSUE THREAD

**Issue by supachailllpay** [nodkz/mongodb-memory-server#190]
Hi, I'm new to MongoDB replica set but from [Connection String Formats](https://docs.mongodb.com/manual/reference/connection-string/). It seems the replicaSet option is required.

```javascript
const replSet = new MongoMemoryReplSet({
  replSet: {
    count: 3
  }
})
await replSet.waitUntilRunning()
const uri = await mongod.getConnectionString() + '?replicaSet=testset' // I have to add this to make it works
```

I'm not sure this intended or its missing.

Thank you.

**Comment by nodkz** [comment]
Strting from v6.0.0 `mongod.getConnectionString()` will add '?replicaSet=testset' by default.

Prior v6.0.0 you will need to add it manually
