### ISSUE TITLE
MongoDB v3 packages fail to decompress

### ISSUE THREAD

**Issue by letalumil** [nodkz/mongodb-memory-server#195]
Hello! It seems that the package has problems with extracting MongoDB v3 packages. Everything works fine with MongoDB v4, but when I tried to download v3.2, v3.4, v3.6 then I got some problems.

So when I try to execute the script:
```js
const { MongoMemoryServer } = require('mongodb-memory-server');

new MongoMemoryServer({
    binary: {
        version: '3.2.22'
    }
});
```
The the output is:
```sh
$ node index.js 
Downloading MongoDB 3.2.22: 96.1 % (74.5mb / 77.6mb)
```
And then the process freezes.

I tried to find the cause of the issue, and it seems that it's the `decompress` package. The execution freezes on this [line](https://github.com/nodkz/mongodb-memory-server/blob/2834df017632c00dd0277a790fabf95e9d80e14c/packages/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts#L186). I tried to dig deeper into `decompress`, but the only thing I was able to find is that decompress freezes [this line](https://github.com/kevva/decompress-targz/blob/c1c39c050783186c5ba38716ed4782cfca6d3bad/index.js#L25) so that [this Promise](https://github.com/kevva/decompress/blob/74a462a139cc2561b6695e696266c8dc31562d3d/index.js#L19) never gets resolved.

Here is some information about my environment:
```sh
$ npm view mongodb-memory-server version
5.1.4

$ node -v
v10.15.3

$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.14.5
BuildVersion:   18F132
```

**Comment by wolfejw86** [comment]
i am also having this issue, is there an update on this?

**Comment by RileyMShea** [comment]
I am also having this,  on ubuntu 19.10 with "mongodb-memory-server": "^6.5.2".  Appears that the regex for `decompress` is possibly only looking for `/\d\.\d\.\d/` so versions with double digit minor/patches, or versions with text characters fail the regex match.

ie

- 4.4.4 good
- v4.4.4 fail
- 3.2.11 fail
- 4.4-latest fail

**Comment by hasezoey** [comment]
@RileyMShea from which file & line do you have this regex and why `decompress`? because since 6.4.1 `decompress` got replaced

**Comment by RileyMShea** [comment]
I do not. I should have probably prefaced this was just a stab in the dark.  I'll amend the previous comment to prevent confusion.  My apologies.

**Comment by hasezoey** [comment]
closing because in 6.4.1 `decompress` got replaced
