### ISSUE TITLE
Issue with monorepo + yarn workspaces

### ISSUE THREAD

**Issue by jole78** [nodkz/mongodb-memory-server#200]
Hi,

I have a monorepo setup with yarn workspaces where 1 of my packages (currently) depends on MMS.

I'm seeing 2 things:
1. I have to add the config to the root package.json in order for MMS to download the correct version (if I don't want latest). Binaries added to root node_modules/.cache
2. When I run the tests (located in 1 of the workspace packages) it again tries to download the binaries but this time into /packages/some-package/node_modules/.cache

Also, I have to specify version in both package.json (for reasons I can't really use ENV variables).

I managed to work around the issue by specifying no-hoist to MMS in the subpackage but it seems that MMS looks for configs/binaries in the "wrong" place. Or??

**Comment by nodkz** [comment]
In such case better to use global package https://github.com/nodkz/mongodb-memory-server#with-auto-download-latest-mongod-binary-on-npm-install-to-homecache

**Comment by jole78** [comment]
That's an option of course...I'll look into it. Thanks!
