### ISSUE TITLE
error when work with jest

### ISSUE THREAD

**Issue by mortezadalil** [nodkz/mongodb-memory-server#201]
I use jest sample but this error is appeared :
![image](https://user-images.githubusercontent.com/15077932/60599128-223b3580-9dc3-11e9-94ef-f663905e2eea.png)

**Comment by PizzaPartyInc** [comment]
Hey!

Here is the fix that helped me:
![image](https://user-images.githubusercontent.com/37663061/61534886-725bfe00-aa39-11e9-9ebb-96fc6516f93c.png)

I think it would be great to modify the example as well, so that others would not stumble upon this error :)

**Comment by shilangyu** [comment]
@PizzaPartyInc 's suggestion fixed it for me, i see its in the readme already, this can be closed(?)
