### ISSUE TITLE
slaveDelay option for MongoDB replicaSet

### ISSUE THREAD

**Issue by thesayyn** [nodkz/mongodb-memory-server#209]
Currently, slaveDelay option is not supported in replica Set initialization.

https://docs.mongodb.com/manual/tutorial/configure-a-delayed-replica-set-member/

**Comment by hasezoey** [comment]
is this an cli option or an mongod-shell only with `rs.reconfig()`?

if its an cli option, it can be easily added
if its an mongod-shell only option, it cannot be easily added (at least *yet*) because this is not used in this project yet

**Comment by hasezoey** [comment]
these options are currently implicitly supported by the config options for MongoMemoryReplSet, `replSet.args` / `instanceOpts.$.args`
