### ISSUE TITLE
download url for 4.2.0 changed from *2008* to *2012*

### ISSUE THREAD

**Issue by maxfriedmann** [nodkz/mongodb-memory-server#217]
If I set the version to 4.2.0 I get a 404 since the URL is incorrect. This package resolves to 

`https://fastdl.mongodb.org/win32/mongodb-win32-x86_64-2008plus-ssl-4.2.0.zip`

but it should be 

`https://fastdl.mongodb.org/win32/mongodb-win32-x86_64-2012plus-4.2.0.zip`

Can you change that?

**Comment by nodkz** [comment]
Currently i'm at vacation. But i can accept pull request from mobile and publish a new version. Please take a look at last commits, it quite easy to make required changes.

Thanks.

**Comment by maxfriedmann** [comment]
I decided not to add the exception for greater versions than 4.2.x since nobody knows how the URL will change again. Please have a look @nodkz at my PR!

**Comment by nodkz** [comment]
@maxfriedmann can you please fix lint problem
https://circleci.com/gh/nodkz/mongodb-memory-server/169?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

I can do it myself only at evening (
But if you gix i can publish a new version from mobile phone ;)

**Comment by nodkz** [comment]
Fixed and published as 5.2.2 version

**Comment by maxfriedmann** [comment]
Thanks a lot!
