### ISSUE TITLE
Mocha worker process does not shut down straight away

### ISSUE THREAD

**Issue by Anupheaus** [nodkz/mongodb-memory-server#234]
I am using this package with my mocha and chai tests.  It works perfectly but just has this very annoying issue of holding the mocha worker open for approx 49-50 seconds after the tests are all finished.  This adds 49-50 seconds of wasted time to my ci process.

Here is a screenshot of the end of my tests:
![image](https://user-images.githubusercontent.com/2872785/67090162-4e779800-f1a1-11e9-9cb1-00c4c6832379.png)
As you can see, my tests take 522ms, and this is what it shows almost immediately after I run the tests, but it just stays like this (with the results already showing) for another 50 seconds or so.  I can confirm that it is this package because if I take out the tests using this package, it doesn't pause at the end of running the tests.

I started trying to determine what part of using the server causes this and it seems that if I start the server and make no changes, then stop the server, no pause.  But if I start the server, create a collection and stop the server...50 second pause...

Any ideas please?

**Comment by hasezoey** [comment]
do you close all connections before stopping the instance? when not, this happened to me (double connect), it holds the connection indefinitely

could you give more information on your setup? like if you use mongoose, and some sample code

**Comment by hasezoey** [comment]
closing because stale for over 3 months
