### ISSUE TITLE
[Windows] Incorrect `mongod` binary path

### ISSUE THREAD

**Issue by cmosgh** [nodkz/mongodb-memory-server#24]
Freshly installed on a new machine
Windows10 x64
```
Autostarting MongoDB instance...
  Mongo[50146] Starting MongoDB instance with following options: {"port":50146,"dbName":"f63e96d0-2244-497d-a043-f608688a503d","uri":"mongodb://localhost:50146/f63e96d0-2244-497d-a043-f608688a503d","storageEngine":"ephemeralForTest","dbPath":"C:\\Users\\Username\\AppData\\Local\\Temp\\mongo-mem-6080BA3QCuF1h8UT"} +0ms
Downloading MongoDB: https://downloads.mongodb.org/win32/mongodb-win32-x86_64-3.4.4.zip
  Mongo[50146] renamed C:\Users\Username\.mongodb-binaries\mongodb-win32-x86_64-3.4.4.zip.downloading to C:\Users\Username\.mongodb-binaries\mongodb-win32-x86_64-3.4.4.zip +10s
  Mongo[50146] getDownloadMD5Hash content: 024a46524c856429d0fd9de0c7d04c5f  mongodb-win32-x86_64-3.4.4.zip
  Mongo[50146]  +557ms
  Mongo[50146] getDownloadMD5Hash extracted signature: 024a46524c856429d0fd9de0c7d04c5f +1ms
  Mongo[50146] extract(): C:\Users\Username\.mongodb-binaries\3.4.4 +581ms
(node:6080) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: MongoBinaryDownload: missing mongod binary in C:\Users\Username\.mongodb-binaries\mongodb-win32-x86_64-3.4.4.zip
(node:6080) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: MongoBinaryDownload: missing mongod binary in C:\Users\Username\.mongodb-binaries\mongodb-win32-x86_64-3.4.4.zip
```

**Comment by nodkz** [comment]
@cmosgh thanks for debugging. 👌

Can you provide you folder structure by path `C:\Users\Username\.mongodb-binaries\3.4.4`

Or maybe you can make PR, which will find `mongod.exe` in these lines:
https://github.com/nodkz/mongodb-memory-server/blob/master/src/util/MongoBinaryDownload.js#L131-L133
and
https://github.com/nodkz/mongodb-memory-server/blob/master/src/util/MongoBinaryDownload.js#L71

Moreover, will be cool if you create an internal method for obtaining correct binary path according to OS something like:
```js
class MongoBinaryDownload {
  ...
  _getMongodPath(): string {
    if (this.platform === 'win32') {
      return __correct path___
    } else {
      return path.resolve(this.downloadDir, this.version, 'mongod');
    }
  }
}
```

**Comment by nodkz** [comment]
I'm on MacOS and make a proper fix for Win quite hard for me.
Thanks for help!

**Comment by cmosgh** [comment]
MongoBinaryDownload  looks for C:\Users\Moshu\.mongodb-binaries\3.4.4\mongod

but the .mongodb-binaries contains only the zip archive and an empty folder folder 3.4.4.

**Comment by nodkz** [comment]
So it look like that filter in `decompress` contain incorrect filter under `win32`
https://github.com/nodkz/mongodb-memory-server/blob/master/src/util/MongoBinaryDownload.js#L123

**Comment by cmosgh** [comment]
I can give you the path it receives sec

**Comment by cmosgh** [comment]
ah its pretty simple I think. since macos doesn't need `.exe`
filter should have added `.exe` and the path resolve should have the same appended

**Comment by nodkz** [comment]
Yep needs to check `this.platform === 'win32'` and if is true then use path and filter for windows, otherwise keep existed values for linux and mac.

Would you try to do PR?

**Comment by cmosgh** [comment]
would be my first. I should try tho :)

**Comment by cmosgh** [comment]
created a pull request but it fails to build on prettier... haven't configure it locally, maybe you can tho use the code?

**Comment by nodkz** [comment]
Congrat with first PR 🎉

**Comment by nodkz** [comment]
Published https://github.com/nodkz/mongodb-memory-server/releases/tag/v1.6.1

**Comment by ozanmuyes** [comment]
For what is worth set the `binary.systemBinary` option (as listed at [here](https://github.com/nodkz/mongodb-memory-server#available-options)) to point to the correct path on the filesystem (where npm postinstall actually downloads the binary). For me this `systemBinary` is "X:\\Project\\Root\\node_modules\\mongodb-memory-server\\node_modules\\.cache\\mongodb-memory-server\\mongodb-binaries\\x.y.z\\mongod.exe" (note the double slash on Windows). Hope this helps, because even version 3.0.0 of this package wasn't working for me.
