### ISSUE TITLE
Jest takes +30 secs for simple unit tests

### ISSUE THREAD

**Issue by MarceloPrado** [nodkz/mongodb-memory-server#244]
I've been using MongoDB Memory Server in two of my company projects now and I'm getting a weird behavior: after a couple of fast runs (6 unit tests running in 2-3 secs), Jest starts taking forever to run (30-50 secs for the same amount of tests).

This is happening to both projects. 
We followed the docs to set up the servers and mongoose connection.

For a reference, we've been running the tests with:
- mongodb-memory-server `5.2.5`
- mongoose `5.7.11`
- typescript `3.7.2`
- ts-jest `24.1.0`

Any idea what could be happening? I might be able to build an example repo if that helps!

Thanks!

**Comment by vkyrychenko** [comment]
We have a similar issue on CodeShip.
With the default jest settings, our tests just stuck at some point with error: `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`.

There is a workaround described [here](https://blog.bam.tech/developer-news/optimise-jest-in-ci-and-save-hours-a-week-literally-1).

It doesn't fix an issue, but at least tests are not crashing: `jest --maxWorkers=3 --coverage --verbose`.

We're using those configs:
```
new MongoMemoryReplSet({
      debug: false,
      replSet: {
        name: 'test_rs0',
        count: 2,
        storageEngine: 'wiredTiger',
      },
})
```

- mongodb-memory-server: `6.0.1`

Hope this will help someone :)

**Comment by MarceloPrado** [comment]
Somehow this problem seems fixed. I'm not sure what exactly happened, I guess it's something related to a high CPU usage on my Mac which seems to slow down its performance.

I'm closing this issue for now.
