### ISSUE TITLE
commands never seem to run

### ISSUE THREAD

**Issue by devayush** [nodkz/mongodb-memory-server#245]
I'm not able to query on the mongodb in memory database using for test cases using jest  Create seems to work absolutely fine but any functions retrieving the data are not.
It could be possibly an error with data being created, please help out on the same 

Same issue i have opened on - [stackoverflow](https://stackoverflow.com/questions/58950443/not-able-to-fire-find-or-get-methods-over-mongodb-in-memory-database)

```ts
describe('#create', () => {
  it('should create a user without throwing an error', () => {
    userModuleObj.create(userData, (err, res) => { // this calls the mongoose create function
      expect(err).toBe(null);
    })
  })
})
```
The above code seems to work

```ts
describe('#retrieve', () => {
  it('should find a user without throwing an error', () => {
    userModuleObj.retrieve({}, (err, res) => { // calling the find function of mongodb
      expect(err).toBe(null);
    })
  })
})
```

**Comment by nodkz** [comment]
Try `const mongod = new MongoMemoryServer({ instance: { storageEngine: 'wiredTiger' }});`. It will speen up mongod on wiredTiger engine, it slower but it better than non-working tests.

Frankly, in my test I use bunch of different read/write commands and they work perfectly https://github.com/graphql-compose/graphql-compose-mongoose/tree/master/src/resolvers/__tests__

**Comment by hasezoey** [comment]
@devayush did you already try the async-await approach? (and could you provide and example of how you connect?)
anyway, can you provide debug output? `new MongoMemoryServer({ debug: true })`
(otherwise close this issue if you dont use it anymore)

**Comment by hasezoey** [comment]
closing because stale for over 3 months
