### ISSUE TITLE
[Arch Linux] Binary not downloaded when no release file is found

### ISSUE THREAD

**Issue by tuarrep** [nodkz/mongodb-memory-server#248]
I've tried to deploy on a server without a `/etc/release` (or equivalent) file and the package fails when trying to download mongod binary. The underlying package report an error and `mongodb-memory-server` stops.

On my local machine I'm using Arch and I have this message `Unknown linux distro Arch Linux, falling back to legacy MongoDB build` and everthing goes well.

Why don't trying to download legacy MongoDB package when getos reports an error ?

**Comment by hasezoey** [comment]
> Why don't trying to download legacy MongoDB package when getos reports an error ?

it is falling back, but currently arch-linux is not supported (and getos got replaced, but still requires either `lsb_release` or an `-release` file, how should it get the infomation needed otherwise (universally)?

**Comment by hasezoey** [comment]
Current status:
ArchLinux does have an /etc/os-release file
ArchLinux(Docker) does **not** have an /etc/os-release file
MongoDB does **not** have a build for ArchLinux (https://www.mongodb.org/dl/linux/)

(Ref: https://github.com/hasezoey/mongodb-memory-server/commit/81e0a128bb730a004433ec53efa02a9f2700582b)

**Comment by tuarrep** [comment]
Sorry for my late reply.
I think my problem was misunderstood. 

On Arch Linux everything goes well even with the legacy binary. 

The problem is on my production server (on which I haven't root permissions) which runs a custom version of Linux. On this server the error `No release file found` is reported by `getos` util.

My question was: if `getos` tries to find a release file and fails, we can make the assumption that we runs on Linux. So why to not download the legacy binary like on Arch in this case?

**Comment by hasezoey** [comment]
> My question was: if getos tries to find a release file and fails, we can make the assumption that we runs on Linux. So why to not download the legacy binary like on Arch in this case?

getos got an internal re-write as of 6.1, which either requires `lsb_release`, `/etc/os-release` or `/etc/*-release` (first file taken), or you just specify which version of mongodb you want, otherwise it will fall-back to a legacy build (which is in most cases not what you want)

PS: in #259 a case for arch & alpine are added, which will show an warning that there is no official mongodb file, and will fall back to a legacy build

**Comment by tuarrep** [comment]
Thank you for your answer.
So, since 6.1 this issue can be closed

**Comment by hasezoey** [comment]
just as a note:

> So, since 6.1 this issue can be closed

if you mean `or you just specify which version of mongodb you want, otherwise it will fall-back to a legacy build (which is in most cases not what you want)`, that was already before, in 6.1 getos got rewritten (because it didnt see any update for long, and had other problems)
