### ISSUE TITLE
Cannot install mongodb-memory-server

### ISSUE THREAD

**Issue by moun3iim** [nodkz/mongodb-memory-server#249]
I have got a problem in installing `mongodb-memory-server`, I tried to install it using yarn and it stays like this forever
![Screenshot from 2019-12-10 15-58-32](https://user-images.githubusercontent.com/44704549/70541230-ef158300-1b66-11ea-8bf3-81d8f0acbf07.png)

and the same problem using npm

![Screenshot from 2019-12-10 16-07-37](https://user-images.githubusercontent.com/44704549/70541384-34d24b80-1b67-11ea-8c51-6e3639ca6fc7.png)

**Comment by moun3iim** [comment]
solved using `--diable-scripts` flag

**Comment by moun3iim** [comment]
solved using `--ignore-scripts` flag

**Comment by hasezoey** [comment]
@moun3iim why got this reopened, cloud you give more information on that?

like:
versions: nodejs, mongodb-memory-server, yarn

**Comment by moun3iim** [comment]
```
npm : v6.13.4
yarn : v1.19.1
node : v13.3.0
```

I reopened the issue because I still get the error, I tried to run npm with `sudo` and it installed correctly but tests didn't work unless you gave npm root permissions

```
Error: EACCES: permission denied, open '/home/abdelmounaim/WebstormProjects/side-project/api/node_modules/.cache/mongodb-memory-server/mongodb-binaries/4.0.3.lock'

Use debug option for more info: new MongoMemoryServer({ debug: true })
    at /home/abdelmounaim/WebstormProjects/side-project/api/node_modules/mongodb-memory-server-core/lib/MongoMemoryServer.js:96:31
    at async module.exports (/home/abdelmounaim/WebstormProjects/side-project/api/node_modules/@shelf/jest-mongodb/setup.js:12:5)
```
if you try to install the package without `sudo` the error remains as above

**Comment by hasezoey** [comment]
> if you try to install the package without sudo the error remains as above

sudo or non-sudo shouldnt affect what the max-stack is

---

could you give your system infomation too? (windows, linux distro)

**Comment by moun3iim** [comment]
> > if you try to install the package without sudo the error remains as above
> 
> sudo or non-sudo shouldnt affect what the max-stack is
> 
> could you give your system infomation too? (windows, linux distro)

Linux(Ubuntu)

**Comment by hasezoey** [comment]
> Linux(Ubuntu)

and version?

**Comment by moun3iim** [comment]
19.04

**Comment by hasezoey** [comment]
did you already try deleting whole `node_modules` (/`node_modules/.cache`) and `~/.cache/mongodb-binaries`? (`rm -rf`

**Comment by nahid597** [comment]
First, you delete your node_modules folder then try to re-install it. Hope it will work.
