### ISSUE TITLE
When mock-fs installed, mongodb-memory-server does not work

### ISSUE THREAD

**Issue by dotundefined** [nodkz/mongodb-memory-server#251]
**BUG!**

I am not sure on which side is it, on  _mongodb-memory-server_, or the _mock-fs_, so I will be posting same issue on both sides.

I was using _mongodb-memory-server_ for most of my service testing. After a while, I needed to mock some files in order to test some file related functions. Then, as soon as I install _mock-fs_, don't even have to import _mock-fs_, all of the tests that use _mongodb-memory-server_ are not even ran. All of the crash right at the beginning.
When I remove _mock-fs_, _mongodb-memory-server_ runs fine.

I don't know if they are using same part of memory, since they are both in-memory modules, or what but they don't seem to work together.

Error log from mocha on the test that uses _mongodb-memory-server_, which is probably not much of help:
`Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/path/to/the/test/test.spec.js)`

This is where it happens:
```javascript
before(async () => {
    await dbHandler.connect(); // This one connects to mongodb-memory-server
  });
```

And also this shows up in the console while the tests are stuck on the code above:
`Downloading MongoDB 4.0.3: 0 % (0mb / 79.4mb)`

Versions:
`node: 10.15.2`,
`mocha: 6.2.2`,
`mock-fs: 4.10.4`,
`mongodb-memory-server: 6.0.2`

**Comment by nodkz** [comment]
Yep, mongodb-memory-server under the hood uses `fs` module to check binary presence.

According to doc of `mock-fs` you need to use `mock.restore()` when you use jest snapshot testing https://github.com/tschaub/mock-fs#using-with-jest-snapshot-testing

So you need to init `mock-fs` after mongod initialization. If you find proper working solution, please open PR with a workaround example to README.md.

Tnx.

**Comment by J-Mustafic** [comment]
So, I have missed this line in the docs: 
`Start Mocha with --timeout 60000 cause first download of MongoDB binaries may take a time.`

But when I first ran the tests without `mock-fs`, there was no issue. I did not even get the log that the MongoDB is downloading.

When I installed `mock-fs`, and in mocha prepare I've set up some file mocking, in `beforeEach` hook(where I was connecting to database) I was getting: `Downloading MongoDB 4.0.3: 0 % (0mb / 79.4mb)`, but the test were skipping this download and kept crashing the tests.

I have fixed it by moving the database connection init into mocha prepare, to run before all tests. In that case, Downloading did occur and got finished, and from that point I had no Issue.

I will post original code that kept breaking here, so you can try and recreate the issue.

**Comment by hasezoey** [comment]
> But when I first ran the tests without mock-fs, there was no issue. I did not even get the log that the MongoDB is downloading.

(if you use one of the non `-core` packages:) it was probably because of the postinstall script that would download the binary

**Comment by hasezoey** [comment]
closing because stale for over 3 months
