### ISSUE TITLE
Can not listen open event when connected to the memory server

### ISSUE THREAD

**Issue by hacker0limbo** [nodkz/mongodb-memory-server#257]
Hello:

When i followed the doc and try to connect to the server, everything seems to be fine, i am able to connect to the memory server using mongoose and do some operations. However there is still one little issue that i am confused:

I tried to listen the `open` event when first time connected to server, although it connected but it seems not printing out any information i set in the `console.log`, here is part of the my program:

```typescript
export default class DBHandler {

  static async connectDB() {
    const uri = await mongod.getUri()
    const options = {
      useNewUrlParser: true,
      useFindAndModify: false,
      useCreateIndex: true,
      useUnifiedTopology: true,
    }
    
    await mongoose.connect(uri, options)
    
    const db = mongoose.connection
    db.on('error', () => {
      console.log('Error when connecting to db')
    })
    db.once('open', () => {
      console.log('Connected to the db memory') // not printing this message even connected?
    })
  }

  static async closeDB() {
    await mongoose.connection.dropDatabase()
    await mongoose.connection.close()
    await mongod.stop()
  }
}

// usage
beforeAll(async () => {
  await DBHandler.connectDB()
})

afterAll(async () => {
  await DBHandler.closeDB()
})
``` 

I am using this lib for Jest testing, and for the test result there isn't showing any message like `Connected to the db memory`. However the whole program works and Jest works fine as well. Here is the image showing the jest result:

![Screen Shot 2019-12-27 at 9 28 22 pm](https://user-images.githubusercontent.com/36297538/71518861-dbe90e00-28ef-11ea-8eca-994fa3073466.png)

Not sure if i listened the right event? Or did i do something wrong? I am really new to this lib and My english is not very well. Hope i explain my confusion clearly, Cheers!

**Comment by hasezoey** [comment]
its probably because of `await mongoose.connect` it **waits** until it is connected, and **then** sets up an `open` event handler (the event is triggered **before** the handler is set-up)

**Comment by hacker0limbo** [comment]
Sweet! This solves my problem, thanks a lot for your explanation. Will close this issue then.
