### ISSUE TITLE
[Windows] Module tries to remove temp dir before mongod exits

### ISSUE THREAD

**Issue by gvuyk** [nodkz/mongodb-memory-server#26]
This causes
```
Error: EBUSY: resource busy or locked, unlink 'C:\Users\Gerard\AppData\Local\Temp\mongo-mem-13616GqtHuLWrpEBT\mongod.lock'
```
Solution would be to wait for the childProcess `exit` event before calling  `tmpDir.removeCallback()`

Happy to provide a PR

**Comment by nodkz** [comment]
Sure!

I didn't catch such problem on Mac. So please fix it.
PS. Feel free to send PR with eslint, flowtype errors ;)
