### ISSUE TITLE
How to connect mongodb-memory-server by Robo 3T?

### ISSUE THREAD

**Issue by jdang67** [nodkz/mongodb-memory-server#260]
Hi Everyone,

I just try to use Robo 3T to connect to the new instance of  MongoDB-memory-server though
the connection  string  
``` javascript 
var url= await mongoServer.getConnectionString() 
```  
and I got the following error:

``` 
Cannot connect to replica set "New Connection"[127.0.0.1:49447]. 
Set's primary is unreachable.

Reason:
SSL tunnel failure: Network is unreachable or SSL connection rejected by server. Reason: It is not possible to continue with empty set name

```
I am not sure how to overcome this problem?

thanks,

Jdang

**Comment by hasezoey** [comment]
I have never used replica sets (not even in this package), but i would recommend checking the tests for it:

- https://github.com/nodkz/mongodb-memory-server/blob/master/packages/mongodb-memory-server-core/src/__tests__/replset-test.ts
- https://github.com/nodkz/mongodb-memory-server/blob/master/packages/mongodb-memory-server-core/src/__tests__/replset-single-test.ts

**Comment by jdang67** [comment]
Hasezoey,

I'm using the latest version (6.2.0) and my OS is windows 10.

thanks,
Jdang

**Comment by hasezoey** [comment]
looking at this again, it looks like your client (`Robo 3T`) tried to connect to the server with SSL, but the server didnt have SSL enabled and so rejected the connection
