### ISSUE TITLE
Replace custom debug functions with logging module

### ISSUE THREAD

**Issue by hasezoey** [nodkz/mongodb-memory-server#262]
*from #214*

i would suggest to replace all `this.debug` calls with some logging module, like `debug` or `loglevel`

---

Pros for loglevel:
- has many levels that are easy to access `logger.<level>`

Cons for loglevel:
- cant be activated via environment (needs to be activated with `setLogLevel`)
- cant be activated for one specific file

---

Pros for debug:
- can be activated via environment
- can be activated for only one file / can be filtered for one file

Cons for debug:
- needs to set a "new logger" in every file
- dosnt have any levels

**Comment by nodkz** [comment]
I vote for DEBUG. In this package... there is no need for log levels like it required in regular apps.

Anyway, current `console.log` solves debug issues and the current feature is optional. Nice to have, but not obligatory.

**Comment by hasezoey** [comment]
> Anyway, current console.log solves debug issues and the current feature is optional. Nice to have, but not obligatory.

yes  it does, but i think the `this.debug` for every class this package has (which are many) is just a bit much...

**Comment by hasezoey** [comment]
just noticed that `debug` is already listed as an dependency, but never used (at least i couldnt find any import)
