### ISSUE TITLE
Does it support Mongodb multi document transaction?

### ISSUE THREAD

**Issue by onkarjanwa** [nodkz/mongodb-memory-server#267]
Getting below error message:
**MongoError: Transaction numbers are only allowed on a replica set member or mongos**

## Versions

- NodeJS: v10.13.0
- mongodb-memory-server-*: 6.2.4
- mongodb: 3.5.2
- mongoose: 5.8.11
- system: MacOS

package: mongo-memory-server 
## What is your question?

Does it support Mongodb multi document transaction?

**Comment by nodkz** [comment]
Yep, supports!

Read docs about [How to start ReplicaSet](https://github.com/nodkz/mongodb-memory-server#replica-set-start)

**Comment by onkarjanwa** [comment]
@nodkz Any suggestions how to solve the error "**MongoError: Transaction numbers are only allowed on a replica set member or mongos**".

**Comment by hasezoey** [comment]
@onkarjanwa 
>  "MongoError: Transaction numbers are only allowed on a replica set member or mongos"

means that it is only allowed on an replica set or an `mongos` instance, so you need to spin up multiple instances
@nodkz already provided an link to [the documentation](https://github.com/nodkz/mongodb-memory-server#replica-set-start) on how to start an replica set with `mongo-memory-server`

**Comment by onkarjanwa** [comment]
@hasezoey @nodkz Multi document transactions are working on local machine without any replica set. But when using `mongo-memory-server` for test environment it is throwing error. 

I could not get it working even after using `MongoMemoryReplicaSet`, every time it throws a new error.

**Comment by hasezoey** [comment]
@onkarjanwa do you use by any chance an non 4.0+ version of mongodb (default being 3.2)? when yes, please set the version to 4.0+ in order to use document transactions

**Comment by onkarjanwa** [comment]
@hasezoey 

I am using binary version `4.2.3` while creating `MongoMemoryServer`.

**Comment by hasezoey** [comment]
@onkarjanwa just to confirm, is this the actual version printed in the log, or just the set version? (if unsure, delete the binary and let it re-download)
otherwise i dont know, because i dont know much about document transactions

**Comment by onkarjanwa** [comment]
@hasezoey I have set the version to `4.2.3` and it downloads new binary and installs it.

**Comment by hasezoey** [comment]
@onkarjanwa sorry, then i dont have any more advice / questions, i never worked with replica sets and document transactions

**Comment by onkarjanwa** [comment]
@hasezoey ok, thanks :)

**Comment by hieuxlu** [comment]
> @onkarjanwa sorry, then i dont have any more advice / questions, i never worked with replica sets and document transactions

To support multi-document transaction, we just need to set `storageEngine: 'wiredTiger'`
```
    const mongoServer = new MongoMemoryReplSet({
      replSet: { count: 1, storageEngine: 'wiredTiger' },
    })
```
Found the fix via [this SO question](https://stackoverflow.com/questions/57801290/transaction-numbers-are-only-allowed-on-storage-engines-that-support-document-le)

**Comment by calebmgshort** [comment]
It took me a long time to hunt down the 'wiredTiger' solution. Could it be included as part of the readme on setting up a replica set? I think that could help a lot of people who are using transactions

**Comment by hasezoey** [comment]
@calebmgshort added with added with fc5cc47e9aeb9095219c3dbc58a3ee3e8af7f74e
