### ISSUE TITLE
Broken download link for mongo 3.0.15

### ISSUE THREAD

**Issue by khasburrahman** [nodkz/mongodb-memory-server#268]
## Versions

- NodeJS: 10.19.0
- mongodb-memory-server:  6.2.4
- mongodb: 3.0.15
- system: debian linux (docker node:10.19.0) 

package: mongo-memory-server 

## What is the Problem?
The link seems invalid, I got 
```error
Error: MongoBinaryDownload: missing mongod binary in /usr/app/node_modules/.cache/mongodb-memory-server/mongodb-binaries/mongodb-linux-x86_64-debian92-3.0.15.tgz (downloaded from https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian92-3.0.15.tgz). Broken archive from MongoDB Provider?
```

## Code Example

```ts
//package json config
{
"config": {
    "mongodbMemoryServer": {
      "version": "3.0.15",
      "debug": "1"
    }
  }
}
```

## Do you know *why* it happenes?
Perhaps the link is invalid? I got access denied when try to access the link using curl
```
curl https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian92-3.0.15.tgz

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>E0282DEE7F30B410</RequestId><HostId>0FiEcznJiUW5sMZOtE5RA+4l3i5bKkzDgjKtNwMm8PDtogpDpJceVg8q4otI24TeDbGB317zTpI=</HostId></Error>
```

**Comment by hasezoey** [comment]
please know that it is an generated link, the requested version might not be an actual version that is why you see this error

PS: after an quick look at [the archive](https://www.mongodb.org/dl/linux) there is no `debian92-3.0*` the earliest for debian92 i find is `3.6.5`

**Comment by khasburrahman** [comment]
I see, 
So after looking another binaries in `https://www.mongodb.org/dl/linux/x86_64`

I found it working correctly using this one 
```
http://downloads.mongodb.org/linux/mongodb-linux-x86_64-3.0.15.tgz
```
So I can set the env so that mongo memory server download that binary
```
MONGOMS_DOWNLOAD_URL=http://downloads.mongodb.org/linux/mongodb-linux-x86_64-3.0.15.tgz
```
Thank you! 👍

**Comment by jhonnymoreira** [comment]
Had the same problem as @khasburrahman in Docker while trying to support the most MongoDB most recent version provided by mLabs at the the time (3.6.17), solution was the same as provided, but using the `config` in `package.json`:

```json
{
  "config": {
    "mongodbMemoryServer": {
      "downloadUrl": "https://downloads.mongodb.org/linux/mongodb-linux-x86_64-3.6.17.tgz",
      "md5Check": "1",
      "postinstall": "1",
      "version": "3.6.17"
    }
  }
}
```
