### ISSUE TITLE
Linux download for Ubuntu 18.04 fails in version ^6.2.4

### ISSUE THREAD

**Issue by rahil051** [nodkz/mongodb-memory-server#269]
#100 already solves the issue by updating the package to 2.7.0 as per the comment https://github.com/nodkz/mongodb-memory-server/issues/100#issuecomment-435927293

But the issue reappears with version 6.2.4

## Versions

- NodeJS: 12.14.1 LTS
- mongodb-memory-server-*: 6.2.4
- mongodb: 3.6
- mongoose: 5.8.11
- system: Linux Mint 19.3 Tricia

package: mongo-memory-server/mongo-memory-server-core

## What is the Problem?

```bash
     Error: MongoBinaryDownload: missing mongod binary in $HOME/$PROJECT_FOLDER/node_modules/.cache/mongodb-memory-server/mongodb-binaries/mongodb-linux-x86_64-ubuntu1804-3.6.5.tgz (downloaded from https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1804-3.6.5.tgz). Broken archive from MongoDB Provider?
```
Accessing the downloadable link responses back with an AccessDenied

### My resolution
Reverting the version back to 1604 solves it for me, but no point creating a separate PR for it, hoping the 1804 link gets alive sooner.

**Comment by hasezoey** [comment]
from what i see, there is no version below 4.0 for ubuntu 18.04, so you need to either use the local version with an set version, or the global one with a set version, or `mongodb-memory-server-global-4.0`

**Comment by hasezoey** [comment]
found the issue, did you specify an custom version, when yes, what did you set?

PS: debug log would always be appreciated

**Comment by rahil051** [comment]
> found the issue, did you specify an custom version, when yes, what did you set?
> 
> PS: debug log would always be appreciated

No, I didn't specify any custom version, instead the MongoBinaryDownloadUrl.js picks up my Ubuntu release as 18.04 and requests the mongodb binary for 18.04 specifically.

### Debug Log

```bash
(node:25026) UnhandledPromiseRejectionWarning: Error: MongoBinaryDownload: missing mongod binary in $HOME/$PROJECT_FOLDER/node_modules/.cache/mongodb-memory-server/mongodb-binaries/mongodb-linux-x86_64-ubuntu1804-3.6.5.tgz (downloaded from https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1804-3.6.5.tgz). Broken archive from MongoDB Provider?
    at MongoBinaryDownload.<anonymous> ($HOME/$PROJECT_FOLDER/node_modules/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts:215:13)
    at step ($HOME/$PROJECT_FOLDER/node_modules/mongodb-memory-server-core/lib/util/MongoBinaryDownload.js:33:23)
    at Object.next ($HOME/$PROJECT_FOLDER/node_modules/mongodb-memory-server-core/lib/util/MongoBinaryDownload.js:14:53)
    at fulfilled ($HOME/$PROJECT_FOLDER/node_modules/mongodb-memory-server-core/lib/util/MongoBinaryDownload.js:5:58)
(node:25026) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25026) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Basically I am running tests for mongo, which spins up mongod server to load fixtures to query on them.

**Comment by hasezoey** [comment]
@rahil051 sorry, this is the error log, not the complete debug log, you can enable it with `MONGOMS_DEBUG=1` as an environment variable (easiest way)

**Comment by hasezoey** [comment]
wait, from what i see `MONGOMS_DEBUG` has no effect (i dont know why, needs rewrite anyway), please use 
```ts
const instance = new MongoMemoryServer({ debug: true });
```

**Comment by hasezoey** [comment]
> wait, from what i see MONGOMS_DEBUG has no effect (i dont know why, needs rewrite anyway), please use

since #270 is merged, debug log should be more useful

**Comment by hasezoey** [comment]
closing because stale for over 3 months
