### ISSUE TITLE
[Lint] Always surround oneline-if's with "{}" or always oneline-if's without

### ISSUE THREAD

**Issue by hasezoey** [nodkz/mongodb-memory-server#275]
@nodkz i ask because this project is currently very mixed in this case and we should standardize it with [an eslint rule](https://eslint.org/docs/rules/curly) to make it always surrounded or let it removed

**Comment by nodkz** [comment]
In our internal projects we surround oneline if with {}. Because with time any one-line-if may become multiline.

**Comment by hasezoey** [comment]
@nodkz so what do you think would fit for this project, force surround?

**Comment by nodkz** [comment]
I don't force our internal teams for this rule. And accept any form of code style. 

So if you want we can add such eslint rule for this repo. And if we'll meet with some inconveniences in the future then we just turn this rule off.

**Comment by hasezoey** [comment]
i will probably make an pr with the rule in place an applied, after #274 is merged
