### ISSUE TITLE
restarting replset with already existing files fails with "already initialized"

### ISSUE THREAD

**Issue by sakulstra** [nodkz/mongodb-memory-server#278]
Disclaimer: I know that not the intention of this library at first place and I probably shouldn't abuse it this way.

## Versions

- NodeJS: 12.x
- mongodb-memory-server-*: 6.3.1
- mongodb: default that comes for arch
- system: arch

package: mongo-memory-server

## What is your question?

The issue i'm trying to solve is that within out company there are people accross all OSes which want to play around with our not yet released api which relies on a mongodb running on the system.

For our stuff to work we need a somehwat up-to-date version of mongodb with a replicaset, so we created a simple script which uses `'mongodb-memory-server` to start a mongodb without the setup hassle and it works great :+1:

One problem though is that in some cases we'd like to persist the test data trough system reboots and stuff like that :sweat_smile: 

So I was wondering if there is a way to start mongodb with previously persisted data similar to `mongod --dbpath database --replSet rs`? I saw there's a:
```
instanceOpts: [
    {
      port: 27017,
      dbPath: "database",
    },
  ],
```
option to specify the path, but when reusing a path from a previous run I get the following error
```
(node:29641) UnhandledPromiseRejectionWarning: MongoError: already initialized
    at MessageStream.messageHandler (/home/lukass/Documents/sputnik/node_modules/mongodb/lib/cmap/connection.js:261:20)
    at MessageStream.emit (events.js:311:20)
    at processIncomingData (/home/lukass/Documents/sputnik/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/home/lukass/Documents/sputnik/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at doWrite (_stream_writable.js:441:12)
    at writeOrBuffer (_stream_writable.js:425:5)
    at MessageStream.Writable.write (_stream_writable.js:316:11)
    at Socket.ondata (_stream_readable.js:714:22)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
```

**Comment by hasezoey** [comment]
dbPath should be an absolute path to avoid conflictions

if you give an dbPath, it will be used across all instances, this is why when more than one are started, it tries to use the same path, what is already locked by another instance

Sorry, but currently the only way to use replset with more than one instance, is to not specify an dbPath to automatically create temporary directories (in `/tmp`)

**Comment by sakulstra** [comment]
@hasezoey i'm not sure if we're talking about the same thing.

I don't want to start multiple instances with the same dbPath, but instead "pick-up where i left off the other day" with another instance.

**Comment by hasezoey** [comment]
@sakulstra i know, but you specified an `dbPath` and want to spin up multiple instances as an replset, right? when yes, you cant do this in the same directory

**Comment by boredland** [comment]
no this isn't about multiple instances. he only has one instance (declared by one item in the `instanceOpts` array. this instance has a path, which seems to be correct.

Imo the problem is here: 
https://github.com/nodkz/mongodb-memory-server/blob/master/packages/mongodb-memory-server-core/src/MongoMemoryReplSet.ts#L262

whenever you run a MongoMemoryReplSet, it calls ReplSetInitiate via the Mongo Admin:
https://docs.mongodb.com/manual/reference/command/replSetInitiate/

when you restart your instance, this initiate is called again ans fails with the error mentioned above. To get around this, I'd propose to add a per-instanceopts property to start the instance without initialization.

**Comment by hasezoey** [comment]
@boredland thanks, sorry that i didnt notice this, i dont really work with replset's

**Comment by boredland** [comment]
Just one thing to add @jloveridge metioned what I think is this particular scenario:

```
// Any servers defined within `opts.instanceOpts` should be started first as
// the user could have specified a `dbPath` in which case we would want to perform
// the `replSetInitiate` command against that server.
```
https://github.com/nodkz/mongodb-memory-server/blob/master/packages/mongodb-memory-server-core/src/MongoMemoryReplSet.ts#L165

**Comment by Ranguna** [comment]
+1 for this. I'm getting the following error when I attempt to restart a replica set:
```
MongoError: No host described in new configuration 59874 for replica set testset maps to this node
```

**Comment by hasezoey** [comment]
@Ranguna you are experiencing an different problem:
https://github.com/nodkz/mongodb-memory-server/blob/e658cc4467c25cb54adf3c534a70fa45d1e9e331/packages/mongodb-memory-server-core/src/__tests__/replset-single-restart-test.ts#L38-L48

**Comment by hasezoey** [comment]
@sakulstra

aside from this, how does the (original issue's) error happen? i mean this package (core) has an test for this:
https://github.com/nodkz/mongodb-memory-server/blob/e658cc4467c25cb54adf3c534a70fa45d1e9e331/packages/mongodb-memory-server-core/src/__tests__/replset-single-restart-test.ts#L18-L51

**Comment by hasezoey** [comment]
This issue didnt have activity (from non-maintainers) in over an month, closing

**Comment by sunhaolin** [comment]
+1 for this.
```bash
MongoMS:MongoInstance 2021-01-21T14:57:12.540+0800 I  COMMAND  [conn2] command admin.$cmd command: replSetInitiate { replSetInitiate: { _id: "rsSteedos", members: [ { _id: 0, host: "127.0.0.1:53110" } ], settings: { electionTimeoutMillis: 500 } }, $clusterTime: { clusterTime: Timestamp(0, 0), signature: { hash: BinData(0, 0000000000000000000000000000000000000000), keyId: 0 } }, $db: "admin" } numYields:0 ok:0 errMsg:"already initialized" errName:AlreadyInitialized errCode:23 reslen:238 locks:{} protocol:op_msg 1961ms
  MongoMS:MongoInstance 2021-01-21T14:57:12.540+0800 I  NETWORK  [conn1] end connection 127.0.0.1:53113 (1 connection now open)
  MongoMS:MongoInstance 2021-01-21T14:57:12.540+0800 I  NETWORK  [conn2] Error sending response to client: SocketException: ������ǰ�Ĺرյ��ã��׽������Ǹ������Ѿ��رգ����ͻ�������ݵ�����û�б����ܡ�. Ending connection from 127.0.0.1:53114 (connection id: 2)
  MongoMS:MongoInstance 2021-01-21T14:57:12.540+0800 I  NETWORK  [conn2] end connection 127.0.0.1:53114 (0 connections now open)
  MongoMS:MongoInstance  +2ms
(node:5796) UnhandledPromiseRejectionWarning: MongoNetworkError: connection 1 to 127.0.0.1:53110 closed
    at D:\learn\node\mongodb-memory-server-core\node_modules\mongodb\lib\cmap\connection.js:68:15
    at Map.forEach (<anonymous>)
    at Socket.<anonymous> (D:\learn\node\mongodb-memory-server-core\node_modules\mongodb\lib\cmap\connection.js:67:20)
    at Socket.emit (events.js:314:20)
    at TCP.<anonymous> (net.js:675:12)
(node:5796) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the 
CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5796) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by hasezoey** [comment]
@sunhaolin please try again with the latest beta release (which currently is `7.0.0-beta.14`)

**Comment by sunhaolin** [comment]
@hasezoey  use mongodb-memory-server-core@7.0.0-beta.14
```
D:\learn\node\mongodb-memory-server-core>node index.js
dbPath:  D:\learn\node\mongodb-memory-server-core\db
  MongoMS:MongoMemoryReplSet waitUntilRunning: stopped +0ms
(node:5704) UnhandledPromiseRejectionWarning: Error: State is not "running" or "init" - cannot wait on something that dosnt start
    at MongoMemoryReplSet.<anonymous> (D:\learn\node\mongodb-memory-server-core\node_modules\mongodb-memory-server-core\lib\MongoMemoryReplSet.js:307:27)
    at Generator.next (<anonymous>)
    at fulfilled (D:\learn\node\mongodb-memory-server-core\node_modules\tslib\tslib.js:114:62)
(node:5704) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the 
CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5704) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
index.js   :
```js
import { MongoMemoryReplSet } from 'mongodb-memory-server-core';
import * as path from 'path';

async function startDB() {
  let dbPath = path.join(process.cwd(), 'db');
  console.log('****************dbPath: ', dbPath);
  const opts = {
    binary: {
      version: '4.2.11',
      downloadDir: './bin/mongodb',
    },
    replSet: {
      storageEngine: 'wiredTiger',
    },
    instanceOpts: [
      {
        port: 27017,
        dbPath: dbPath,
      },
    ],
  };
  const replSet = new MongoMemoryReplSet(opts);
  await replSet.waitUntilRunning();
  const uri = await replSet.getUri();
  console.log('****************uri: ', uri);
  // or you may obtain the connection config parts:
  // const port = await replSet.getPort();
  // const dbPath = await replSet.getDbPath();
  // const dbName = await replSet.getDbName();

  // stop replica set manually
  // replSet.stop();
  // or it should be stopped automatically when you exit from script
}

startDB();
```

**Comment by hasezoey** [comment]
@sunhaolin your example seems to follow what the README examples are, which are not updated yet to the new version,
so either use the documentation (which is not publicly running yet), which can be started with downloading this repo, going inside `website`, running `yarn install` and then `yarn start` and go to the site displayed in the terminal
or
modified your code to work with the new version:
```ts
import { MongoMemoryReplSet } from "mongodb-memory-server-core";
import * as path from "path";

async function startDB() {
  // note: this path must exists before running this script, otherwise it will error
  const dbPath = path.join(process.cwd(), "db");
  console.log("*dbPath: ", dbPath);
  const replSet = await MongoMemoryReplSet.create({
    // binary: { // commented out, because i dont have this binary at such an path
    //   version: "4.2.11",
    //   downloadDir: "./bin/mongodb",
    // },
    replSet: {
      storageEngine: "wiredTiger",
    },
    instanceOpts: [
      {
        // port: 27017,
        port: 9000, // different port, because i already have another instance running
        dbPath,
      },
    ],
  });
  const uri = replSet.getUri();
  console.log("uri: ", uri);

  await replSet.stop();
}

startDB();
```

Note: this is *how* it should look like, but after running it, i noticed #431

**Comment by sunhaolin** [comment]
@hasezoey thank you very much!
