### ISSUE TITLE
enable journaling on test

### ISSUE THREAD

**Issue by sibelius** [nodkz/mongodb-memory-server#279]
## Versions

- NodeJS: 12.4.0
- mongodb-memory-server-*: 5.2.1
- mongodb: 3.5.2
- mongoose: 5.9.4 
- system: 

package: mongo-memory-server-global 

## What is your question?

We are improving our writeConcern in mongoose, but we are getting the following error:

```jsx
MongoError: cannot use 'j' option when a host does not have journaling enabled

      at Connection.<anonymous> (node_modules/mongodb/lib/core/connection/pool.js:450:61)
      at processMessage (node_modules/mongodb/lib/core/connection/connection.js:384:10)
      at Socket.<anonymous> (node_modules/mongodb/lib/core/connection/connection.js:553:15)
```

is it possible to enable journaling when testing? or should we change `j` based on test environment?

**Comment by hasezoey** [comment]
this seems like an nodejs-mongodb error, you need to enable journaling on the instance

**Comment by hasezoey** [comment]
it seems like journaling isnt enabled in the instance, [look here for how to enable it](https://docs.mongodb.com/manual/core/journaling/#journaling-and-the-in-memory-storage-engine) (for the default engine in this package)

and closing because stale for over 3 months
