### ISSUE TITLE
Deep requiring uuid/v4 is deprecated as of uuid@7.x.

### ISSUE THREAD

**Issue by cncolder** [nodkz/mongodb-memory-server#280]
## Versions

- NodeJS: v13.10.1
- mongodb-memory-server-core: 6.3.2
- system: Linux

package: mongo-memory-server-core

## What is the Problem?

> DeprecationWarning: Deep requiring like `const uuidv4 = require('uuid/v4');` is deprecated as of uuid@7.x. Please require the top-level module when using the Node.js CommonJS module or use ECMAScript Modules when bundling for the browser. See https://github.com/uuidjs/uuid/blob/master/README.md#upgrading-from-v3x-of-this-module for more information.

## Do you know *why* it happenes?

https://github.com/nodkz/mongodb-memory-server/blob/d78ca69bc03902e1db72c971eb60c9503429f589/packages/mongodb-memory-server-core/src/util/db_util.ts#L1

**Comment by hasezoey** [comment]
thanks, will be fixed when #281 gets merged (with various other dependency updates)
