### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by SantiagoHerreG** [nodkz/mongodb-memory-server#285]
## Versions
I am using latest versions (2020):
+ chai for requests to the app server
+ express
+ mongoose
+ mongodb-memory-server

## What is your question?

I am always getting this error:
`(node:4927) UnhandledPromiseRejectionWarning: RangeError: Array buffer allocation failed`

Right after `MongoMS:MongoBinaryDownload extract()` in debug mode. Any suggestion?

**Comment by hasezoey** [comment]
*sorry for an late response*

---

- please always include the versions (even if they are latest at that point)
- please include on which system you are running this package
- what is your nodejs version?

**Comment by hasezoey** [comment]
closing because stale for over 2 months and probably fixed by the replacement #274
