### ISSUE TITLE
Unnecessary non-devDependencies in mongodb-memory-server-core

### ISSUE THREAD

**Issue by ulrichb** [nodkz/mongodb-memory-server#286]
## Versions

- mongodb-memory-server-*: 6.3.3

package: mongodb-memory-server-core

## What is the Problem?

`mongodb-memory-server-core` installs a lot of unnecessary dependencies (e.g. all the `@types/...`) in a consuming project: 

https://github.com/nodkz/mongodb-memory-server/blob/52289e85710ac0b552ba50e9c9db32d4aef26547/packages/mongodb-memory-server-core/package.json#L49-L60

Please move them into `devDependencies`.

**Comment by hasezoey** [comment]
if types are devDeps, then in some projects the types would need to be installed manually or wont work at all, so all types that are accessible from "the outside" should be in the normal deps, but otherwise i agree that not *all* need to be in there

**Comment by hasezoey** [comment]
cc @nodkz

**Comment by ulrichb** [comment]
@hasezoey I just took a quick look at the generated `.d.ts` files and the only re-exported external types I saw were from `@types/tmp`.

Note that also `https-proxy-agent` is re-exported, but this package has its own typings.

**Comment by nodkz** [comment]
Related issue https://github.com/nodkz/mongodb-memory-server/pull/266 
So we may move @types/* to devDependencies, except @types/tmp.
@ulrichb can you open PR?
