### ISSUE TITLE
Migrate from `get-port` package to `portfinder`

### ISSUE THREAD

**Issue by nodkz** [nodkz/mongodb-memory-server#287]
`get-port` has stupid internal port locking from 15 till 30 seconds which cannot be disabled.

[portfinder](https://github.com/http-party/node-portfinder) is better 
- does not have internal lock
- it has build-in debug via `debug` package like 

The real problem with `get-port` can be found in the following test case where we should write crazy comments:
https://github.com/nodkz/mongodb-memory-server/blob/d2873eaa34a1a29bb10ce57ebd7d412e1b68bc77/packages/mongodb-memory-server-core/src/__tests__/replset-single-restart-test.ts#L35-L46

**Comment by hasezoey** [comment]
just tested replacing the package, tests failed because of race-conditions

**Comment by hasezoey** [comment]
i think this can be closed, because `portfinder` (without the delay) will make the tests full of race-conditions (without having to use `runInBand`)
