### ISSUE TITLE
Overwrite complete version string

### ISSUE THREAD

**Issue by 0Ams** [nodkz/mongodb-memory-server#295]
## What is your question?
* I am using a `debian92` version of os (mongodb-linux-x86_64-debian92-3.2.17.tgz), but since there is no such version of `mongod dl`.
* So I would like to download and use `mongodb-linux-x86_64-3.2.17.tgz` except `debian92`.

> I'd like to hear some advice on how I can download to `mongodb-linux-x86_64-3.2.17.tgz`.

**Comment by hasezoey** [comment]
you can overwrite what versions you specifically want
[look here](https://github.com/nodkz/mongodb-memory-server#available-options-for-mongomemoryserver) at the `binary` options, there you can overwrite anything for version generation

**Comment by 0Ams** [comment]
@hasezoey 
I referred to the basic option, but I didn't find an option to prevent me from referring to the `os-release` I wanted. 
I want to block or exclude functions that refer to getOS() '/etc/os-release' that operate when creating mongod binary down url. I will install a sub-version.

Advice is needed as the only possible method currently is to delete '/etc/os-release'.

**Comment by hasezoey** [comment]
@0Ams is what #413 does the thing that was requested?

specifically: c19d2167a88977a67c886f651bf0a70dcf51a806

**Comment by hasezoey** [comment]
closing because included since `7.0.0-beta.8`
