### ISSUE TITLE
mongodb-memory-server with CircleCI

### ISSUE THREAD

**Issue by MiluchOK** [nodkz/mongodb-memory-server#296]
## Versions

- NodeJS: 12.16.1
- mongodb-memory-server-*: 6.5.1
- mongodb: -
- mongoose: -
- system: Docker image: circleci/node:12.16.1

package: mongo-memory-server 

## What is your question?

When I try to use `mongodb-memory-server` on CircleCI, I face issues. Please let me know if there is a configuration that can be used. I tried downgrading the package and it simply led to other issues. Here is a specific issue I see: https://circleci.com/gh/MiluchOK/milkinium-api/138

Code can be found here: https://github.com/MiluchOK/milkinium-api

Please advise

**Comment by manuel114** [comment]
@MiluchOK I have the exact same issue, have you been able to solve it?

**Comment by hasezoey** [comment]
@MiluchOK your provided output from CircleCI is not visible to anyone without an account, and it didnt have any debug logs - could you re-run it with debug enabled? (https://github.com/nodkz/mongodb-memory-server#enable-debug-mode)
