### ISSUE TITLE
@types/get-port@4.2.0 dependency is deprecated

### ISSUE THREAD

**Issue by lafeuil** [nodkz/mongodb-memory-server#298]
## Versions

- NodeJS: 12
- mongodb-memory-server-*: 6.5.2
- mongodb: 4.2-next
- system: Linux

package: mongo-memory-server

## What is the Problem?
After installing the mongo-memory-server, I have this deprecated warning :  
```
npm WARN deprecated @types/get-port@4.2.0: This is a stub types definition. get-port provides its own type definitions, so you do not need this installed.
```

This dependency is in mongodb-memory-server-core package.
```
$ npm ls @types/get-port
[...]
└─┬ mongodb-memory-server@6.5.2
  └─┬ mongodb-memory-server-core@6.5.2
    └── @types/get-port@4.2.0 
```

## Do you know *why* it happenes?

*no*

**Comment by lafeuil** [comment]
I don't check but I think you can remove this dependency because the types definition are defined in the main package `get-port`.

**Comment by hasezoey** [comment]
@lafeuil it will get removed once we move from `get-port` to `portfinder` #287
