### ISSUE TITLE
How to specify authentication username, password and database when starting with `auth` set to `true`

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [nodkz/mongodb-memory-server#299]
## Versions

- NodeJS: 12.13.1
- mongodb-memory-server-*: 6.5.2
- mongodb: 4.2.2
- mongoose: 5.9.7
- system: Win10

package: mongo-memory-server 

## What is your question?

I am using this package in my tests. My actual code has my mongoose connecting to a secured db with credentials. So, I am getting an authentication failed error when I am starting the mongo memory server without auth and mongoose in my code passes in a username and password along with the test database.

Now, I know I can work around this by changing how the module which handles mongoose connection behave differently during test(not pass the username and password) but I saw that there is an option to start mongo memory server with `auth`. So, when I enable `auth` and try to connect with mongoose **without** auth, it gets connected but operations are not authzd, as expected.

But if I want mongoose to connect to the mongo memory server instance which has auth enabled, how do I specify the username, password and db?

Or should I drop this approach.

**Comment by hasezoey** [comment]
from what i know, you need to first connect to the db (without auth), create an admin account and then restart with auth enabled

**Comment by SayakMukhopadhyay** [comment]
I am not sure if I get you. 
> you need to first connect to the db (without auth), create an admin account(or the account needed)

You mean connect with `mongodb-memory-server`? Or just logging into the Mongo shell
> then restart with auth enabled

If I restart `mongodb-memory-server` with auth enabled, I would need to pass the password anyway right? My problem is that the there is no option to pass the username and password in the first place.

**Comment by hasezoey** [comment]
@SayakMukhopadhyay from what i know, there arnt any options to specify an username or password on db creation, so you need to spin up an instance with auth disabled, login there (either mongo shell or mongodb driver) create an user, shutdown the instance and start it up again with auth enabled

**Comment by flolu** [comment]
It would be really awesome to have something like this:
```typescript
const mongod = new MongoMemoryServer({
  instance: {
    auth: {
      user: 'username',
      password: 'password'
    }
  }
})
```
---

Or at least there shouldn't be an error when a `user` and a `password` is provided while conneting:
```typescript
new MongoClient('', {auth: {user: 'username', password: 'password'}}).connect()
```
Currently the line above will throw `MongoError: Authentication failed.`

**Comment by hasezoey** [comment]
> Or at least there shouldn't be an error when a user and a password is provided while conneting:

sorry we cant do anything about this, this is an mongod / nodejs-mongodb driver problem

---

otherwise i planned this to include in 7.0 (not any time soon probably)

**Comment by SayakMukhopadhyay** [comment]
Are you open to a PR? I can look into adding this feature.

**Comment by hasezoey** [comment]
@SayakMukhopadhyay yes we are open to PR's, if you can figure out where and how to put it (there currently are no convenient hooks for such things)

**Comment by hasezoey** [comment]
closing because authentication handling got added in `7.0.0-beta.6`
