### ISSUE TITLE
Giving SchemaOptions to mongoose schema throws error

### ISSUE THREAD

**Issue by onuriltan** [nodkz/mongodb-memory-server#301]
## Versions

- NodeJS: 12.16.1
- mongodb-memory-server: 1.6.5
- mongodb: 4.2.3
- mongoose: 5.7.1
- system: MacOs Catalina 10.15.3

package: mongodb-memory-server 

## What is the Problem?
If I give mongoose SchemaOptions as `{ timestamps: true, collection: 'users' }`, mongoose model throws error as `TypeError: this.getValue is not a function`, if I don't give SchemaOptions it works as expected. 

### Working code
```ts
import { Schema } from 'mongoose';
const userSchema = new Schema({
  name: String,
});

const userModel = mongoose.model<UserDoc>('user', userSchema)
const created = userModel.create({
  "name" : "onur"
})
console.log(created)
// logs { _id: 5e944bc9374c1a22b86e8c13, name: onur, __v: 0 } 
```

 ### Non-Working code
```ts
import { Schema } from 'mongoose';
const userSchema = new Schema({
  name: String,
}, { timeStamps: true, collection: 'users' } ); // giving SchemaOptions here

const userModel = mongoose.model<UserDoc>('user', userSchema)
const created = userModel.create({
  "name" : "onur"
})
console.log(created)
// throws error "this.getValue is not a function"
```

## Do you know *why* it happenes?
Giving SchemaOptions to mongoose.Schema causing the error, otherwise it works perfect.

### StackTrace
```
TypeError: this.getValue is not a function 
    at model.<anonymous> (/Users/.../node_modules/mongoose/lib/schema.js:1029:21)
    at callMiddlewareFunction (/Users/.../node_modules/kareem/index.js:474:23)
    at model.next (/Users/.../node_modules/kareem/index.js:58:7)
    at _next (/Users/.../node_modules/kareem/index.js:106:10)
    at /Users/.../kareem/index.js:499:38
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

**Comment by hasezoey** [comment]
and what has this to do with the mongo-memory-server project?

**Comment by onuriltan** [comment]
In the documentation recommended use is to create mongoose connection by using mongodb-memory-server and create mongoose schema and create the model, so I can really make the integration testing without any dependency, but giving options to schema throws error so I thought it is a bug since a lot of projects uses schemas by giving options to them, why do you think it is not relevant?

**Comment by hasezoey** [comment]
@onuriltan what you are describing seems like an *mongoose* error, not an *mongo-memory-server* error

if you are new: mongodb dosnt have / use schemas, this is used by mongoose for validation, mongodb has since about 4.0 schemas too, but are optional and from what i know mongoose schemas dont translate to mongodb schemas

**Comment by onuriltan** [comment]
Yes it is true, they are different things. I just see examples with  _mongoose_ in the readme so I thought you are also supporting the use with it. Do you have any suggestions using it with mongoose? Maybe I can try to remove _SchemaOptions_ by cloning the schema object and deleting keys which include those options.

**Comment by hasezoey** [comment]
@onuriltan just because this project uses mongoose as an example, dosnt mean this project accepts bug reports for it

otherwise, judging from the examples given, you dont `await` the `.create`(Promise) function and i would recommend to upgrade to the latest mongoose (5.9)

**Comment by onuriltan** [comment]
@hasezoey You are correct, I can close the issue since it does not fully support mongoose, I will try your solution or create a real database for the test pipeline to solve the problem, thanks a lot!

**Comment by onuriltan** [comment]
@hasezoey By the way the issue is fully about the mongoose, nothing to do with mongodb and this library, thanks again.
