### ISSUE TITLE
Reusing already dowloaded binary tar.

### ISSUE THREAD

**Issue by as-ajitsingh** [nodkz/mongodb-memory-server#303]
## Versions
- NodeJS: 13.7.0
- mongodb-memory-server-core: 6.5.2
- mongodb: any
- system: any

package: mongo-memory-server-core

## What is your question?
Does it make sense to have a check for already downloaded mongod binary tar, so to skip the download process again and continue with the unzipping process? 

### Reason
On slow networks, it may happen that binary got downloaded(after jest timeout) but due to jest timeout settings test cases failed. In this case, running test cases again will get the already downloaded binary tar(after performing integrity test) and use that to run the mongo instance.

**Comment by sibelius** [comment]
I think it already does this https://github.com/nodkz/mongodb-memory-server/blob/master/packages/mongodb-memory-server/postinstall.js

**Comment by hasezoey** [comment]
@sibelius no it currently dosnt check if there already exists an downloaded `tar` (zipped version)
