### ISSUE TITLE
Doesn't work on Fedora 32

### ISSUE THREAD

**Issue by rhinoman** [nodkz/mongodb-memory-server#304]
## Versions

- NodeJS: 12.16.2
- mongodb-memory-server-*: 6.5.2
- mongodb: N/A
- mongoose: 5.4.16
- system: 

package: mongodb-memory-server
possible are:
mongo-memory-server
mongo-memory-server-core
mongo-memory-server-global
-->

## What is the Problem?

The server apparently times out when running unit tests with jest.  Everything works fine on Fedora 31, Centos 7/8, Ubuntu, etc...

`Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.`

## Code Example

```ts
N/A
```

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment]
please provide debug logs https://github.com/nodkz/mongodb-memory-server#enable-debug-mode

**Comment by rhinoman** [comment]
`  MongoMS:MongoMemoryServer Called MongoMemoryServer.ensureInstance() method: +0ms
  MongoMS:MongoMemoryServer  - no running instance, call `start()` command +0ms
  MongoMS:MongoMemoryServer Called MongoMemoryServer.start() method +0ms
  MongoMS:MongoMemoryServer Starting MongoDB instance with following options: {"port":27017,"dbName":"emissive","ip":"127.0.0.1","storageEngine":"ephemeralForTest","dbPath":"/tmp/mongo-mem-95366GjddYjj4lNW","tmpDir":{"name":"/tmp/mongo-mem-95366GjddYjj4lNW"},"uri":"mongodb://127.0.0.1:27017/emissive?"} +3ms
  MongoMS:MongoBinary MongoBinary options: {"downloadDir":"/home/jcadam/novetta/emissive-user-service/node_modules/.cache/mongodb-memory-server/mongodb-binaries","platform":"linux","arch":"x64","version":"4.0.14"} +0ms
  MongoMS:MongoBinary MongoBinary: Mongod binary path: /home/jcadam/novetta/emissive-user-service/node_modules/.cache/mongodb-memory-server/mongodb-binaries/4.0.14/mongod +2ms
  MongoMS:MongoInstance Mongo[27017]: Called MongoInstance._launchKiller(parent: 9536, child: 9549): +0ms
  MongoMS:MongoBinary MongoBinary: Download lock removed +10ms
  MongoMS:MongoInstance Mongo[27017]: STDERR: /home/jcadam/novetta/emissive-user-service/node_modules/.cache/mongodb-memory-server/mongodb-binaries/4.0.14/mongod: error while loading shared libraries: libcrypto.so.10: cannot open shared object file: No such file or directory
  MongoMS:MongoInstance  +4ms
  MongoMS:MongoInstance Mongo[27017]: CLOSE: 127 +0ms
  MongoMS:MongoInstance Mongo[27017]: [MongoKiller]: exit - [0,null] +2s
`

**Comment by rhinoman** [comment]
```
  MongoMS:MongoMemoryServer Called MongoMemoryServer.ensureInstance() method: +0ms
  MongoMS:MongoMemoryServer  - no running instance, call `start()` command +0ms
  MongoMS:MongoMemoryServer Called MongoMemoryServer.start() method +0ms
  MongoMS:MongoMemoryServer Starting MongoDB instance with following options: {"port":27017,"dbName":"emissive","ip":"127.0.0.1","storageEngine":"ephemeralForTest","dbPath":"/tmp/mongo-mem-95366GjddYjj4lNW","tmpDir":{"name":"/tmp/mongo-mem-95366GjddYjj4lNW"},"uri":"mongodb://127.0.0.1:27017/emissive?"} +3ms
  MongoMS:MongoBinary MongoBinary options: {"downloadDir":"/home/jcadam/novetta/emissive-user-service/node_modules/.cache/mongodb-memory-server/mongodb-binaries","platform":"linux","arch":"x64","version":"4.0.14"} +0ms
  MongoMS:MongoBinary MongoBinary: Mongod binary path: /home/jcadam/novetta/emissive-user-service/node_modules/.cache/mongodb-memory-server/mongodb-binaries/4.0.14/mongod +2ms
  MongoMS:MongoInstance Mongo[27017]: Called MongoInstance._launchKiller(parent: 9536, child: 9549): +0ms
  MongoMS:MongoBinary MongoBinary: Download lock removed +10ms
  MongoMS:MongoInstance Mongo[27017]: STDERR: /home/jcadam/novetta/emissive-user-service/node_modules/.cache/mongodb-memory-server/mongodb-binaries/4.0.14/mongod: error while loading shared libraries: libcrypto.so.10: cannot open shared object file: No such file or directory
  MongoMS:MongoInstance  +4ms
  MongoMS:MongoInstance Mongo[27017]: CLOSE: 127 +0ms
  MongoMS:MongoInstance Mongo[27017]: [MongoKiller]: exit - [0,null] +2s

```

**Comment by rhinoman** [comment]
Ok guys, installing package compat-openssl10 fixes it!

**Comment by maks-io** [comment]
I don't want to spam here, but I can also confirm this works. Thank you @rhinoman !

**Comment by hasezoey** [comment]
closing because not an direct issue with this package

**Comment by dylanwulf** [comment]
The package `compat-openssl10` is no longer available in the fedora 34 repos :(

**Comment by hasezoey** [comment]
@dylanwulf thanks for reporting, next time please open another issue - do you maybe know if this is from fedora 34 onward, or already from fedora 33?

**Comment by hasezoey** [comment]
@dylanwulf support for fedora 34+ is now added in `7.0.0-beta.39`

**Comment by hasezoey** [comment]
@dylanwulf thanks for the information, for now `rhel80` is used for fedora 34+
