### ISSUE TITLE
MongoBinary "can't find system binary at path. callback is not a function"

### ISSUE THREAD

**Issue by ewrogers** [nodkz/mongodb-memory-server#305]
## Versions

- NodeJS: 12.13.0
- mongodb-memory-server-*: 6.5.2
- mongodb: 3.5.7
- macOS 10.15.4

package: mongodb-memory-server-core

## What is the Problem?

The `systemBinary` does not seem to get detected, despite existing at the path expected. I have installed `mongodb` via official homebrew instructions.

It still tries to download the binary despite it existing at the path specified.

    MongoMS:MongoBinary MongoBinary options: {"downloadDir":"REDACTED/node_modules/.cache/mongodb-memory-server/mongodb-binaries","platform":"darwin","arch":"x64","version":"4.0.14","systemBinary":"/usr/local/bin/mongod"} +187ms
    MongoMS:MongoBinary MongoBinary: can't find system binary at /usr/local/bin/mongod. callback is not a function +1ms
    MongoMS:MongoBinaryDownloadUrl Using "mongodb-osx-ssl-x86_64-4.0.14.tgz" as the Archive String +0ms
    MongoMS:MongoBinaryDownloadUrl Using "https://fastdl.mongodb.org" as the mirror +1ms
    MongoMS:MongoBinaryDownload Downloading: "https://fastdl.mongodb.org/osx/mongodb-osx-ssl-x86_64-4.0.14.tgz" +0ms

In `package.json`: 

    "mongodbMemoryServer": {
      "disablePostinstall": "1",
      "systemBinary": "/usr/local/bin/mongod",
      "md5Check": "1"
    }

Checking that it exists locally:

    $ which mongod
    > /usr/local/bin/mongod

    $ ls -la /usr/local/bin | grep mongod
    > lrwxr-xr-x mongod -> ../Cellar/mongodb-community/4.2.1/bin/mongod

I can run `mongod` locally just fine.

## Code Example

    beforeEach(async () => {
      mongod = new MongoMemoryServer({
        instance: {
          dbName: 'test'
        }
      })

      argv.uri = await mongod.getUri()
    })

Using `jest`:

    MONGOMS_DEBUG=1 npm test -- --runInBand --detectOpenHandles"

## Do you know *why* it happenes?

No.

What is really strange is that it's only with this particular project that I experience this issue. Other projects with same versions of every dependency and testing structure do not have this problem it seems.

I've been comparing the two projects and I don't see anything that sticks out.

**Comment by hasezoey** [comment]
i think this has something to do that macos handles some fs functions differently, so the function `fs.access` dosnt work like in linux/windows

**Comment by ewrogers** [comment]
Yes! Been peeking at the code and [seen this line](https://github.com/nodkz/mongodb-memory-server/blob/master/packages/mongodb-memory-server-core/src/util/MongoBinary.ts#L39) in MongoBinary (L#39).

What I do not understand is *why* does it work for one project and not the other? It should fail in both for similar reasons and configurations.

But in the other project I get the expected:

    MongoMS:MongoBinary MongoBinary options: {"downloadDir":"REDACTED/node_modules/.cache/mongodb-memory-server/mongodb-binaries","platform":"darwin","arch":"x64","version":"4.0.3","systemBinary":"/usr/local/bin/mongod"} +58ms
      MongoMS:MongoBinary MongoBinary: found sytem binary path at /usr/local/bin/mongod +1ms
      MongoMS:MongoBinary MongoBinary: Mongod binary path: /usr/local/bin/mongod +23ms

**Comment by ewrogers** [comment]
Ah, I think I have found the issue. We are using `jest` to mock `fs` calls, and `access` is one of them. Ugh.

What I don't get is we `await` the `getUri()` call, which in theory should wait for it to have spun up already in the `beforeEach` or `beforeAll` call. The mocks are done inside the tests themselves, not before or globally.

So why are the mocks executing before the `beforeAll` `beforeEach` calls?

**Comment by ewrogers** [comment]
Looks like I've learned a fun part about jest...

Calls to `jest.spyOn' mocking `fs` do live past the lifetime of the test itself (I assume due to the `fs` reference being imported only once).

Lesson learned: use `mockRestore()` to restore original functions so other libraries can call those functions:

```
beforeEach(async() => {
  // do mongo memory server stuff here
 
  fsAccessMock = jest.spyOn(fs, 'access').mockImplementation(...)
  fsAccessSyncMock = jest.spyOn(fs, 'accessSync').mockImplementation(true)
  fsReadFileMock = jest.spyOn(fs, 'readFile').mockImplementation(...)
})

afterEach(async () => {
    fsAccessMock && fsAccessMock.mockRestore()
    fsAccessSyncMock && fsAccessSyncMock.mockRestore()
    fsReadFileMock && fsReadFileMock.mockRestore()
})
```

Fixed now! Closing this issue and just giving the caveat to future readers: **careful of what you mock in tests!**
