### ISSUE TITLE
How to setup initial data in the database?

### ISSUE THREAD

**Issue by JonasWestAlro** [nodkz/mongodb-memory-server#309]
For a lot of our tests it would be neat (or even necessary) to have some existing data in the database before running the test. One way to populate the database would be to make a general script or function, that could create all the test documents, and call that script before each test case, but I am afraid the script will be messy, and it will be difficult to create all references between documents etc.

Therefore, I am trying to figure out if I can create a complete dump of a sandbox database (maybe a subset of our already existing production database) that I can initialize the mongodb-memory-server with, before each test case?

Is that possible? and is there maybe a better way of doing this?

**Comment by hasezoey** [comment]
> One way to populate the database would be to make a general script or function, that could create all the test documents

i would recommend this way, the other way would be to copy the created db's folder over and over

> Is that possible? and is there maybe a better way of doing this?

there is no build-in way, either an copy of the folder, or an setup script

**Comment by JonasWestAlro** [comment]
@hasezoey OK thank you for a quick response. 
The db's folder is created where? And I assume I would have to create/copy the folder before initializing the database, or is it possible to overwrite the folder after the database instance is spun up?

**Comment by hasezoey** [comment]
you can use the option `dbPath` to set where the db is stored, the default is (on linux) in `/tmp` and then `mongo-mem-` with some random string appended

**Comment by JonasWestAlro** [comment]
OK great. Thank you.

**Comment by Benjadahl** [comment]
For anyone else getting here: Using mongoimport and mongoexport also seems like a viable strategy

**Comment by hasezoey** [comment]
> For anyone else getting here: Using mongoimport and mongoexport also seems like a viable strategy

true, but it would require downloading the archive again, because MMS *only* extracts the `mongod` binary file

**Comment by thardy** [comment]
Let's say I have a mongo-init.js file filled with things I want to add to my newly created MongoMemoryServer. How do I execute that script against my in-memory server programmatically?
