### ISSUE TITLE
[feature request] Reuse mongod instances

### ISSUE THREAD

**Issue by sibelius** [nodkz/mongodb-memory-server#315]
## Versions

- NodeJS: 12
- mongodb-memory-server-*: 6.6.1
- mongodb: 3.5.8
- mongoose: 5.9.17 
- system: macos and linux

package: mongo-memory-server 

## Feature Request

I'd like to reuse `mongod` instances in our jest tests

We use this approach https://itnext.io/parallel-testing-a-graphql-server-with-jest-44e206f3e7d2

that uses mongodb-memory-server to run tests in parallel, each test file has a mongod.
We use `maxWorkers=4` and what I've notice is the following behavior

It spin up a new `mongod` for each one of the workers, so we have 4 mongod process running
And when the tests finished, we have mongo_kill script to kill them.
And more 4 mongod are spinning

What if we could reuse mongod process? Like a poll of mongod process.

I think this would be much more efficient

**Comment by hasezoey** [comment]
you could look at how [typegoose](https://github.com/typegoose/typegoose) handles this, typegoose uses jest & mongo-memory-server

**Comment by sibelius** [comment]
the idea would be to have a single instance, and use multiple databases?

can you also check this behavior https://github.com/nodkz/mongodb-memory-server/issues/300#issuecomment-640576422?

**Comment by nodkz** [comment]
You may do it via creating a custom environment for Jest.

The code should be something like (the following code is a just an example of how we read `.env.test` files instead of `.env`):
```js
/* eslint-disable @typescript-eslint/no-var-requires */
const NodeEnvironment = require('jest-environment-node');

class ServerEnvironment extends NodeEnvironment {
  constructor(config, context) {
    super(config, context);
    this.config = config;
    // this.testPath = context.testPath;
  }

  async setup() {
    await super.setup();
    this.preparePolyfills();

    // await someSetupTasks(this.testPath);
    // this.global.someGlobalObject = createGlobalObject();
  }

  async teardown() {
    // this.global.someGlobalObject = destroyGlobalObject();
    // await someTeardownTasks();
    await super.teardown();
  }

  runScript(script) {
    return super.runScript(script);
  }

  preparePolyfills() {
    const r = require('dotenv').config({
      path: require('path').resolve(this.config.globals.dotEnvDir, '.env.test'),
      debug: process.env.DEBUG,
    });

    if (r && r.parsed) {
      this.global.process.env = {
        ...this.global.process.env,
        ...r.parsed,
      };
    }
  }
}

module.exports = ServerEnvironment;
```

So you need to initialize MMS here as you custom global env variable, and reuse existed MMS instance. Sorry, I don't have any ready solution. So try to figure out it yourself. And I will be very appreciated if you find a solution and share it with community. Thanks!

**Comment by sibelius** [comment]
After digging more into this, let me share more what I've found.

Our current solution uses this environment (https://github.com/entria/entria-fullstack/blob/master/packages/server/test/environment/mongodb.js):

```jsx
/* eslint-disable */
const MongodbMemoryServer = require('mongodb-memory-server');
const NodeEnvironment = require('jest-environment-node');

class MongoDbEnvironment extends NodeEnvironment {
  constructor(config) {
    console.error('\n# MongoDB Environment Constructor #\n');
    super(config);
    this.mongod = new MongodbMemoryServer.default({
      instance: {
        // settings here
        // dbName is null, so it's random
        // dbName: MONGO_DB_NAME,
      },
      binary: {
        version: '4.0.10',
      },
      // debug: true,
      autoStart: false,
    });
  }

  async setup() {
    await super.setup();
    console.error('\n# MongoDB Environment Setup #\n');
    await this.mongod.start();
    this.global.__MONGO_URI__ = await this.mongod.getConnectionString();
    this.global.__MONGO_DB_NAME__ = await this.mongod.getDbName();
    this.global.__COUNTERS__ = {
      user: 0,
    };
  }

  async teardown() {
    await super.teardown();
    // console.error('\n# MongoDB Environment Teardown #\n');
    await this.mongod.stop();
    this.mongod = null;
    this.global = {};
  }

  runScript(script) {
    return super.runScript(script);
  }
}

module.exports = MongoDbEnvironment;
```

it will spin up 1 `mongod` per test file, with `maxWorker=4`, we gonna have 4 mongod per time, if `mongo_kill.js` works properly.

----
A better solution would be to have a single `mongod` running instance, and let each test have a different database name, so tests won't conflict with each other

We can move the `MongodbMemoryServer` to `global setup` and `global teardown`, however this won't let us get a different database per test, neither the connection string, as you can't access global values from `global setup/teardown`

For now, I'd like to fix the `mongo_kill.js` script that is not working well in CircleCI, but the proper solution would be able to reuse the running `mongod` instance

**Comment by sibelius** [comment]
instead of many `mongod` instances, I've got working with just one

https://github.com/shelfio/jest-mongodb/pull/209

The idea is to init `mongodb-memory-server` in a global process, and save the connection URI using a file (it needs to be something serializable)
Using a custom node environment to generate a custom database name per test file

One thing that happened to me was that sometimes the `mongod` stops and restart with another port number causing tests failing
