### ISSUE TITLE
Is it possible to use the new "search" pipeline?

### ISSUE THREAD

**Issue by alexbjorlig** [nodkz/mongodb-memory-server#317]
I would love to use the new[ full-text search](https://www.mongodb.com/atlas/search) options when testing our application. When trying to do this with the mongodb-memory-server, we get the following error: 

```
Error: GraphQL error: Unrecognized pipeline stage name: '$search'
```

Would this somehow be possible - or do we have to give-up testing of full-text search?

## Versions

- NodeJS: 14
- mongodb-memory-server-*: 6.2.4
- system:MacOS

mongo-memory-server

**Comment by DilipCoder** [comment]
**$set is also missing from aggregation stage**

Versions:
"mongodb-memory-server": "^6.6.1",
system: ubuntu 18.04

**Comment by hasezoey** [comment]
please provide which mongodb version is being used

@alexbjorlig you might need to wrap it in an `$text` first (`{ $text: { $search: "something" } }`)

@DilipCoder what do you mean that `$set` is not available?

**Comment by alexbjorlig** [comment]
@hasezoey in our project we use `"mongodb-memory-server": "^6.2.4",` when testing. The full text search is available on atlas running MongoDB 4.2.

**Comment by hasezoey** [comment]
@alexbjorlig i asked for the version of mongodb, not the package version

and are you sure this is not an atlas-only feature?

**Comment by alexbjorlig** [comment]
@hasezoey - I'm sorry. I don't have the `.cache` directory in my node_modules? I just checked, and full-text search is an atlas-only feature. So I guess that closes the issue. I will cover this area in our test environment in a different way then.

**Comment by hasezoey** [comment]
@alexbjorlig that is just the default location, it might be globally installed when `-global` package is used, or when an custom path is given

**Comment by alexfoxy** [comment]
I have this issue running my tests. Error received is: `MongoError: Unrecognized pipeline stage name: '$search'`. 

```
mongo db version: 4.2.7
mongodb-memory-server: 6.6.3
mongoose: 5.9.28
```

The query runs fine when running the application. Query is as follows:

```
  const documents = await model.aggregate([
    {
      $search: {
        'text': {
          'query': searchTerm,
          'path': paths,
        },
      },
    },
    {
      $match: query,
    },
  ]).limit(limit)
    .skip(skip)
    .sort({ score: { $meta: 'textScore' } })
```

**Comment by alexfoxy** [comment]
Interestingly this is within my binaries folder:
```
ls node_modules/.cache/mongodb-memory-server/mongodb-binaries/ 
4.0.14                  4.0.14.lock.STALE       4.0.3                   4.0.3.lock.STALE
```

so `mongodb-memory-server` does not use your global version?

**Comment by hasezoey** [comment]
@alexfoxy when you mean system-installed binary, no this package dosnt without config for it, if you use the normal package the binary gets stored in `node_modules/.cache` and if using the global version then in `~/.cache/mongodb-binaries`

if you want to use the system-binary, you need to set option [`binary.systemBinary`](https://github.com/nodkz/mongodb-memory-server#available-options-for-mongomemoryserver)

**Comment by alexfoxy** [comment]
@hasezoey it's part of the Mongo Atlas search index feature:

https://docs.atlas.mongodb.com/reference/atlas-search/tutorial/#run-your-first-atlas-search-query

**Comment by alexfoxy** [comment]
@hasezoey also I don't understand, why mongo-memory-server installs the `4.0.14` binary, in the docs it says it will install the latest?

**Comment by alexfoxy** [comment]
@hasezoey I'm also wondering now if this is unsupported then? For my tests I will have to think of a work around..

**Comment by hasezoey** [comment]
@alexfoxy from what it seems, it is an atlas-exclusive feature

**Comment by johnrb2** [comment]
Since there is now a [local version of atlas](https://www.mongodb.com/docs/atlas/cli/stable/atlas-cli-deploy-docker/) available, will you be updating `mongodb-memory-server` to support Atlas Search?

**Comment by hasezoey** [comment]
@johnrb2 to my current knowledge, this "local atlas deployment" requires its own cli-tool and podman, which are requirements i would not like to currently add to MMS. 
If anything it would at the very least be another class altogether (like `MongoMemoryReplSet` and `MongoMemoryServer`, along the lines of `MongoMemoryAtlas`)
