### ISSUE TITLE
[Peppermint] Distribution Support

### ISSUE THREAD

**Issue by ravirajawasthi** [nodkz/mongodb-memory-server#318]
## Versions

- NodeJS: v12.18.0
- mongodb-memory-server-*: 6.6.1
- mongoose: ^5.9.13
- system: Ubuntu 18.04 Peppermint OS

package: mongo-memory-server 6.6.1

## What is the Problem?

I can't install mongodb-memory-server using npm

![image](https://user-images.githubusercontent.com/27188880/84758846-99250a80-afe3-11ea-9637-aa1d3641bd21.png)
When i try to install

![image](https://user-images.githubusercontent.com/27188880/84759076-e30df080-afe3-11ea-996b-f80abddef2b4.png)
System Specs

![image](https://user-images.githubusercontent.com/27188880/84759563-83fcab80-afe4-11ea-99b6-1207959a0bdb.png)
Uname -a output

I've tried using version latest in package.json

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment]
simple issue when looking at the code, the code checks for an regex containing `mint`, expecting something like `Linux Mint`, but not `Peppermint`

@ravirajawasthi do you know what base what version of peppermint uses or where to look at?

**Comment by ravirajawasthi** [comment]
This might help : https://peppermintos.com/2019/12/peppermint-10-respin-released/

**Comment by tudormd** [comment]
Pop!_OS  - https://pop.system76.com/
failed to download/install MongoDB binaries. The error: Error: Status Code is 403 (MongoDB's 404)
 "version": "4.2.8"

**Comment by hasezoey** [comment]
partially fixed by #341 (31183dd)

**Comment by hasezoey** [comment]
This issue maybe be fixed by PR #432

**Comment by hasezoey** [comment]
Pull Request #432 got merged into `7.0.0-beta.16`, could someone test if `Peppermint` gets an correctly installed mongodb binary?

**Comment by hasezoey** [comment]
closing because this should be fixed since `7.0.0-beta.16`, thanks to reading `/etc/upstream-release/lsb-release`
