### ISSUE TITLE
Process pooling feature

### ISSUE THREAD

**Issue by TanukiSharp** [nodkz/mongodb-memory-server#319]
## Versions

- NodeJS: 10
- mongodb-memory-server-*: 6.6.1
- system: Linux (Ubuntu 16.04) in Docker on MacOS Catalina

package: mongo-memory-server

## What is your question?

Is there a process pooling feature built-in ?

To give you context, I'm running unit tests but they have to run in sequence because they use the same DB process and would other overlap and fail running in parallel. To get them running in parallel, I spawn one instance of `mongodb-memory-server` per test process, so tests run "isolated" and that's great, it works. However, the cost of spawning and killing processes is still big, so instead I thought keeping processes running for reuse could be a great win.

To give you an idea, for the moment my tests still run faster in sequence (spawning and killing only one process) than in parallel (spawning and killing N processes).

I could implement process pooling on my side, but before I go this way, I wanted to make sure I'm not reinventing the wheel.

Thanks.

**Comment by nodkz** [comment]
Nope, there is no process pooling. It quite difficult to implement inside test case (worker). It should be implemented on runner level (eg. Jest environment) which will share poll across workers.

If you get such solution please share it. If it possible of course.

**Comment by hasezoey** [comment]
from what i know, there is `globalSetup` and `globalTeardown`, but i dont know if that is what @nodkz means
-> [typegoose](https://github.com/typegoose/typegoose/tree/master/test) uses this

**Comment by hasezoey** [comment]
Process Pooling will not be an feature of this project, for something like this, use something like in jest [`globalSetup`](https://jestjs.io/docs/en/configuration#globalsetup-string) and [`globalTeardown`](https://jestjs.io/docs/en/configuration#globalteardown-string) options

**Comment by hasezoey** [comment]
more in-depth example added in c31098000e2732740997e002a87aac19a006f645, should also be in the documentation if it ever gets online
