### ISSUE TITLE
Define Commit Format

### ISSUE THREAD

**Issue by hasezoey** [nodkz/mongodb-memory-server#325]
it would be better if there was an standard definition on how to structure commits

something like [Angular's](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-format)

**Comment by nodkz** [comment]
For now, we are using [semantic-release](https://github.com/semantic-release/semantic-release) for package publishing. It uses the following Commit Message Header – `<type>(<scope>): <short summary>`. According to `<type>` semantic-release takes decision what version to publish next.

@hasezoey what do you want to suggest – just add docs or husky with commitlint or something else?

**Comment by hasezoey** [comment]
when you mean husky, do you mean [this husky](https://github.com/typicode/husky)?

> just add doc

because i dont work in this project much, i forgot the style of the commits, and i couldnt find CONTRIBUTING or an section in the README

**Comment by hasezoey** [comment]
> we are using semantic-release for package publishing

btw, i couldnt find any information about this: when does it release an version, after some time, manual trigger or commit accumulation (/commit count)? (like accumulating multiple things for an minor release)

**Comment by nodkz** [comment]
### About Husky

Yep, this husky (https://github.com/typicode/husky). We use it internally in our private repos. It checks before commit:
- staged files for eslint rules
- checks commit message

But if something incorrect it blows console log with a lot of logs. It's quite annoying. It very easy to control with the internal teams but for OSS it can be a blocker issue for new contributors.

So I think that we should not use husky for OSS project. I think we can fix any errors from our contributors and for now it not bother us a lot.

### Automatic releasing process

1) Only on `master` branch executed this command (after success tests)
https://github.com/nodkz/mongodb-memory-server/blob/5d662645bf3a9828709d27f749cc3bbbfd8d2395/.circleci/config.yml#L58
2) This command calls `lerna`
https://github.com/nodkz/mongodb-memory-server/blob/5d662645bf3a9828709d27f749cc3bbbfd8d2395/package.json#L37
3) Lerna uses the following config for `publish` command
https://github.com/nodkz/mongodb-memory-server/blob/5d662645bf3a9828709d27f749cc3bbbfd8d2395/lerna.json#L4-L16
4) The most interesting thing is `"conventionalCommits": true` and it poorly described in Lerna repo. This thing before publishing gather new commits from previous release and according to commit messages
- understands which next version should be published – `*.*.Z+1`, `*.Y+1.0` or `X+1.0.0`
- get text from them for publishing in release notes if the new release was publushed

More details about what kind of messages should be – can be found here https://www.conventionalcommits.org/ 

So this procedure works quite well and helps automatically publish new package versions after merging PRs to master.

### Contributing section

This is my weak side. No one my repo does not have CONTRIBUTING.md. @hasezoey  can you suggest a good example? 

We definitely should add this thing as you did with templates for issues. They work perfectly!

**Comment by hasezoey** [comment]
> This is my weak side. No one my repo does not have CONTRIBUTING.md. @hasezoey can you suggest a good example?

i dont have good examples, the one for typegoose i just made on-the-fly to have one and to have some style structure

i think the file should mention:
- commit structure
- what to run before the pr / if using husky, it should mention husky (or husky like)
