### ISSUE TITLE
$merge aggregation stage seems not to be supported

### ISSUE THREAD

**Issue by bwhisp** [nodkz/mongodb-memory-server#331]
## Versions

- NodeJS: 12.18.3
- mongodb-memory-server-*: 6.6.1
- mongodb: 4.2.8
- system: 
     - Ubuntu 20.04 running on WSL for Windows 10
     - Heroku CI pipeline (which is running Linux I assume)

package:
mongo-memory-server (in package.json and node_modules)
mongo-memory-server-core (only in node_modules)

## What is the Problem?
`$merge` aggregation stage seems not to be supported 

## Code Example

```ts
  const aggregationStages = [
    { $match: {} },
    ... (some other aggregation stages)
    { $merge: { into: 'User', on: '_id', whenMatched: 'merge', whenNotMatched: 'discard' } }
  ];
  // Following line is an equivalent of db.getCollection('User_temp')
  const collectionConnector = app.models.User.getDataSource().connector.db.collection('User_temp');
  collectionConnector.aggregate(aggregationStages);
```

running this code fails with the following error :  
```
MongoError: Command does not support writeConcern
      at MessageStream.messageHandler (node_modules/mongodb/lib/cmap/connection.js:261:20)
      at MessageStream.EventEmitter.emit (domain.js:483:12)
      at processIncomingData (node_modules/mongodb/lib/cmap/message_stream.js:144:12)
      at MessageStream._write (node_modules/mongodb/lib/cmap/message_stream.js:42:5)
      at doWrite (_stream_writable.js:403:12)
      at writeOrBuffer (_stream_writable.js:387:5)
      at MessageStream.Writable.write (_stream_writable.js:318:11)
      at Socket.ondata (_stream_readable.js:716:22)
      at Socket.EventEmitter.emit (domain.js:483:12)
      at addChunk (_stream_readable.js:295:12)
      at readableAddChunk (_stream_readable.js:271:9)
      at Socket.Readable.push (_stream_readable.js:212:10)
      at TCP.onStreamRead [as _originalOnread] (internal/stream_base_commons.js:186:23)
      at TCP.<anonymous> (node_modules/async-listener/glue.js:188:31)
```

## Do you know *why* it happens?

*no*, but if I replace `$merge` with `$out` the code runs fine 
The problem is I cannot use $out, because there I don't want to override every document of my `User` collection

**Comment by hasezoey** [comment]
could you provide an link to the documentation of this operator, because i cannot find it, i can only find `$mergeObjects` and `$concat`?

**Comment by bwhisp** [comment]
Sure, here it is : https://docs.mongodb.com/manual/reference/operator/aggregation/merge/

However, it is an aggregation pipeline stage and not an operator.

Short description: it behaves like a `$out` except that it doesn't replace the whole destination collection

**Comment by hasezoey** [comment]
from what i can tell from the error, the problem is that some command (in this example) does not support the option `writeConcern` but is passed somewhere, without an more detailed trace / error, i cannot tell what command has this error

**Comment by bwhisp** [comment]
Please, tell me what kind of traces you would like. 

mongodb-memory-server is used through unit tests. I tried to search for writeConcern but I only found results in mongodb package

I also tried to run debugger and break on this error, but the stack makes it very complicated to find from where the error was originally thrown because it gets passed around a huge amount of times

In my code, `mongodb-memory-server` gets initilized this way : 
```
  const { MongoMemoryServer } = require('mongodb-memory-server');
  const mongod = new MongoMemoryServer({ instance: { dbName: TEST_DB_NAME } });
  mongod.getConnectionString().then((uri) => {
    process.env.MEMORY_DB_URI = uri;
    next();
  });
```

**Comment by hasezoey** [comment]
i guess the best way to find what actually caused it, surround everything with console.log(or equivalent)

**Comment by bwhisp** [comment]
Hello, 
I have just debugged a little on it. 
What I can see for the moment is that the MongoClient is created with a writeConcern for which `w === 1`

I am still debugging on the issue. 
Anyways, thank you very much for your help

**Comment by hasezoey** [comment]
this is either an duplicate of #336 or using an mongod version before `4.2` (or something else?)

closing because stale for more than 1 month
