### ISSUE TITLE
How can I ensure that while running tests, I can start a session and not close the connection?

### ISSUE THREAD

**Issue by dondrzzy** [nodkz/mongodb-memory-server#339]
## Versions

- NodeJS: v14.3.0
- mongodb: v4.0.1
- mongoose: 5.9.16
- mongo-memory-server-core: 6.6.4

## What is your question?
I am testing out mongoose atomic transactions. While creating a user, I perform all operations under a transaction. This works just fine in the development environment but fails when running tests
```js
// db connection
const { MongoMemoryReplSet } = require('mongodb-memory-server');

if (process.env.NODE_ENV === 'testing') {
  const replSet = new MongoMemoryReplSet({
    replSet: { storageEngine: 'wiredTiger' },
  });
  await replSet.waitUntilRunning();
  const uri = await replSet.getUri();

  mongoose.set('useFindAndModify', false);
  mongoose.set('useCreateIndex', true);
  mongoose.connect(uri, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  });
} else {
  mongoose.connect(settings.uri, {
    useNewUrlParser: true,
    useCreateIndex: true,
    useUnifiedTopology: true,
    replicaSet: 'rs',
  });
}

// user controller
const mongoose = require('mongoose');

controller.createUser = async (req, res) => {
  const session = await mongoose.startSession();
  session.startTransaction();

  const user = new User({username: req.body.username})
  try {
    await user.save({ session });
    await session.commitTransaction();
    ...
  } catch (err) {
    await session.abortTransaction();
    throw new Error(err)
  } finally {
    session.endSession();
  }
  ...
}

// test
describe('user api routes', () => {
  it('should create a user', async () => {
    const res = await request(app).post('/api/v1/users').send({});
})
```
> npm test
```
Error MongooseError: Connection 0 was disconnected when calling `startSession
```
When I remove the transaction code and session, it works just fine.

**Comment by hasezoey** [comment]
sorry for an late response, could you provide [debug log](https://github.com/nodkz/mongodb-memory-server#enable-debug-mode)?

**Comment by abishek28007** [comment]
Error Log:
errmsg:'Transaction numbers are only allowed on a replica set member or mongos',
code: 20,
codeName: 'IllegalOperation',
name: 'MongoError',

**Comment by hasezoey** [comment]
@abishek28007 this error seems to say that you arnt using an replicaset, transactions are only supported on replicasets

**Comment by abishek28007** [comment]
@hasezoey  I am trying to write unit test for transaction, how do I enable that on mongodb-memory-server

**Comment by hasezoey** [comment]
@abishek28007 you need to import and use [`MongoMemoryReplSet`](https://github.com/nodkz/mongodb-memory-server#replica-set-start)
