### ISSUE TITLE
"failed to download/install MongoDB binaries. The error: Error: Status Code is 403" in v6.6.4 on MacOS

### ISSUE THREAD

**Issue by e-compton** [nodkz/mongodb-memory-server#340]
## Versions

- NodeJS: 12.16.1
- mongodb-memory-server-*: 6.6.4
- mongodb: 4.0.13
- system: MacOS Catalina 10.15.5

package: mongo-memory-server

## What is the Problem?

During installation and at runtime the packages throws an error when downloading mongodb.
```
mongodb-memory-server: checking MongoDB binaries cache...
failed to download/install MongoDB binaries. The error: Error: Status Code is 403 (MongoDB's 404)
```

The error is exclusive to 6.6.4 and we are currently pinning the version to 6.6.3 as a workaround.

## Code Example

```ts
npm i mongodb-memory-server
```

## Do you know *why* it happens?

Upon inspection of the code it is generating this URL to download mongodb, which returns 403:
https://fastdl.mongodb.org/osx/mongodb-macos-x86_64-4.0.13.tgz

Whereas version 6.6.3 uses this URL which does work:
https://fastdl.mongodb.org/osx/mongodb-osx-ssl-x86_64-latest.tgz

**Comment by hasezoey** [comment]
what is your config for mongo version?

**Comment by e-compton** [comment]
Its not set to anything:
```
  "config": {
    "mongodbMemoryServer": {
      "debug": "1"
    }
  },
```

**Comment by hasezoey** [comment]
with 31183ddcb3f75e3270d1cd15157636aa167b8035 (#341 / 6.6.5) this should be fixed
