### ISSUE TITLE
The requested module 'mongodb-memory-server' does not provide an export named 'MongoMemoryServer' when testing with jest

### ISSUE THREAD

**Issue by bvqbao** [nodkz/mongodb-memory-server#343]
## Versions

- NodeJS: v14.7.0
- mongodb-memory-server-*: 6.6.6
- mongodb: 4.4.0
- mongoose: 5.10.1
- system: Windows 10

package: mongo-memory-server 

## What is your question?

I try to use mongodb-memory-server with jest but it fails with the following error:

`The requested module 'mongodb-memory-server' does not provide an export named 'MongoMemoryServer'`

**product.test.js**
```js
import * as db from './db'
import * as productService from '../src/services/product'

beforeAll(db.connect)
afterEach(db.clearDatabase)
afterAll(db.closeDatabase)

const sampleProduct = {
    name: 'iPhone 11',
    price: 699,
    description: 'It is a iPhone. What do you expect?'
}

describe('product ', () => {
    it('can be created correctly', async () => {
        const savedProduct = await productService.create(sampleProduct)
        expect(savedProduct._id).toBeDefined()
        expect(savedProduct.name).toBe(sampleProduct.name)
    })
})
```
**db.js**

```js
import mongoose from 'mongoose'
import { MongoMemoryServer } from 'mongodb-memory-server';

const mongod = new MongoMemoryServer()

export const connect = async () => {
    const uri = await mongod.getUri()

    await mongoose.connect(uri, {
        useNewUrlParser: true,
        useUnifiedTopology: true
    })
}

export const closeDatabase = async () => {
    await mongoose.disconnect()
    await mongod.stop()
}

export const clearDatabase = async () => {
    const collections = mongoose.connection.collections

    for (const key in collections) {
        const collection = collections[key]
        await collection.deleteMany()
    }
}
```
**package.json**

```json
{
  "name": "in-memory-db-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "node --experimental-vm-modules node_modules/jest/bin/jest.js --runInBand"
  },
  "type": "module",
  "jest": {
    "testEnvironment": "jest-environment-node",
    "transform": {}
  },
  "config": {
    "mongodbMemoryServer": {
      "systemBinary": "C:\\mongodb\\bin\\mongod.exe",
      "debug": "0"
    }
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "mongoose": "^5.10.1"
  },
  "devDependencies": {
    "jest": "^26.4.2",
    "jest-environment-node": "^26.3.0",
    "mongodb-memory-server": "^6.6.6"
  }
}
```
Any sugguestion?

Thanks.

**Comment by hasezoey** [comment]
some questions:
- what is your tsconfig?
- is the tsconfig applied to jest as well (tsc, tsnode, ts-jest)?
- does it work outside of jest?

**Comment by bvqbao** [comment]
There is no tsconfig file in my project.

It works if I rewrite all the code using `require` syntax instead of `import` syntax.

So I'm not sure what is wrong here.

**Comment by hasezoey** [comment]
> There is no tsconfig file in my project.

so all plain js?

**Comment by bvqbao** [comment]
Yes.

**Comment by hasezoey** [comment]
and are you working with esmodules or commonjs modules?

because this project dosnt support esmodules / esm import (yet)

**Comment by bvqbao** [comment]
All my code files use plain js with esm `import` / `export` syntax.

In the jest test example from README.md, I see you can use `import { MongoMemoryServer } from 'mongodb-memory-server'`

So apparently, we can't use the `import` syntax with mongo-memory-server?

**Comment by hasezoey** [comment]
that is provided by typescript, it gets compiled into what it needs to be

**Comment by bvqbao** [comment]
Got it. That was a little bit confusing for a newbie like me.
Thanks for your help.
