### ISSUE TITLE
Vulnerability Issue With bl < 2.2.1

### ISSUE THREAD

**Issue by jasonwu2153** [nodkz/mongodb-memory-server#349]
## Issue

Just got a message from one of my repos about a security vulnerability with bl below version 2.2.1. It seems like this repo still uses v2.2.0. Would be great if this could be updated.

![Screenshot from 2020-09-03 09-32-47](https://user-images.githubusercontent.com/45532884/92121653-880cbe00-edc8-11ea-8827-704f2565f7ac.png)

**Comment by hasezoey** [comment]
package `bl` is not installed directly in one of the packages here, so it will depend on when the other packages are upgraded

**Comment by jasonwu2153** [comment]
Ah understood - thank you!

**Comment by hasezoey** [comment]
#348 got merged, next version will include it

**Comment by nodkz** [comment]
Please let us know when this PR be accepted https://github.com/mongodb/node-mongodb-native/pull/2536 and the new package `mongodb` be published.

Only after that, we can eliminate this warning.

**Comment by kylepeeler** [comment]
Anything I (first-time contributor 😄) can do to help get this moved along? Merging the above and this one would help to resolve a high npm vulnerability currently blocking CI on another project

**Comment by hasezoey** [comment]
@kylepeeler the fix on this package already got applied #348, but because this package uses yarn, its only `yarn.lock` which got updated, otherwise we need to wait for mongodb to merge the mentioned PR and release it

**Comment by kylepeeler** [comment]
https://github.com/mongodb/node-mongodb-native/pull/2536 seems to have been merged and the issue resolved, should we close this issue?
