### ISSUE TITLE
[Question]: Possible to use mongoimport

### ISSUE THREAD

**Issue by simplecommerce** [nodkz/mongodb-memory-server#350]
## Versions

- NodeJS: 12.15.0
- mongodb-memory-server-*: 6.6.7
- mongodb: 4.0.2
- system:  Operating System: Ubuntu 18.04.1 LTS, Kernel: Linux 4.15.0-88-generic, Architecture: x86-64

package: 
mongo-memory-server

## What is your question?

Hi, I was wondering if it was possible to use mongoimport command line via nodejs script to import .json files into the mongodb instance created by this package.

I tried it, but it says
`error: Command failed: mongoimport /bin/sh: 1: mongoimport: not found`

I was only wondering if something like this is possible at all using this package or do I have to manually run insert queries to populate the database.

Thanks!

**Comment by hasezoey** [comment]
not possible *with just this package*, it is recommended to use the mongodb-nodejs-driver, and if you still have to execute some things directly, use [`db.command`](https://mongodb.github.io/node-mongodb-native/3.6/api/Db.html#command)

ps: this package only extracts `mongod`, the server file
