### ISSUE TITLE
Is mongodb-memory-server intended to be supported on nodejs 8.x?

### ISSUE THREAD

**Issue by philsteph** [nodkz/mongodb-memory-server#351]
## Versions

- NodeJS: 8.9.1
- mongodb-memory-server-*: 6.6.3+
- mongodb: 4.2
- mongoose: 5.2
- system: Windows 10, Linux RHEL7/8

package: mongo-memory-server-global

## What is your question?

The documentation at https://github.com/nodkz/mongodb-memory-server references requirements of "NodeJS: 8+" however, as of mongodb-memory-server-global v6.6.3 this appears to be no longer the case.

Version 6.6.2 referenced camelcase ^5.3.1 (https://github.com/nodkz/mongodb-memory-server/blob/v6.6.2/packages/mongodb-memory-server-core/package.json)
Whereas 6.6.3 now references camelcase ^6.0.0 (https://github.com/nodkz/mongodb-memory-server/blob/v6.6.3/packages/mongodb-memory-server-core/package.json)

Looking at camelcase 6.0.0 we can see a commit (https://github.com/sindresorhus/camelcase/commit/878bc443148512abed0f899b5baac386550a316c) that states a requirement for nodejs 10.

Attempting to `npm install` on nodejs 8.9.1 with any version of mongodb-memory-server-global at version 6.6.3 onwards results in:
> \> mongodb-memory-server@6.6.3 postinstall C:\temp\foo\node_modules\mongodb-memory-server-global\node_modules\mongodb-memory-server
> \> node ./postinstall.js
> 
> C:\temp\foo\node_modules\mongodb-memory-server-global\node_modules\camelcase\index.js:17
>                 } else if (isLastCharUpper && isLastLastCharUpper && /[\p{Ll}]/u.test(character)) {
>                                               ^
> 
> SyntaxError: Invalid regular expression: /[\p{Ll}]/: Invalid escape
>     at preserveCamelCase (C:\temp\foo\node_modules\mongodb-memory-server-global\node_modules\camelcase\index.js:17:33)
>     at Object.camelCase [as default] (C:\temp\foo\node_modules\mongodb-memory-server-global\node_modules\camelcase\index.js:63:11)
>     at Object.resolveConfig [as default] (C:\temp\foo\node_modules\mongodb-memory-server-global\node_modules\mongodb-memory-server-core\lib\util\resolve-config.js:33:320)
>     at Object.<anonymous> (C:\temp\foo\node_modules\mongodb-memory-server-global\node_modules\mongodb-memory-server\postinstall.js:27:41)
>     at Module._compile (module.js:635:30)
>     at Object.Module._extensions..js (module.js:646:10)
>     at Module.load (module.js:554:32)
>     at tryModuleLoad (module.js:497:12)
>     at Function.Module._load (module.js:489:3)
>     at Function.Module.runMain (module.js:676:10)
> npm WARN Error: EPERM: operation not permitted, lstat 'C:\temp\foo\node_modules\mongodb-memory-server-global\node_modules'
> npm WARN  { Error: EPERM: operation not permitted, lstat 'C:\temp\foo\node_modules\mongodb-memory-server-global\node_modules'
> npm WARN   stack: 'Error: EPERM: operation not permitted, lstat \'P:\\git\\MHSC CDW\\data-services\\node_modules\\mongodb-memory-server-global\\node_modules\'',
> npm WARN   errno: -4048,
> npm WARN   code: 'EPERM',
> npm WARN   syscall: 'lstat',
> npm WARN   path: 'P:\\git\\MHSC CDW\\data-services\\node_modules\\mongodb-memory-server-global\\node_modules' }
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! mongodb-memory-server@6.6.3 postinstall: `node ./postinstall.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the mongodb-memory-server@6.6.3 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\name\AppData\Roaming\npm-cache\_logs\2020-09-07T09_23_18_002Z-debug.log

However, version 6.6.2 of mongodb-memory-server-global installs successfully on nodejs 8.9.1.

As such, should I fix to use version 6.6.2 of mongodb-memory-server-global until I can move off of nodejs 8, which is going to be some time unfortunately? Seems a shame to break compatibility with older versions of nodejs though.

**Comment by hasezoey** [comment]
didnt notice there was an engine upgrade in an lower package, next major version will bump it up to lowest LTS(/Maintenance) NodeJS Version (10)

so for now, try to upgrade nodejs or use an lower version of this package

**Comment by hasezoey** [comment]
made official with #356

**Comment by philsteph** [comment]
Ah okay great, good to know, thanks. Will follow the nodejs upgrade route then.

Thanks for the quick response.
