### ISSUE TITLE
Branches & Protection

### ISSUE THREAD

**Issue by hasezoey** [nodkz/mongodb-memory-server#362]
I wanted to ask (for CONTRIBUTING.md additions), what protections are currently on the `master` branch and what style it should follow like: linear-commit-history (no merge commits) and/or no direct commits?

and i wanted to ask if we maybe should create an `next` branch to prepare versions before they are automatically released (like some minor and major versions)

**Comment by nodkz** [comment]
For now, there is no protection on `master`. And sometimes I do direct commits to master. I know that it's a bad practice but it's very fast. Anyway, this repo became quite popular so l'd added the following restrictions:

<img width="920" alt="Screen Shot 2020-09-09 at 18 29 21" src="https://user-images.githubusercontent.com/1946920/92598315-73e62680-f2ca-11ea-8b7c-6b079b5469ec.png">

I don't like merge commits. Linear history is a good thing 👌

**Comment by nodkz** [comment]
In most cases, fast feature delivery is gold. But sometimes when you want to deliver breaking changes - it's better to use `alpha`, `beta` branches. They're already supported by semantic-release. And `next` branch too, about it in the next section.

For example, in repo https://github.com/graphql-compose/graphql-compose-mongoose/releases I'm preparing a new major version via `alpha` packages.

They work very simple:
- Just create `alpha` branch
- When opening PRs choose `alpha` branch for merging (instead of master)
- Use commit messages as usual with commit-lint style
- When PR merged with `alpha` semantic-release will automatically publish a new `alpha` package
- When `alpha` branch is ready and the last `alpha` package is tested by several 3rd parties – then you merge `alpha` branch to `master`.

So let use `alpha` & `beta` only for huge breaking changes. More details described here https://semantic-release.gitbook.io/semantic-release/usage/workflow-configuration#pre-release-branches 

All configurations already made by default https://semantic-release.gitbook.io/semantic-release/usage/configuration#branches

### What about `next` branch?

Frankly, I did not test it in our workflows. So I don't know which cons we will get with the additional tag in npm. How will work `yarn upgrade interactive` or `npm-check`...

Anyway I prefer `alpha` branch workflow because it doesn't have any restrictions like [has `next`](https://semantic-release.gitbook.io/semantic-release/usage/workflow-configuration#pushing-to-a-release-branch).

**Comment by nodkz** [comment]
For me `prerelease` workflow (`alpha` & `beta`) is more clear and obvious. Rather than `next`, `master`.

**Comment by hasezoey** [comment]
i thought that the `next` branch would be most appropriate for this repository (to not have too many branches)

> How will work yarn upgrade interactive or npm-check...

by default this command uses `latest` tag, and with `--latest` it will use it too, and you can use `--next` to use the next tag

and i recommended next because i was it was already supported by semantic-release - i would just need to confirm what versioning it will use (like in this branch will it actually use the normal style `x.x.x` or the pre-release style `x.x.x-x`)

**Comment by hasezoey** [comment]
just as an addition / example, in typegoose i use an branch like `r6` for major version 6, and otherwise just push to master (more or less like here), and i never worked with an workflow that required more than 2 branches (i worked with `next -> master` but not like `unstable -> next -> master`)
-> this question is mainly to have an branch that can act as an accumulator of changed before an version gets published (like having multiple feature pull request, but dont want on each merge an new minor/major version number)

**Comment by nodkz** [comment]
If you already have experience with `next` – let's try it here! And in the battle, I'll understand how it works. 😉

**Comment by hasezoey** [comment]
> If you already have experience

just want to clarify, yes i "have experience", but that was only when i worked alone on an project

**Comment by nodkz** [comment]
`unstable -> next -> master` - NO ))) We are not so big for such workflow. `next -> master` will be enough.

**Comment by nodkz** [comment]
> just want to clarify, yes i "have experience", but that was only when i worked alone on an project

no problem ;) i'm ready for testing in the battle 😈

**Comment by nodkz** [comment]
And I'm don't worry about `next` branch. If we will work together there are 2 variants:
- 1) we together working directly on branch `next`:  somebody of us notices that upstream has a commit and we also locally made commit. Then 1) just delete local commit `git reset HEAD~1` 2) pull new changes 3) again stage and commit your changes
- 2) we are working in different branches and then open PRs to the `next` branch
- 3) (preferrable way) you are working as usual on `next` branch, and if 
  - I want to add new features, then I just open new PR to `next` branch
  - I review your code and want to make some code refactor - then I switched to 2nd scenario.

**Comment by hasezoey** [comment]
> no problem ;) i'm ready for testing in the battle smiling_imp

i will try to set it up after all the current PR's have been merged

---

> If we will work together there are 2 variants

> somebody of us notices that upstream has a commit and we also locally made commit.

how about `git pull --rebase`? (if possible of course) or using `git stash`

---

i would be for that hotfixes are directly made to master (and merged back to next?) but i dont know how this will affect linear-history
-> it wouldnt be nice if just for linear-history we would have to rebase branches (non-pr branches)

for this repository i would stay with my current model: create `feature/` / `fix/` branches and depending on severity (like hotfix) make pr (so that it can be reviewed before merge & make sure tests run) / directly commit to next (more or less on hotfixes)

**Comment by hasezoey** [comment]
now that i think about this, how will this be handled (when no merge-commits are used):
when we would push nest to master (or anything to master) and an new version (commit) is pushed, how will this get to the next branch when not using merge-commits and without rebasing the next branch? and after than (if we should use merge commits in next), how to bring it back to master without using rebase / merge-commit there? (i mean `ff-only` would sometimes be an option, but i think not always)

**Comment by nodkz** [comment]
Good catch! Yep, in some cases, we will be forced to rebase the `next` branch. One more downside for this approach.

Anyway, merge-commits for master branch became available again (I've removed protection for semantic-release). Let's linear-commits will be the non-strict rule. If someday you need to merge then just use it.

**Comment by hasezoey** [comment]
maybe lets try to keep linear commits, but only allow merge commits *from* next and merge the release commits (and if anything else should ever come up) back into next? (so that we have an continues history, like if we should do pre-releases with tags, so that the tags not point to an unused history)

**Comment by hasezoey** [comment]
after reading more into how semantic-release does things, i think its better to use the branch `beta` for pre-releases (like "bigger-minor" / major) versions, if we would ever need to accumulate things, and otherwise use the release-branch (`master`) for normal things (patch, "minor-minor" versions)
-> but this would also require merge-commits between the two (no-rebase)

here what i read: https://semantic-release.gitbook.io/semantic-release/usage/workflow-configuration

**Comment by hasezoey** [comment]
im gonna try using the pre-branch `beta` for #387 and #389 and see how it works

**Comment by hasezoey** [comment]
tested it (version 6.8.1), and it worked really smoothly 

PS: if we dont make changes too often, we can just use `git merge --ff-only beta` (and back), this way almost no merge commits get created

**Comment by nodkz** [comment]
Nice! I'm glad that it works smoothly. I think that we should keep alfa/beta when making big changes like your last PRs (a lot of commits, refactors, breaking changes). They are really big with great improvements.

But when we are working with PRs from the community which fixes small things it will be better to publish them ASAP without alfa/beta/next step. Contributors are very happy when their changes land on npm very fast.

**Comment by hasezoey** [comment]
> But when we are working with PRs from the community which fixes small things it will be better to publish them ASAP without alpha/beta/next step. Contributors are very happy when their changes land on npm very fast.

i understand, and by default they will target `master` anyway, and if we dont need to accumulate changes, it can be directly brought to master
-> the only cases where this would not be good is if either "beta"(or other names) is further than master *or* if there are many PR's to collect them to one release

**Comment by hasezoey** [comment]
i think this discussion is resolved
