### ISSUE TITLE
MongoMemoryReplSet: _initReplSet: is "shouldCheckForSessionSupport" still needed?

### ISSUE THREAD

**Issue by hasezoey** [nodkz/mongodb-memory-server#366]
is the following line still needed? i tested without it, and no errors

https://github.com/nodkz/mongodb-memory-server/blob/6425c78edb7f94187bc12deda21927a4efabad70/packages/mongodb-memory-server-core/src/MongoMemoryReplSet.ts#L254-L262

and the mentioned code lines changed too, to 

https://github.com/mongodb/node-mongodb-native/blob/c16ec43a3cd9a751c11b10b1b6b2bc3cc4d933c4/src/operations/execute_operation.ts#L67-L92

**Comment by hasezoey** [comment]
> Firstly comment this line for easier rollback and put TODO: remove after 2020.12 – I'm using such todo-hack internally in our projects.

as in what of these two?
- comment in-code
- add this to the commit-message

**Comment by nodkz** [comment]
TODOs in code just unobtrusively remind you about removing. So it can be removed after years if nobody doesn't work with this file.

I think it's excessive to add in commit messages. But it depends on what you want to write in commit message?

**Comment by hasezoey** [comment]
ok, just wanted to clarify
