### ISSUE TITLE
Can't run mongodb-memory-server on Linux Mint

### ISSUE THREAD

**Issue by StepanYurtsiv** [nodkz/mongodb-memory-server#38]
The same as https://github.com/nodkz/mongodb-memory-server/issues/32 but for Linux Mint.

Was trying just to make like this
```
if (/ubuntu|mint/i.test(os.dist)) {
      return this.getUbuntuVersionString(os);
}
```

But tests are failing
![image](https://user-images.githubusercontent.com/18295488/34607856-34502c64-f21e-11e7-83a2-d3d628ede2ee.png)

**Comment by nodkz** [comment]
Please run following code on your machine:

```js
import getos from 'getos';
import os from 'os';

getos((e, os) => {
  console.log(
     {
        platform: os.platform(),
        arch: os.arch(),
        version: '3.4.4',
        os,
      }
  );
});
```

Don't forget to install required packages:
```
npm install os getos
```

The problem somewhere in https://github.com/nodkz/mongodb-memory-server/blob/master/src/util/MongoBinaryDownloadUrl.js it does not understand params provided from the code above.

It quite simple to fix, just look at tests https://github.com/nodkz/mongodb-memory-server/blob/master/src/util/__tests__/MongoBinaryDownloadUrl-test.js and add your test case for MINT.

PS. How I understand MINT uses Ubuntu packages and should return such link `'https://downloads.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1404-3.4.4.tgz'` for your OS.

**Comment by nodkz** [comment]
Will be cool if you make PR.
Thanx.

**Comment by StepanYurtsiv** [comment]
Thanks! I've fixed the problem, but don't have access to the repo

**Comment by nodkz** [comment]
1. You should fork my repo. It will became avaliable under your github user.

2. You clone repo under your user name. Make proper changes. Commit snd push to github to your forked repo.

3. After pull, you open github site with your repo and can find button "create pull request". Just press it, and your changes will be submited to my repo as PullRequest.

------

Or you may publish here your changes as comment, and I put them manually.

Tnx.

**Comment by StepanYurtsiv** [comment]
Ok, I think it would be faster to publish here because changes are quite small

/src/util/MongoBinaryDownloadUrl.js
```
  getLinuxOSVersionString(os: OS): string {
     ...
     } else if (/mint/i.test(os.dist)) {
      return this.getMintVersionString(os);
    }
  }

  // eslint-disable-next-line no-unused-vars
  getMintVersionString(os: OS): string {
    // unfortunately getos doesn't return version for Mint
    return 'ubuntu1404';
  }
```

/src/util/__tests__/MongoBinaryDownloadUrl-test.js
```
describe('getMintVersionString', () => {
    const downloadUrl = new MongoBinaryDownloadUrl({
      platform: 'linux',
      arch: 'x64',
      version: '3.4.4',
    });

    it('should return an archive name for Linux Mint', () => {
      expect(
        downloadUrl.getMintVersionString({ dist: 'Linux Mint' })
      ).toBe('ubuntu1404');
    })
  });
```

**Comment by nodkz** [comment]
Tnx! 
Added your changes manually.
Already landed in the new version.
