### ISSUE TITLE
Extend Documentation with docusaurus & github-pages

### ISSUE THREAD

**Issue by hasezoey** [nodkz/mongodb-memory-server#381]
This is an question/discussion about "outsourcing" and extending the documentation into github pages with docusaurus(2)

(Example (from typegoose): https://typegoose.github.io/typegoose/)

CC @nodkz

**Comment by nodkz** [comment]
Yep, it will be an amazing thing! 👍
But currently I don’t have bandwidth for implementing it myself.

Can you make a basic setup with default (or typegoose) styles?

**Comment by hasezoey** [comment]
yes i can, and i need to ask (because its "hard" to change afterwards): do you want the url as `https://nodkz.github.io/mongodb-memory-server` or do you want `https://nodkz.github.io/docs` (would need to create an repo called "docs")

**Comment by nodkz** [comment]
Definitely `mongodb-memory-server`. In the future, we can decide to move this repo under `mongodb-memory-server` Github org. Moreover, I like when docs and code in one repo – it helps to use text search in IDE for changing all places where some construction (variable, function, anything) is present.

**Comment by hasezoey** [comment]
i will try setting it up, it would be good to have this org sooner than later, because (as i had noticed with typegoose) old links might be problematic

>  it helps to use text search in IDE for changing all places

definitely, just wanted to know your opinion

---

one last thing before being able to start: what folder structure do you want
either `/website/docs` or `/docs` (website still needed to keep all the configs for the website)

PS: do you have an icon for this project?

**Comment by hasezoey** [comment]
Note: it seems like the `website` workflow wont be executed until merged into master

**Comment by hasezoey** [comment]
@nodkz the documentation is now merged, and gh-pages (branch) created, but i think it needs to be manually enabled in the repository settings, here is how typegoose's site is configured:

![Screenshot from 2021-01-20 16-24-43](https://user-images.githubusercontent.com/10911626/105196667-27dea480-5b3c-11eb-944e-8f60cce67032.png)

**Comment by hasezoey** [comment]
Re: @nodkz could you enable github pages in repo setting? (only repository owner can do this)

**Comment by nodkz** [comment]
Wow, you wrote me about this several months ago. Sorry, I missed this. 🙏

I've just enabled it – https://nodkz.github.io/mongodb-memory-server/

**Comment by hasezoey** [comment]
thanks, i hope to extend it a bit more until 7.0.0 release
