### ISSUE TITLE
ensureInstance() hangs if mongodb executable failed to start

### ISSUE THREAD

**Issue by zoltan-mihalyi** [nodkz/mongodb-memory-server#385]
## Versions

- NodeJS: 12.13.0
- mongodb-memory-server-*: 6.8.0
- mongodb: 4.4.0
- system: Windows 10

package: mongo-memory-server-core

## What is the Problem?

`await new MongoMemoryServer().ensureInstance()` never returns.

## Code Example

```ts
await new MongoMemoryServer({binary: {version: '4.4.0'}}).ensureInstance()
```

## Do you know *why* it happenes?

Running the downloaded mongod.exe manually displays error messages about missing vcruntime140_1.dll.
After installing Microsoft Visual C++ 2015-2019 Redistributable  x86 and x64 versions, it works correctly.

**Comment by zoltan-mihalyi** [comment]
Maybe it can be reproduced on windows by uninstalling Microsoft Visual C++ 2015-2019 Redistributable packages.

ensureInstance() should throw exception in this case

**Comment by hasezoey** [comment]
could you provide the full mongod log output? because this seems like this package dosnt catch this error

**Comment by zoltan-mihalyi** [comment]
On my other machine the same problem happens, but mongod.exe prints a different error message.
mongod.exe exits with code 127, so maybe mongodb-memory-server doesn't handle the non-zero exit codes at all.

`$ ./mongod.exe`
.../node_modules/.cache/mongodb-memory-server/mongodb-binaries/4.4.0/mongod.exe: error while loading shared libraries: api-ms-win-crt-convert-l1-1-0.dll: cannot open shared object file: No such file or directory
`$ echo $?`
127

**Comment by hasezoey** [comment]
@zoltan-mihalyi could you provide the debug log?

**Comment by zoltan-mihalyi** [comment]
```
  MongoMS:MongoMemoryServer Called MongoMemoryServer.ensureInstance() method +0ms
  MongoMS:MongoMemoryServer  - no running instance, call `start()` command +1ms
  MongoMS:MongoMemoryServer Called MongoMemoryServer.start() method +0ms
  MongoMS:MongoMemoryServer Starting MongoDB instance with following options: {"port":56020,"dbName":"f390a0e9-cd76-4129-b08d-cf7080e7d9a8","ip":"127.0.0.1","storageEngine":"ephemeralForTest","dbPath":"XXX\\AppData\\Local\\Temp\\mongo-mem--3220-qZMRYiUiAUsa","tmpDir":{"name":"XXX\\AppData\\Local\\Temp\\mongo-mem--3220-qZMRYiUiAUsa"},"uri":"mongodb://127.0.0.1:56020/f390a0e9-cd76-4129-b08d-cf7080e7d9a8?"} +7ms
  MongoMS:MongoBinary MongoBinary options: {
  "downloadDir": "XXX\\node_modules\\.cache\\mongodb-memory-server\\mongodb-binaries",
  "platform": "win32",
  "arch": "x64",
  "version": "4.4.0",
  "checkMD5": false
} +0ms
  MongoMS:MongoBinary MongoBinary: Download lock removed +5ms
  MongoMS:MongoBinary MongoBinary: Mongod binary path: "XXX\node_modules\.cache\mongodb-memory-server\mongodb-binaries\4.4.0\mongod.exe" +0ms
  MongoMS:MongoInstance Mongo[56020]: Called MongoInstance._launchKiller(parent: 3220, child: 18780): +0ms
  MongoMS:MongoInstance Mongo[56020]: Mongod instance closed with an non-0 code! +53ms
  MongoMS:MongoInstance Mongo[56020]: CLOSE: 3221225781 +0ms
  MongoMS:MongoInstance Mongo[56020]: [MongoKiller]: mongo_killer: childPid not alive
  MongoMS:MongoInstance  +53ms
  MongoMS:MongoInstance Mongo[56020]: [MongoKiller]: exit - [0,null] +8ms
```
