### ISSUE TITLE
The request module is required by request-promise

### ISSUE THREAD

**Issue by robinvdvleuten** [nodkz/mongodb-memory-server#39]
I see that you've installed `request-promise` as dependency without its peer `request`. Now when you install the package, you'll run in the following warnings;

```bash
warning "mongodb-memory-server > request-promise@4.2.2" has unmet peer dependency "request@^2.34".
warning "mongodb-memory-server > request-promise > request-promise-core@1.1.1" has unmet peer dependency "request@^2.34".
```

As Yarn does not install peer dependencies automatically.

**Comment by nodkz** [comment]
Good catch!
Fixed in the new version. Tnx.
