### ISSUE TITLE
Should the port really be reset to null/undefined inside start if instance failed the first time?

### ISSUE THREAD

**Issue by hasezoey** [nodkz/mongodb-memory-server#393]
should the following code really reset port to null/undefined and not just rely on port-finding?
https://github.com/nodkz/mongodb-memory-server/blob/e563cf1e5444e485c7662178883634611297a04f/packages/mongodb-memory-server-core/src/MongoMemoryServer.ts#L101-L103

CC @nodkz

**Comment by nodkz** [comment]
```ts
this._startUpInstance()
      .catch((err) => {
        if (err.message === 'Mongod shutting down' || err === 'Mongod shutting down') {
          log(`Mongodb did not start. Trying to start on another port one more time...`);
          if (this.opts.instance && this.opts.instance.port) {
            this.opts.instance.port = null;
          }
          return this._startUpInstance();
        }
        throw err;
      })
```
This helps to find another port in `_startUpInstance`. If this method understands that the port is busy and tries to find another new one then I think we can remove this nullifying.

Sorry for the delay in answering so many simultaneous things for now (microfronteds+webpack5; auth+iam research keycloak/ory/gluu or own bicycle; tons of internal reviews) besides OSS.

**Comment by hasezoey** [comment]
> This helps to find another port in _startUpInstance. If this method understands that the port is busy and tries to find another new one then I think we can remove this nullifying.

from my current knowledge, the port-finder package that we currently use has this (and this port locking), so i wanted to ask if there was an specific reason for this

**Comment by nodkz** [comment]
Nothing more except I wrote above (to allow find another port and not be locked in the provided port). How I remember the old package didn’t look another port if the exact value was provided.

**Comment by hasezoey** [comment]
we currently use `get-port`, which has [this in the Readme#Usage](https://github.com/sindresorhus/get-port#usage)
> ```ts
> (async () => {
>   console.log(await getPort({port: 3000}));
>   // Will use 3000 if available, otherwise fall back to a random port
> })();
> ```

**Comment by nodkz** [comment]
So we can remove these lines.

**Comment by hasezoey** [comment]
closing, because #394 removed that part
