### ISSUE TITLE
Remove file "types" and put all types in the appropriate files

### ISSUE THREAD

**Issue by hasezoey** [nodkz/mongodb-memory-server#406]
Move types like:
- `DownloadProgress` into `MongBinaryDownload`
- `MongoMemoryInstancePropBase` into `MongoInstance`
- `MongoMemoryInstanceProp` into `MongoInstance`
- `StorageEngine` into ?

**Comment by nodkz** [comment]
`MongoInstance` because some binaries are supporting several engines. And Instance can not be launched without an engine (if we suppose that they do not have an engine by default).

**Comment by hasezoey** [comment]
@nodkz sorry, i dont quite understand your message - did you mean on where to put type `StorageEngine`?
anyway here re-phrased:

Proposal: 
remove file `types.ts` and move all files within into appropriate other files (like interface `DownloadProgress` into `MongBinaryDownload.ts`)
OR
move all other types from files like `MongBinaryDownload.ts` into `types.ts`

---

> StorageEngine into ?

the `?` in my original was because i dont know into which file this would be most appropriate would be, probably `MongoInstance.ts`

**Comment by nodkz** [comment]
Yep, let put `StorageEngine` in `MongoInstance.ts`.

`types.ts` should be removed. Types should be defined in that files where they are used as input arguments. Of course, that one Type can be used as input arg in several modules, but in most cases, it's obvious which file should be chosen for keeping this Type. 

PS. For now, TS supports [`import type`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export) clause so there is no purpose for such kind of general file with types.

**Comment by hasezoey** [comment]
> PS. For now, TS supports import type clause so there is no purpose for such kind of general file with types.

actually, even before. typescript automatically removed imports that were only types (`import type` is mainly aimed at `isolatedModules`)

**Comment by hasezoey** [comment]
closing because fixed since `7.0.0-beta.6`
