### ISSUE TITLE
throw custom error on "lib*" missing

### ISSUE THREAD

**Issue by alexandrulesi** [nodkz/mongodb-memory-server#408]
## Versions

- NodeJS: v12.18.3
- mongodb-memory-server-*: 6.9.2
- mongodb: 3.2.7
- system: Fedora 32 Linux 5.8.13-200.fc32.x86_64

package: mongo-memory-server 

## What is the Problem?

Running jest failed throwing:

`
mongod instance closed with code 127`

## Do you know *why* it happenes?

Enabling debugging revealed:

`libcrypto.so.10: cannot open shared object`

Then installing `compat-openssl` fixed the issue

**Comment by hasezoey** [comment]
this is not really an bug of *this* package, i will change this to an "feature request" (as in throwing an custom error on lib* missing)

**Comment by GeorgeSapkin** [comment]
One Fedora 33 the package is called `compat-openssl10`.

**Comment by alexandrulesi** [comment]
Thanks for the answers! Going to close the issue

**Comment by hasezoey** [comment]
> Thanks for the answers! Going to close the issue since there's nothing to be done from what I can tell.

as i said before, i converted this issue to an feature request to "throw an custom error if an lib is missing", which is not implemented yet

**Comment by alexandrulesi** [comment]
> > Thanks for the answers! Going to close the issue since there's nothing to be done from what I can tell.
> 
> as i said before, i converted this issue to an feature request to "throw an custom error if an lib is missing", which is not implemented yet

Oh sorry I misunderstood

**Comment by hasezoey** [comment]
closing because extra logging got added in `7.0.0-beta.21`
