### ISSUE TITLE
mongodb-memory-server is adding a prefix to index name what is overflowing namespace

### ISSUE THREAD

**Issue by PedroQwe** [nodkz/mongodb-memory-server#409]
## Versions

- NodeJS: 12.18.3
- mongodb-memory-server-*: 6.9.2
- mongodb: 3.4.4
- mongoose: 4.11.4
- system: MacOS 10.15.6

package: mongo-memory-server

## What is the Problem?

I am trying to use the mongodb-memory-server to run the unit tests of my application. The problem is that I have some compound indexes and they work fine in local mongo instance, I do not need to create an index name. But when I run in mongodb-memory-server the generated name is too long because there is a prefix in the index name.

## Code Example

```js
MySchema.index({"superLongNameField1" : 1,  "superLongNameField2": 1, "superLongNameField3": 1, "superLongNameField4" : 1, "superLongNameField5" : 1});

//Name of the index in the local mongo:
superLongNameField1_1_superLongNameField2_1_superLongNameField3_1_superLongNameField4_1_superLongNameField5_1

//Error tring to run mongodb-memory-server
MongoError: namespace name generated from index name "87075582-17b6-4b9c-8589-82e3a8c9a834.$superLongNameField1_1_superLongNameField2_1_superLongNameField3_1_superLongNameField4_1_superLongNameField5_1" is too long (127 byte max)
```

## Do you know *why* it happenes?

A prefix is being added to the name of the index. That is the root cause of the issue. I can not create a name for this index because it is already being used in production. I belive, the prefix should not be added to the name of the indexes, just like it happens in the local mongo instance.

**Comment by hasezoey** [comment]
this is not an issue with this package, this package doesn't modify the behavior / calls from mongod / mongodb

what version is your "local mongo instance" and what version is the package using?, if you use default, try changing version to `4.0.20` (latest for 4.0) or to `4.2.10`
