### ISSUE TITLE
The Jest example in README does not work

### ISSUE THREAD

**Issue by songguoqiang** [nodkz/mongodb-memory-server#42]
I tried out the Jest example in the README and it does not work. When I ran some test, there are some error message saying "failed to connect on first connect".

The problem is at this line

```
mongoose.connect(mongoUri, opts, (err) => {
    if (err) console.error(err);
  });
```

Since `mongoose.connect()` returns a promise, we need to call it with `await` such that the call only returns when the connection is done. 

So it should be something like

```
await mongoose.connect(mongoUri, opts, (err) => {
    if (err) console.error(err);
  });
```

**Comment by nodkz** [comment]
Thanks for catching this! 👌
Wanna make a PR for your fix?

**Comment by songguoqiang** [comment]
Pavel, Sorry, I didn't respond in time. And thanks for fixing it!

Gordon
