### ISSUE TITLE
Is it possible to support arm64 (Apple Silicon) downloads without additional config

### ISSUE THREAD

**Issue by maxpeterson** [nodkz/mongodb-memory-server#422]
## Versions

- NodeJS: v15.3.0
- mongodb-memory-server: 6.9.2
- mongodb: 4.0.14
- mongoose: 5.10.19
- system: MacOS 11.0.1  ( Apple M1  / arm64 )

package: mongo-memory-server

## What is your question?

Would it be possible for `MongoMemoryServer` to handle the Apple M1  / `arm64` architecture without additional configuration. It seems likely that anyone using `arm64` will require the `x64` mongod  binary until there is a `arm64` one available.

### Background 

Trying to run tests with `MongoMemoryServer` on Apple M1  / arm64 resulted in the following error:

> unsupported architecture, ia32 and x64 are the only valid options

I was able to resolve the issue using the `MONGOMS_ARCH`  environment variable

```
env MONGOMS_ARCH=x64 npn run test
```

Thanks for creating a fantastic library!

**Comment by hasezoey** [comment]
currently we check only for these 2 supported architectures, because mongodb dosnt provide many arm(64) packages (at least when i last viewed)

**Comment by amirjani** [comment]
@maxpeterson my problem doesn't solve with ```env MONGOMS_ARCH=x64 npn run test```? 
how do you solve the problem exactly?

**Comment by maxpeterson** [comment]
> @maxpeterson my problem doesn't solve with `env MONGOMS_ARCH=x64 npn run test`?
> how do you solve the problem exactly?

@amirjani What if you try the `MONGOMS_DOWNLOAD_URL ` env vars outlined in https://github.com/nodkz/mongodb-memory-server#configuring-which-mongod-binary-to-use - pointed to an x64 / ios path.

If that fails you could try manually downloading the binary and copying it to the `node_modules/.cache/mongodb-memory-server/mongodb-binaries/4.0.14/mongod`

**Comment by amirjani** [comment]
> > @maxpeterson my problem doesn't solve with `env MONGOMS_ARCH=x64 npn run test`?
> > how do you solve the problem exactly?
> 
> @amirjani What if you try the `MONGOMS_DOWNLOAD_URL ` env vars outlined in https://github.com/nodkz/mongodb-memory-server#configuring-which-mongod-binary-to-use - pointed to an x64 / ios path.
> 
> If that fails you could try manually downloading the binary and copying it to the `node_modules/.cache/mongodb-memory-server/mongodb-binaries/4.0.14/mongod`

Thanks for your help 

we could fix this with below too: 
```javascript
"config": {
    "mongodbMemoryServer": {
	"systemBinary": "/opt/homebrew/bin/mongod",
	"arch": "x64",
	"disablePostinstall": "1",
	"version": "4.4.2", // whatever version you want 
	"debug": "0"
   }
}
```

**Comment by bimusiek** [comment]
Hey, just wanted to say thank you. 
The workaround with `env MONGOMS_ARCH=x64` works on our MacMini M1 CI server as well as on MBP 13 M1. 
It downloads x64 mongo and runs it via Rosetta 2. Great fix until SpiderMonkey  produces ARM version and Mongo updates it.

**Comment by JStonevalley** [comment]
Hi
What about arm64 for ubuntu 20.04, it looks like mongodb procide a binary for that: https://docs.mongodb.com/manual/administration/production-notes/#arm64

**Comment by hasezoey** [comment]
@JStonevalley thanks, #443 
this issue here is about mac arm64, so i created one to track your suggestion

**Comment by JStonevalley** [comment]
> @JStonevalley thanks, #443
> this issue here is about mac arm64, so i created one to track your suggestion

Thank you!

**Comment by hasezoey** [comment]
this should be automatically translated in `7.0.0-beta.22`, could someone test?

**Comment by maxpeterson** [comment]
> this should be automatically translated in `7.0.0-beta.22`, could someone test?

I have tested `7.0.0-beta.22` on Apple M1 / arm64 and the correct `mongod` binary is downloaded during `npm install` 😄 

```
node_modules/.cache/mongodb-memory-server/mongodb-binaries/4.0.20/mongod --version
db version v4.0.20
git version: e2416422da84a0b63cde2397d60b521758b56d1b
allocator: system
modules: none
build environment:
    distarch: x86_64
```

After some minor compatibility tweaks (from version `6.9.2`) my test pass.

**Comment by hasezoey** [comment]
thanks for testing @maxpeterson

closing because fixed in `7.0.0-beta.22`

**Comment by arjunreddyk** [comment]
> ## Versions
> * NodeJS: v15.3.0
> * mongodb-memory-server: 6.9.2
> * mongodb: 4.0.14
> * mongoose: 5.10.19
> * system: MacOS 11.0.1  ( Apple M1  / arm64 )
> 
> package: mongo-memory-server
> 
> ## What is your question?
> Would it be possible for `MongoMemoryServer` to handle the Apple M1 / `arm64` architecture without additional configuration. It seems likely that anyone using `arm64` will require the `x64` mongod binary until there is a `arm64` one available.
> 
> ### Background
> Trying to run tests with `MongoMemoryServer` on Apple M1 / arm64 resulted in the following error:
> 
> > unsupported architecture, ia32 and x64 are the only valid options
> 
> I was able to resolve the issue using the `MONGOMS_ARCH` environment variable
> 
> ```
> env MONGOMS_ARCH=x64 npn run test
> ```
> 
> Thanks for creating a fantastic library!

Please fix the typo npn 
`env MONGOMS_ARCH=x64 npm run test`

**Comment by rgomide** [comment]
Hi, I could run locally with apple M1 using the command `env MONGOMS_ARCH=x64 npm run test`.
Now I'm trying to run test inside a docker container without success. 
My node image is: node:10.15.3

I tried to run with this environment variables:
- MONGOMS_ARCH=x64
or
- MONGOMS_DOWNLOAD_URL=https://fastdl.mongodb.org/osx/mongodb-macos-x86_64-4.4.6.tgz
I also tried others URLs.

With this settings, I'm having this error:

> Instance Exited before being ready and without throwing an error!
> 
>       at MongoInstance.once (../node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:273:13)
>       at MongoInstance.closeHandler (../node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:454:10)

**Comment by hasezoey** [comment]
> Hi, I could run locally with apple M1 using the command env MONGOMS_ARCH=x64 npm run test.

since MMS 7.0.0, macos arm64 is automatically translated to download the x64 version (from what i know, arm64 builds still dont exist)

> I tried to run with this environment variables:

how do you try to run these in the docker container?

---

also important to note is, if the binary already exists, it will **not** be re-downloaded (if its the same version & same (end result) arch & same system)

if you continue to have this problem, please open a new issue with all required information or open a discussion or ask on our discord

**Comment by awlevin** [comment]
Took me a bit to find the relevant download page so posting here to hopefully save the next fellas some time: https://www.mongodb.com/download-center/community/releases/archive
