### ISSUE TITLE
unique index bug

### ISSUE THREAD

**Issue by ehsan2003** [nodkz/mongodb-memory-server#436]
## Versions

- NodeJS: 15.3.0
- mongodb-memory-server-*: 0.0.0
- mongodb: 6.9.3
- mongoose: 5.11.8 
- system:Linux ubuntu 20.10 

package: mongo-memory-server 

### unique indexes not working properly:
when a duplication error occurs on a real mongodb instance it throws an error with 'keyPattern' property which indicates which properties are conflicting
but in the mongodb-memory-server the error objects doesn't contain that key ('keyPattern') and the error message doesn't contain that too.
 it is some thing like : 
```
E11000 duplicate key error dup key: { : 'test', :10 }
```

## Code Example
it is happening when inserting a document on mongodb

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment]
not an problem with this package, this package dosnt modify the mongod instance - it is just managing the start & stop (& download)

ask this in mongodb / mongodb driver / mongoose repositories
