### ISSUE TITLE
Postinstall and index scripts assume that `mongodb-memory-server-core` is a sibling in `node_modules`

### ISSUE THREAD

**Issue by mhassan1** [nodkz/mongodb-memory-server#438]
## Versions

- NodeJS: 14.15.1
- mongodb-memory-server-*: 6.9.3
- mongodb: 4.4.1
- mongoose: 5.11.15
- system: MacOS

package: `mongodb-memory-server` (and `-global` packages with `postinstall.js` scripts)

## What is the Problem?

The `postinstall.js` script looks for `mongodb-memory-server-core` in a sibling directory: https://github.com/nodkz/mongodb-memory-server/blob/2bc51280ec91ac8558c2aa49d3995d0d499f3620/packages/mongodb-memory-server/postinstall.js#L21
In some cases, it may not be there:
- hoisting puts the packages at different levels of `node_modules`
- Yarn Plug'n'Play doesn't use `node_modules` at all

## Code Example

```ts
// instead of
if (!isModuleExists('../mongodb-memory-server-core/lib/util/resolve-config')) {}

// do
if (!isModuleExists('mongodb-memory-server-core/lib/util/resolve-config')) {}
```

## Do you know *why* it happenes?

In the case of Yarn Plug'n'Play, it happens because `mongodb-memory-server-core` is kept as a tarball and is mounted to a read-only file system. `../mongodb-memory-server-core` in `mongodb-memory-server` does not point to `mongodb-memory-server-core`, and so the postinstall logs `Could not resolve postinstall configuration` and exits.

**Comment by hasezoey** [comment]
this is for in monorepo execution, because otherwise it wouldnt be able to find the other files, and in some install cases, it wont work in the non-relative form - if it causes problems, use the `-core` package directly and runtime download the binary

**Comment by mhassan1** [comment]
Interesting. What is an example of an install case where using the non-relative form will not work?

**Comment by hasezoey** [comment]
i once tried to change it to non-relative, but it didnt work, but i cant quite remember the exact reason, maybe the code / build process changed enough that it would be possible to change it

**Comment by mhassan1** [comment]
I can't imagine why that would be a problem. Since `mongodb-memory-server` and `mongodb-memory-server-core` are separate packages and `core` is a dependency, the postinstall script should refer to `core` like it would any other dependency. Is there a way we can verify whether this is a safe fix to make?

**Comment by hasezoey** [comment]
> Is there a way we can verify whether this is a safe fix to make?

not really aside from manually installing it into an bare project?

> I can't imagine why that would be a problem

i kind remember the problem now, when running `yarn install` to install all the packages in the monorepo, it would try to execute the postinstalls, and would fail because it could not find the core package installed (thats why relative)

**Comment by mhassan1** [comment]
When you say "monorepo," you're talking about this `mongodb-memory-server` monorepo, correct?

That doesn't seem to be a problem. I just cloned this monorepo, modified the `postinstall.js` to use the module path, and ran `yarn install` in the root. It does fail initially because the `build` step for `mongodb-memory-server-core` happens in a `postinstall` step, but that happens regardless of whether I use a module path or a relative path. If I run `yarn install` again, the `postinstall` step runs without issue.

I'd be happy to offer a pull request, if that would help move forward.

**Comment by hasezoey** [comment]
> I'd be happy to offer a pull request, if that would help move forward.

yes you can try, please make the base branch `beta` for now

**Comment by mhassan1** [comment]
PR for beta [here](https://github.com/nodkz/mongodb-memory-server/pull/444)

**Comment by hasezoey** [comment]
i could confirm that installing `v7.0.0-beta.19` installs successfully in an new project and all dependencies get resolved
