### ISSUE TITLE
tslib is missing from non-core dependencies

### ISSUE THREAD

**Issue by mhassan1** [nodkz/mongodb-memory-server#445]
## Versions

- NodeJS: 14.15.1
- mongodb-memory-server-*: 7.0.0-beta.18
- mongodb: 4.4.1
- system: MacOS

package: `mongodb-memory-server` (and `-global*`)

## What is the Problem?

`mongodb-memory-server`, `mongodb-memory-server-global`, and friends use `tslib` in their `index.js` files; however, `tslib` is not included as a dependency of those packages. In a scenario where there is no dependency hoisting (e.g. Yarn Plug'n'Play), users will get an error like:
```txt
mongodb-memory-server tried to access tslib, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: tslib (via "tslib")
Required by: mongodb-memory-server@npm:7.0.0-beta.18
```

## Code Example

1. Create an empty project with Yarn v2 Plug'n'Play
2. Add `mongodb-memory-server-global` as a dependency
3. Create a file with `require('mongodb-memory-server-global')`

## Do you know *why* it happenes?

When dependency hoisting is disabled or doesn't exist (e.g. Yarn Plug'n'Play), each package must strictly declare all dependencies in its `package.json`; in this case, there is no guarantee that `tslib` will be available to `mongodb-memory-server-global`, since it hasn't been declared in its dependencies, and, without hoisting, we can't rely on the fact that it is a dependency of `mongodb-memory-server-core`.

**Comment by hasezoey** [comment]
could you confirm that `v7.0.0-beta.19` work with YPnP?

**Comment by mhassan1** [comment]
It works, thanks!
