### ISSUE TITLE
Default mongo version (4.0.14) not available for download anymore

### ISSUE THREAD

**Issue by Systerr** [nodkz/mongodb-memory-server#448]
## Versions

- NodeJS: 14.15.0
- mongodb-memory-server-*: 6.9.3
- mongodb: 4.0.14 (project default)
- mongoose: 0.0.0 
- system: gitlab-ci (node:14-buster)

package: mongo-memory-server 

## What is the Problem?

> mongodb-memory-server@6.9.3 postinstall /node_modules/mongodb-memory-server
> node ./postinstall.js
mongodb-memory-server: checking MongoDB binaries cache...
failed to download/install MongoDB binaries. The error: Error: Status Code is 403 (MongoDB's 404)
This means that the requested version-platform combination doesn't exist
  Used Url: "https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian10-4.0.14.tgz"

## Code Example

```bash
npm i mongodb-memory-server
```

## Do you know *why* it happenes?

Looks like version 4.0.14 removed from CDN. Default version  (4.0.14) should be updated.

I solved it in my case by setting config into npm. But default installation should works also.

**Comment by hasezoey** [comment]
already fixed in beta

**Comment by hasezoey** [comment]
i took a deeper look at it now, it seems like nothing below `4.2` is available for `debian10`, so for everything below, `debian92` should be used

workaround for now should be to use `MONGOMS_VERSION=v4.2-latest`
