### ISSUE TITLE
Replicaset cannot binding to all IP addresses

### ISSUE THREAD

**Issue by reinaldo-calderon-team** [nodkz/mongodb-memory-server#450]
## Versions

- NodeJS: v11.15.0
- mongodb-memory-server-*: 6.9.3
- system: docker - ubuntu:bionic 

package: mongo-memory-server 

## What is the Problem?

Cannot create a **replicaset** for binding to all IP addresses,  pick up the service but only use the address 127.0.0.1

## Code Example

```ts
const mongo = require('mongodb-memory-server-core');

replicaConfig = {
  binary: {},
  instanceOpts: [{ port: 9879, ip: '0.0.0.0' }],
  replSet: {
    auth: false,
    name: 'rs0',
    count: 1,
    dbName: 'overwatch',
    oplogSize: 1,
    storageEngine: 'ephemeralForTest',
  },
};

const mongodb = new mongo.MongoMemoryReplSet(replicaConfig);
```

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment]
could you provide more information on what the problem is, like the error and [debug output](https://github.com/nodkz/mongodb-memory-server#enable-debug-mode)?

**Comment by reinaldo-calderon-team** [comment]
@hasezoey , Outside of localhost, I cannot establish a connection with the database

when printing the _MongoMemoryReplSet_ object, 
the output always shows that it is listening exclusively for the **ip: '127.0.0.1'** 


### The  Code
```ts
const mongo = require('mongodb-memory-server-core');

replicaConfig = {
  binary: {},
  instanceOpts: [{ port: 9879, ip: '0.0.0.0' }],
  replSet: {
    auth: false,
    name: 'rs0',
    count: 1,
    dbName: 'overwatch',
    oplogSize: 1,
    storageEngine: 'ephemeralForTest',
  },
};

const mongodb = new `mongo.MongoMemoryReplSet(replicaConfig);`
await mongodb.waitUntilRunning();
console.info(mongodb);
```

### The  Output
```ts
MongoMemoryReplSet {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  servers:
   [ MongoMemoryServer {
       runningInstance: [Promise],
       instanceInfoSync: [Object],
       opts: [Object] } ],
  _state: 'running',
  opts:
   { binary: {},
     instanceOpts: [ [Object] ],
     replSet:
      { auth: false,
        args: [Array],
        name: 'rs0',
        count: 1,
        dbName: 'overwatch',
        ip: '127.0.0.1',
        oplogSize: 1,
        spawn: [Object],
        storageEngine: 'ephemeralForTest',
        configSettings: {} } } }
```

**Comment by hasezoey** [comment]
did you also check the actual logging from the instances?

sorry if the options are confusing, `instanceOpts` are used for *specific instances* which overwrite the options from `replSet`, and `replSet` options are used for generic spin-up
why: you can specify `replSet.count`, which will first spin up the length of `instanceOpts`, and if the count is not reached, will spin up generic ones with the options of `replSet` until `replSet.count` is reached (means if `instanceOpts.length` is higher than `replset.count`, no more generic instances are started)

and the default for `replSet.ip` is `127.0.0.1`

did you also already try the `7.0.0-beta`? 

PS: what you provided is not the debug output, please enable debug logging and provide the full console output
