### ISSUE TITLE
bug: don't use exact version of the packages

### ISSUE THREAD

**Issue by ruscon** [nodkz/mongodb-memory-server#453]
## What is the Problem?

Since this is a library (and not a final service / platform), then it is advisable to indicate the versions of packages with a tilde(~) or caret(^) in package.json

Otherwise, the project has a large dependency tree than it could be

## Code Example

```bash
❯ npm ls mongodb
├── mongodb@3.6.4
└─┬ mongodb-memory-server@6.9.3
  └─┬ mongodb-memory-server-core@6.9.3
    └── mongodb@3.6.2
```

**Comment by hasezoey** [comment]
known, and fixed in `beta` already - will be changed in an 6.x release also
