### ISSUE TITLE
Finals for 7.0.0

### ISSUE THREAD

**Issue by hasezoey** [nodkz/mongodb-memory-server#456]
- [x] Look through the code for cleanup
- [ ] Ease transition by deprecating & adding new functions to 6.x [optional]
- [x] Add More Tests
- [x] Extend Documentation (Migration Guide)

**Comment by little-shippy** [comment]
@hasezoey any progress updates on version 7.0.0?

**Comment by hasezoey** [comment]
@little-shippy yes, it looks like its pretty stable, so it might be released soon(tm), but i still dont know about #442, well it can be done later

**Comment by little-shippy** [comment]
@hasezoey that's awesome news! It'd be great to see 7.0.0 released soon as my team has recently switched over to the M1 chip Macs and we're forced to use `run-rs` until 7.0.0 is released.

**Comment by hasezoey** [comment]
Version `7.0.0-beta.49` can be considered an Release-Candidate, if nothing comes up (and i dont forget it), version `7.0.0` will be released on 1.7.2021 (d/m/y)

**Comment by hasezoey** [comment]
With 3624253f509a54cff04997943894b9eb7e7e64fe, the version `7.0.0` is now fully released

- [Github Version](https://github.com/nodkz/mongodb-memory-server/releases/tag/v7.0.0)
- [Changelog](https://github.com/nodkz/mongodb-memory-server/blob/master/CHANGELOG.md#700-2021-07-01)
- [Migration Guide](https://nodkz.github.io/mongodb-memory-server/docs/guides/migrate7)

PS: it seems like automated release didnt work the first time, so it released `6.10.0`, dont use that version (i cannot remove it currently) (https://github.com/nodkz/mongodb-memory-server/issues/491)

**Comment by nodkz** [comment]
@hasezoey Amazing changes! 👍
My congratulations 🎉🎉🎉
It was really really very impressive changes! Changelog is 🤯🤯🤯🤯

PS. I've just made a deprecation for version 6.10.0 (some packages were unpublished, others were deprecated).
