### ISSUE TITLE
Attempting to getUri() returns error "instanceInfo" is undefined

### ISSUE THREAD

**Issue by cbryant24** [nodkz/mongodb-memory-server#457]
## Versions

- NodeJS: v15.10.0
- mongodb-memory-server-*: 7.0.0-beta.26
- mongodb: 4.0.20
- mongoose: 5.11.19
- system: MacOS Big Sur Apple M1

package: mongo-memory-server 

## What is the Problem?

I Run `npm run test` and the test throws an error when invoking `await mongoServer.getUri()` stating the `"instanceInfo" 
is undefined`

<img width="861" alt="Screen Shot 2021-03-10 at 12 37 29 PM" src="https://user-images.githubusercontent.com/29960336/110694407-63d9d180-819d-11eb-8e4d-d4bf9725f580.png">

## Code Example

This repo can also be cloned and run to reproduce the problem if using an apple macbook with an m1 chip 
https://github.com/cbryant24/mongo-memory-server

```ts
import mongoose from "mongoose";
import { MongoMemoryServer } from "mongodb-memory-server";

// May require additional time for downloading MongoDB binaries
jasmine.DEFAULT_TIMEOUT_INTERVAL = 600000;

let mongoServer: any;

beforeAll(async () => {
  mongoServer = new MongoMemoryServer();
  const mongoUri = await mongoServer.getUri();
  await mongoose.connect(mongoUri, (err) => {
    if (err) console.error(err);
  });
});

afterAll(async () => {
  await mongoose.disconnect();
  await mongoServer.stop();
});
```

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment]
sorry, if you didnt read the changelog, you wouldnt know - there is no migration guide *yet*

`getUri` (on all classes) is now sync, not an promise anymore, an instance needs to be manually started with `.start` or directly with `.create`
