### ISSUE TITLE
Feature: fetch mongodb on package install

### ISSUE THREAD

**Issue by wingedfox** [nodkz/mongodb-memory-server#46]
I've noticed substantial delay in e2e tests due to on-demand mongodb server download.
On the other hand, on-demand download makes testing without internet access almost impossible because we've to mock 3rd-party infrastructure.

It worth to provide a way to have mongodb server as a part of this npm package or add some optional npm dependency (separate package) to take server from.

**Comment by nodkz** [comment]
Feel free to create `mongodb-memory-server-offline` package and add it as `optionalDependency`. Like it did here https://github.com/graphql-compose/graphql-compose-mongoose/blob/30968a23a40d0bdbf90621984e189439eec13711/src/composeWithMongoose.js#L240-L245 with optional package `graphql-compose-pagination`.

**Comment by nodkz** [comment]
Or maybe need to find another solution on your side. Cause `mongodb-memory-server-offline` will be very FAT package if you will add all supported mongodb versions.

Try to add some options which will instruct where to take mongodb bineries offline from your repo. It will be more right way.

**Comment by wingedfox** [comment]
mongo-memory-server-offline package could fetch server during install phase, which will work for virtually everything, except automatic updates. This way package won't be that fat.

**Comment by nodkz** [comment]
And how it decide which version of mongodb binaries need to install? 3.4, 3.6

**Comment by wingedfox** [comment]
There are 2 options:
1. provide a release for each mongo build
2. provide (cli?) interface to fetch necessary build right from dependent npm script using pre-install hook

**Comment by nodkz** [comment]
Ok, let take 1st case. But rename packages something like:
- mongo-memory-server-download-3.4
- mongo-memory-server-download-3.6

Where this packages at pre-install will download needed mongo binary to `path.resolve(os.homedir(), '.mongodb-binaries')` folder.

**Comment by wingedfox** [comment]
As long as you won't have 2 different versions for any package given it's OK to use `path.resolve(os.homedir(), '.mongodb-binaries',version)` and reference correct one from `mongo-memory-server`.

**Comment by masudianpour** [comment]
Any update on this issue?

**Comment by nodkz** [comment]
By default `mongodb-memory-server` package installs `latest` version of `mongod` in postscripts.
If you want a specific version, you should provide it in your test files with proper timeout for test-runner.

Or you may add some script to your package.json which will execute after package installation:
```js
{
  "scripts": {
    "postinstall": "node ./postinstall.js", 
  }
}
```
Like it did in this file https://github.com/nodkz/mongodb-memory-server/blob/master/postinstall.js

**Comment by stilllife00** [comment]
@nodkz I manage to install a specific mongo version at postinstall as you suggest, the problem is that the cache is not retained. AFAIU the mongobinary that runs at postinstall is different from the one that runs during a test suite run, and it tries to re-download the binary in the same folder where the binary already is. Can you suggest a workaround for this? It is pointless to install a binary if the test suite installs it again. Also can the local cache of MongoBinary check for the existance of a certain folder instead of looking up on the internal cache property ?
