### ISSUE TITLE
Multiple databases with single memory server instance

### ISSUE THREAD

**Issue by criskurtin** [nodkz/mongodb-memory-server#461]
## Versions

- NodeJS: 14.15.4
- mongodb-memory-server-*: 6.9.6
- mongodb: 4.0.10
- mongoose: 5.11.12
- system: Linux (Pop OS 20.04)
package: mongo-memory-server

## What is your question?

Is there currently a way to create an instance of `MongoMemoryServer` with multiple named databases? The project I'm working on uses a base `MONGO_URL` to create 3 connections in total, each connecting to a different db (dbNames are already dynamically appended from env vars in a connection function).
The idea would be to create a single instance with these 3 databases (dbNames can be pulled from the same env vars that source uses), replace the `MONGO_URL` env var with memory server's base URL and allow the connection function (which uses mongoose) to create connections without any modifications to the code (still generating full connection strings dynamically from env vars). 
If we do this, we would be able to execute our API integration tests faster by instantiating a memory server during the jest setup phase.

**Comment by hasezoey** [comment]
please consult the mongodb (or mongoose) documentation for this
this package provides an full mongodb instance, which can be connected to normally, and the most common use case url is generated by `.getUri`, the first parameter in `getUri` can be used to overwrite which db is used (`mongodb://host:port/dbwillbereplaced`
