### ISSUE TITLE
Mongoose Cursor Issue

### ISSUE THREAD

**Issue by psychonetic** [nodkz/mongodb-memory-server#463]
## Versions

- NodeJS: v15.13.0
- mongodb-memory-server-*: 6.9.3
- mongoose: 5.12.2 
- system: MacOS Catalina 10.15.7

package: mongo-memory-server 

## What is the Problem?
Using mongoose cursor functionality does not seem to work.

error: Unhandled error. (MongooseError: Operation `user.find()` buffering timed out after 10000ms
    at Timeout.<anonymous> (***/mongoose/lib/drivers/node-mongodb-native/collection.js:185:20)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7))

Also when using cursor() + eachAsync does not seem to work.
    
When using the code example below, the code works as expected.

## Code Example

```ts
for await (const user of User.find({})) {
      console.log(user);
}
```

## Do you know *why* it happenes?

*no*

**Comment by wizlif** [comment]
@psychonetic How did you fix this ?
