### ISSUE TITLE
Can this package be used in replacement of redis ?

### ISSUE THREAD

**Issue by ceessay** [nodkz/mongodb-memory-server#465]
## Versions

- NodeJS: 0.0.0
- mongodb-memory-server-*: 0.0.0
- mongodb: 0.0.0
- mongoose: 0.0.0 
- system: 

package: mongo-memory-server 

## What is your question?

I have to process large set of arrays coming from MongoDb atlas. I use json files to store temporary results of my processing. I would like to know if I could use mongo-memory-server instead of redis to store my temporary  results

**Comment by hasezoey** [comment]
this package here (`mongodb-memory-server-core`) only does download & manage an `mongod` (mongodb) instance, it will definitely be slower than redis (redis is built with in-memory in mind, mongodb not)

it like manually starting an local instance of `mongod` along side your project, you need to decide yourself if mongodb is right for this job
