### ISSUE TITLE
Mongo memory server will not stay connected

### ISSUE THREAD

**Issue by code4fun907** [nodkz/mongodb-memory-server#475]
## Versions

- NodeJS: 14.17.0
- mongodb-memory-server-*: 6.9.6
- mongodb: none
- mongoose: 5.10.19 
- system: Windows

package: mongo-memory-server

## What is your question?

Im having some real trouble running mongodb memory server on my machine. because Ive already wrote out this question on stackoverflow a few days ago and it still after being seen by almost 50 people remains unsolved I thought I would come here. here is the link to that specific stackoverflow question https://stackoverflow.com/questions/67699988/mongo-memory-server-is-not-starting-at-all

(first time making a github issue so if I did anything wrong im sorry!)

**Comment by hasezoey** [comment]
> (first time making a github issue so if I did anything wrong im sorry!)

next time, please include the full question instead of just an link to stackoverflow

PS: if it really is just an question, then posting it in discussions is better (will move if it comes to this)

**Comment by hasezoey** [comment]
btw, did you already test an `7.0.0-beta.x` version?

**Comment by hasezoey** [comment]
i looked at the stackoverflow issue, where in the comments it was suggested it was an permissions error, but from what i can tell:
- the binary is installed correctly
- the temporary folder is created and can be used

but i also saw that the instance is exiting with code `3221225781` and no extra error logs, but from searching, it seems like this is related to missing libraries (but without error logs, i dont know what libraries are missing)

please try if the same behavior is on `7.0.0-beta.x` (the latest beta please) and post the full debug log
Note: 7.0.0 has breaking changes and [the migration guide can be found here](https://nodkz.github.io/mongodb-memory-server/docs/guides/migrate7) (it includes the most important changes)

**Comment by code4fun907** [comment]
alright I will try this `7.0.0-beta.x` version now and come back with results if it works, also thanks for the advice about haha I just did not want to rewrite the entire thing

**Comment by hasezoey** [comment]
> also thanks for the advice about haha I just did not want to rewrite the entire thing

if the stackoverflow question is formatted correctly, it is basically an copy-paste into here (in the section `What is your question?`) and still filling out the `Versions` section

**Comment by eric-burel** [comment]
It seems to be related to using Windows, we have the same problem on a windows machine as well.

**Comment by hasezoey** [comment]
@eric-burel did you already try the beta like mentioned earlier in this issue? and if you hit the same error, could you provide the full debug log in the beta?

**Comment by eric-burel** [comment]
We're on it I'll keep you informed on the result, thanks! It's an open source project so if it still doesn't work I'll share a repro.

**Comment by Timi-Duban** [comment]
As it was said, we have the same problem here using a windows machine.
I tried the beta (version 7.0.0-beta43), and still hit the error.

Here's the full debug log triggered by MongoMemoryServer.create()
![image](https://user-images.githubusercontent.com/55442526/121175613-8bebd600-c85b-11eb-866e-c1075223f671.png)
![image](https://user-images.githubusercontent.com/55442526/121175640-97d79800-c85b-11eb-877f-76deda3778a7.png)

**Comment by hasezoey** [comment]
@Timi-Duban could you try manually running the downloaded binary and see if its the same error? (it seems to be in `./node_modules/.cache/mongodb-memory-server/`)

**Comment by Timi-Duban** [comment]
Okay ! After trying to run the binary file, windows told me that VCRUNTIME140.dll and MSVCP140.dll were missing.
I downloaded "Visual C++ Redistribuable for Visual Studio" and now mongo-memory-server works as expected. Thank you for your help on this :)

**Comment by hasezoey** [comment]
@Timi-Duban thanks, so the issue seems to be not from mongodb directly, but from how this are spawned on windows (or undocumented exit codes)

>  No need install v7.0.0 for it, it works even on the 6.

v7 has better logging (way more) and is an major refactor, so this is the best way to get how this package is operating (based on log), so it was helpful at least for debugging this issue
