### ISSUE TITLE
3.6.2

### ISSUE THREAD

**Issue by mathieug** [nodkz/mongodb-memory-server#48]
Download of MongoDB version 3.6.2 does not work.
Here is the generated link from the package: `https://downloads.mongodb.org/osx/mongodb-osx-x86_64-3.6.2.tgz`
There is only a ssl version on downloads.mongodb.org, so the link is https://downloads.mongodb.org/osx/mongodb-osx-ssl-x86_64-3.6.2.tgz.

Should I make a PR which tests if the wanted version is > 3.6 and add `-ssl-` in `name` (https://github.com/nodkz/mongodb-memory-server/blob/master/src/util/MongoBinaryDownloadUrl.js#L39) ?

**Comment by mathieug** [comment]
I tried with #49 but it needs to be tested

**Comment by nodkz** [comment]
Just published https://github.com/nodkz/mongodb-memory-server/releases
