### ISSUE TITLE
$and syntax not supported in unit test using memory-server but works in production

### ISSUE THREAD

**Issue by soupfable** [nodkz/mongodb-memory-server#488]
## Versions

- NodeJS: 14.17 and 10.16
- mongodb-memory-server-*: 6.9.6
- mongodb(the binary version): 3.6.6
- system:  MacOS

package: mongo-memory-server

## What is the Problem?

Query syntax issue : unknown operator $and

THIS WORKS :       
        
```
   $and : [ {"milestones.completed": {  $lte: thirtyDaysAgo } },  
                    { "milestones.completed": {  $gte: thirtyOneDaysAgo } } ]
```

THIS DOES NOT WORK :  
 
` 'milestones.completed': { $and: [{ $lte: thirtyDaysAgo }, { $gte: thirtyOneDaysAgo }] }`

## Error

```
  MongoError: unknown operator: $and

      at MessageStream.messageHandler (node_modules/mongodb/lib/cmap/connection.js:272:20)
      at processIncomingData (node_modules/mongodb/lib/cmap/message_stream.js:144:12)
      at MessageStream._write (node_modules/mongodb/lib/cmap/message_stream.js:42:5)
```

**Comment by hasezoey** [comment]
This is not an problem with this package

and from what i know, the operator `$and` can only be used on the top-level of the query (which the first example is, and the second not)

**Comment by nhuanhoangduc** [comment]
@soupfable Wrong syntax:
```
'milestones.completed': { $and: [{ $lte: thirtyDaysAgo }, { $gte: thirtyOneDaysAgo }] }
```
Correct syntax:
```
{ $and: [ { <expression1> }, { <expression2> } , ... , { <expressionN> } ] }
```
