### ISSUE TITLE
Version "6.10.0" got accidentally released

### ISSUE THREAD

**Issue by hasezoey** [nodkz/mongodb-memory-server#491]
Version `6.10.0` got accidentally released by an mis-configured semantic-release, please dont use that version

(i cannot change it at the moment, because i dont have the rights on the npm package)

**Comment by nodkz** [comment]
I've just made a deprecation for version 6.10.0 (some packages were unpublished, others were deprecated).

**Comment by hasezoey** [comment]
closing, because it got resolved, but i will still keep it pinned until the pinned space is needed or some time (like maybe a year) has passed

**Comment by PeterTrotter** [comment]
Worth noting that a `yarn upgrade` will still grab `6.10.0` when configured for `~6.9.x`

**Comment by hasezoey** [comment]
@PeterTrotter from what i know, `yarn` (and its registry) dont have the concept of "deprecated", which makes it kinda difficult

btw, if you have it configured for the `~6.9.x` range, and dont use `--latest`, it should not actually upgrade to 6.10, did you update the lockfile after having changed the range to that too?

**Comment by PeterTrotter** [comment]
@hasezoey eurgh, my bad - I had meant to write `^6.9.x` which is the expected behaviour.

I've changed it to `~` and it's all good. I was sort of adding a message as note for others that might make the same mistake.

Thanks!
