### ISSUE TITLE
dbName not present in connection string for replica sets

### ISSUE THREAD

**Issue by apendua** [nodkz/mongodb-memory-server#492]
## Versions

- NodeJS: 12.22.1
- mongodb-memory-server-*: 7.0.0
- mongodb(the binary version): 4.2.0
- system: MacOS

package: mongo-memory-server

## What is the Problem?

It seems like in `7.x` release, `options.replSet.dbName` is no longer included in the result of `.getUri()`. Is this intentional?

## Code Example

```ts
const mongoServer = new MongoMemoryReplSet({
  replSet: {
    dbName: 'test',
    storageEngine: 'wiredTiger',
  },
  binary: {
    version: '4.2.0',
  },
  autoStart: false,
});
await mongoServer.start();
await mongoServer.getUri(); // <- this doesn't include dbName
```

## Do you know *why* it happenes?

In versions prior to `7.x` this wasn't the case. This is clearly a breaking change but I don't think it was mentioned in the documentation anywhere but maybe I am missing something.

**Comment by hasezoey** [comment]
> Is this intentional?

yes it is
see 
- https://github.com/nodkz/mongodb-memory-server/issues/141#issuecomment-863312675
- https://github.com/nodkz/mongodb-memory-server/blob/3624253f509a54cff04997943894b9eb7e7e64fe/packages/mongodb-memory-server-core/src/util/utils.ts#L13-L17

dbName can still be passed as an parameter

**Comment by apendua** [comment]
@hasezoey Wow! That was quick. Thank for for a prompt action.

Regarding your comment here:

> it seems the URI format slightly differs between these two (with mongodb /db mean authentication database, and mongoose means default database for the connection & models)

I think you this statement can be supported by

https://docs.mongodb.com/manual/reference/connection-string/

However, that particular parameter also serves as the default connection database the same way it does for `mongoose`. I am not sure where this discrepancy between `mongoose` and "mongodb" is coming from. Isn't `mongoose` using the official driver behind the scenes anyway?

**Comment by hasezoey** [comment]
> Isn't mongoose using the official driver behind the scenes anyway?

it is, but you dont have to call `connection.useDb('yourdb')`, and authentication is handled by options (both in mongoose and mongodb, but mongodb still supports the "old way", being directly after `/` and before `?`)
