### ISSUE TITLE
new required version on previouses releases

### ISSUE THREAD

**Issue by mtti-g** [nodkz/mongodb-memory-server#500]
It seems as though all previous versions of `mongodb-memory-server` have a bumped version of node listed as required now. This is when attempting to install `@5.2.11` and `@6.9.2` (among a couple other versions I tried in between).
```bash
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for mongodb-memory-server@7.0.0: wanted: {"node":">=12.22.0"} (current: {"node":"12.19.0","npm":"6.14.8"})
npm ERR! notsup Not compatible with your version of node/npm: mongodb-memory-server@7.0.0
npm ERR! notsup Not compatible with your version of node/npm: mongodb-memory-server@7.0.0
npm ERR! notsup Required: {"node":">=12.22.0"}
npm ERR! notsup Actual:   {"npm":"6.14.8","node":"12.19.0"}
```
Notice how it is providing an error related to version 7, although that version is not in use.

Also, when testing this, only hard versions were applied. So it is not referencing `6.10` which was accidentally released.

A work around for now is removing `engine="strict"` from the `.npmrc`, but that is not ideal.

**Comment by hasezoey** [comment]
cannot reproduce
tested in an vm:

```ts
$ node -v
v10.24.1

$ npm -v
6.14.13

$ npm i -s mongodb-memory-server@6.x # no error
+ mongodb-memory-server@6.9.6

$ # done
```

**Comment by mtti-g** [comment]
Thanks for looking at it. I'll get more in depth testing steps to reproduce it some time today.

**Comment by mtti-g** [comment]
Looks like that was a red herring :P, another dependency is the problem:
```bash
$ node -v
v12.19.0

$ npm -v
6.14.8

$ echo engine-strict=true >> .npmrc
$ npm i -s @shelf/jest-mongodb
```

And you will receive this error:
```bash
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for mongodb-memory-server@7.0.0: wanted: {"node":">=12.22.0"} (current
: {"node":"12.19.0","npm":"6.14.8"})
npm ERR! notsup Not compatible with your version of node/npm: mongodb-memory-server@7.0.0
npm ERR! notsup Not compatible with your version of node/npm: mongodb-memory-server@7.0.0
npm ERR! notsup Required: {"node":">=12.22.0"}
npm ERR! notsup Actual:   {"npm":"6.14.8","node":"12.19.0"}
```
Sorry about the wild goose chase there. For those that also experience this, I'll link the issue here: https://github.com/shelfio/jest-mongodb/issues/285
