### ISSUE TITLE
Is unionWith stage supported?

### ISSUE THREAD

**Issue by radoslawsobies** [nodkz/mongodb-memory-server#504]
when i try to run a pipline with stage $unionWith, i get this error:
MongoError: Unrecognized pipeline stage name: '$unionWith'

mongo-momory-server v 7.2.0

**Comment by hasezoey** [comment]
what binary version are you using?

[documentation](https://docs.mongodb.com/manual/reference/operator/aggregation/unionWith/) states:
> New in version 4.4.

(Note: version `7.2.0` has an default version of `4.0.25`, because it is LTS)

**Comment by radoslawsobies** [comment]
is it possible to install mongo-memory-server with mongdb 4.4?

**Comment by radoslawsobies** [comment]
i found mongodb-memory-server-global-4.4
but when i run test i get error

Error: Instance Exited before being ready and without throwing an error!

    at MongoInstance.<anonymous> (C:\Users\rsobi\WebstormProjects\pub\zaplify\packages\campaign-service\node_modules\mongodb-memory-server-core\src\util\MongoInstance.ts:199:13)

there is no folder scr, in node_modules\mongodb-memory-server-core\

**Comment by hasezoey** [comment]
> is it possible to install mongo-memory-server with mongdb 4.4?

yes your can, you have 3 options
- use an environment variable (`MONGOMS_VERSION`)
- use an package.json config variable
- use the package `mongodb-memory-server-global-4.4`

[`VERSION` option documentation](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#version)
[how to use config options as package.json config variables](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#how-to-use-them-in-the-packagejson)
[how to use config options as env variables](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#how-to-use-them-as-environment-variables)

you will have to try different version things (depending on system), sometimes its with the `v` prefix, sometimes not, easiest version to test is `v4.4-latest`

**Comment by hasezoey** [comment]
> i found mongodb-memory-server-global-4.4
> but when i run test i get error
> 
> Error: Instance Exited before being ready and without throwing an error!
> 
> ```
> at MongoInstance.<anonymous> (C:\Users\rsobi\WebstormProjects\pub\zaplify\packages\campaign-service\node_modules\mongodb-memory-server-core\src\util\MongoInstance.ts:199:13)
> ```
> 
> there is no folder scr, in node_modules\mongodb-memory-server-core\

please provide [debug output](https://github.com/nodkz/mongodb-memory-server#enable-debug-mode) to help further

**Comment by radoslawsobies** [comment]
thank u for your assistance.
i soved it. it was due to mongo.exe crashed, i installed vc_redist_2015 and it started to work.

**Comment by hasezoey** [comment]
closing, because resolved

**Comment by tosiek88** [comment]
runing in docker
```

web_1  | 2021-08-13T18:03:22.926Z MongoMS:MongoInstance Mongo[39327]: start: Starting Processes
web_1  | 2021-08-13T18:03:22.926Z MongoMS:MongoInstance Mongo[39327]: _launchMongod: Launching Mongod Process
web_1  | 2021-08-13T18:03:22.926Z MongoMS:MongoInstance Mongo[39327]: prepareCommandArgs
web_1  | 2021-08-13T18:03:22.926Z MongoMS:MongoInstance Mongo[39327]: prepareCommandArgs: final arugment array:["--port","39327","--dbpath","/tmp/mongo-mem--13-Swd021cDv0KE","--storageEngine","wiredTiger","--bind_ip","127.0.0.1","--noauth"]
web_1  | 2021-08-13T18:03:22.984Z MongoMS:MongoInstance Mongo[39327]: _launchKiller: Launching Killer Process (parent: 13, child: 25)
web_1  | 2021-08-13T18:03:23.044Z MongoMS:MongoInstance Mongo[39327]: stderrHandler: ""/root/.cache/mongodb-binaries/mongod-x64-debian-4.0.25: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /root/.cache/mongodb-binaries/mongod-x64-debian-4.0.25)
web_1  | ""
web_1  | 2021-08-13T18:03:23.045Z MongoMS:MongoInstance Mongo[39327]: closeHandler: Mongod instance closed with an non-0 (or non 12 on windows) code!
web_1  | 2021-08-13T18:03:23.045Z MongoMS:MongoInstance Mongo[39327]: closeHandler: 1

```

DockerFile
```
FROM nikolaik/python-nodejs

WORKDIR ./src
COPY package*.json /
EXPOSE 8080
ENV MONGOMS_DEBUG=1

RUN npm install mocha -g && npm install ts-node -g && npm install typescript -g && npm install 

```

```
export class DatabaseMockFast {
  connectionString?: string
  connection?: Mongoose
  mongoServer?: MongoMemoryServer
  db: Db = {} as Db

  async connect(): Promise<void> {
    const start = performance.now()

    console.log('==========================DOCKER===========================')

    const mongooseOpts: ConnectionOptions = {
      keepAlive: true,
      useNewUrlParser: true,
      useUnifiedTopology: true,
      useCreateIndex: false,
    }

    this.mongoServer = await MongoMemoryServer.create({
      auth: {},
      instance: { auth: true, storageEngine: 'wiredTiger' },
    })

    const mongoUri = this.mongoServer.getUri()
    mongoose.set('debug', true)
    this.connection = await mongoose.connect(mongoUri, mongooseOpts)
    this.connectionString = mongoUri
    console.debug(performance.now() - start)
  }
```

**Comment by hasezoey** [comment]
@tosiek88 your issue is not related to this issue, next time please open up another issue

PS: this is your issue: #476
