### ISSUE TITLE
Feature Request: Support for $$NOW

### ISSUE THREAD

**Issue by rubenvereecken** [nodkz/mongodb-memory-server#521]
## Versions

- mongodb-memory-server-*: 7.3.4

package: mongo-memory-server

## What is your question?

I found that there is no support for the mongodb aggregation variable [`$$NOW`](https://docs.mongodb.com/manual/reference/aggregation-variables/#mongodb-variable-variable.NOW) which simply returns the current time. We use it in a scoring function used in document sorting. Would it be possible to request this functionality?

**Comment by hasezoey** [comment]
like many others already asked, this package only manages the mongodb binary / instance

from what i can tell, variable `$$NOW` got added in 4.2, where this package's default is `4.0.25`, you will have to set your version to `4.2` with [`VERSION`](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#version) ([read here on how to add it to the package.json](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#how-to-use-them-in-the-packagejson)) or use the package `mongodb-memory-server-global-4.2`
