### ISSUE TITLE
Support and use MongoDB Driver 4.x

### ISSUE THREAD

**Issue by hasezoey** [nodkz/mongodb-memory-server#532]
MongoDB driver 4.x was fully rewritten to typescript with 4.0.0 and cannot easily be transitioned without breaking stuff

For now, anyone that wants to use MongoDB driver 4.x with this package (7.x), try to avoid places where the driver is used (like using `createAuth` / `automaticAuth` or the ReplSet)

**Comment by mielp** [comment]
Do you accept pull requests for this?

**Comment by hasezoey** [comment]
@mielp you can try, though it will not be in in 7.x, it will be in 8.x

**Comment by hasezoey** [comment]
upgraded in 6cf55023c2ace7448a80c88d6067f8dbb7742572, currently released in `8.0.0-beta.1`

**Comment by hasezoey** [comment]
closing because 6cf55023c2ace7448a80c88d6067f8dbb7742572 is now in master branch
