### ISSUE TITLE
how do i manually put binaries into mongodb-binaries

### ISSUE THREAD

**Issue by Diluka** [nodkz/mongodb-memory-server#539]
## Versions

- NodeJS: 0.0.0
- mongodb-memory-server-*: 0.0.0
- mongodb: 0.0.0
- mongoose: 0.0.0 
- system:  macos

package: mongo-memory-server 

## What is your question?

it can't auto download the binaries on my computer. I can download the binaries package by using download app. But how can i put it?

**Comment by hasezoey** [comment]
place the binary where ever needed (probably package manager set), and use the [`SYSTEM_BINARY`](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#system_binary) config option in either the [`package.json`](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#how-to-use-them-in-the-packagejson) or as a [environment variable](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#how-to-use-them-as-environment-variables)
