### ISSUE TITLE
E11000 duplicate key error does not contain index name or key name/path

### ISSUE THREAD

**Issue by LordUche** [nodkz/mongodb-memory-server#556]
## Versions

- NodeJS: 14.17.5
- mongodb-memory-server-*: 7.4.3
- mongodb(the binary version): 3.7.2
- mongoose: 6.0.10 
- system: MacOS

package: mongo-memory-server 

## What is the Problem?

When a duplicate key error occurs, I get the message

`MongoServerError: E11000 duplicate key error dup key: {: "jdoe@example.com" }`

instead of something like:

```MongoServerError: E11000 duplicate key error collection: test-db.users index: email_1 dup key: { email: "jdoe@example.com" }```

Also, the error object should contain `keyPattern` and `keyValue` keys like:

```
{
  index: 0,
  code: 11000,
  keyPattern: { email: 1 },
  keyValue: { email: 'jdoe@example.com' }
}
```

but the `keyPattern` and `keyValue` keys are undefined.

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment]
> mongodb(the binary version): 3.7.2

are you sure you are using that version and not something like `4.0.25`?

---

where does this error come from, from inside this package (`mongodb-memory-server`) or from your code?

also, please provide your mongodb configuration (eg `new MongoMemoryServer` / `new MongoMemoryReplSet`)

**Comment by hasezoey** [comment]
just tried your [reproduction repo](https://github.com/LordUche/mongoose-unique)

it seems like this is a problem with the mongodb driver 4.x and using mongodb server 4.0.x, with mongodb server 4.2(.14) or higher i cant reproduce this problem

workaround:
- set config option [VERSION](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#version) to 4.2 or higher (either in [package.json](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#how-to-use-them-in-the-packagejson) or [environment variable](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#how-to-use-them-as-environment-variables))
- use mongoose 5.13.x (or minor higher) to use mongodb (driver) 3.x and wait for #555

**Comment by DheerajRed** [comment]
Hey I made a dedicated video on this please check it out https://youtu.be/wSQxPtP2usw
