### ISSUE TITLE
Extend or Remove Process exist listeners

### ISSUE THREAD

**Issue by hasezoey** [nodkz/mongodb-memory-server#563]
The Event `beforeExit` will not get triggered if stopped with something like `CTRL+C` or other events like `SIGUSR1`, so we either need to extend to listen to all (which is kinda impossible, because some of these events dont run Promises to the end, which `cleanup` is)

## Related Issues

- Found in #530

**Comment by edshen17** [comment]
Hi, I just updated to the beta version and everything works as expected. I no longer get those 300MB files when I restart nodemon/run tests.

Thank you so much!
