### ISSUE TITLE
Update operation with aggregation pipelines

### ISSUE THREAD

**Issue by lgmf** [nodkz/mongodb-memory-server#564]
## Versions
- NodeJS: 14.17.3
- mongodb-memory-server-*: 6.3.3
- mongodb: 4.4.10
- mongoose: 6.0.12
- system: Elementary OS 5.1.7 Hera Built on Ubuntu 18.04.6 LTS

package:
Mongoose Testing (https://www.npmjs.com/package/@tsed/testing-mongoose)

## What is your question?

I'm using TSED as a NodeJS framework (https://github.com/tsedio/tsed/issues/1604) and it uses a wrapper to the mongodb-memory-server in order to create automated tests.

The problem is that I'm not being able to use aggregation pipelines on updates. When running the application with MongoDB version 4.4.10 my code works, but in the test environment, it doesn't.

Basically, I have a repository that executes a "find and replace" operation on a string property using the aggregate operator $replaceAll and then updates the current document.

```ts
async function findAndReplaceRecords(id: string, propName: string, payload: { find: string; replace: string }) {
  const doc = await this.getDocumentById(id);

  const { find, replace } = payload;

  const pipeline = [
    {
      $set: {
        records: {
          $map: {
            input: "$records",
            as: "record",
            in: {
              $mergeObjects: [
                "$$record",
                {
                  [propName]: {
                    $replaceAll: {
                      input: `$$record.${propName}`,
                      find,
                      replacement: replace
                    }
                  }
                }
              ]
            }
          }
        }
      }
    }
  ];

  return doc.updateOne(pipeline);
}
```

**Comment by brano93** [comment]
Facing same issue, any updates?

**Comment by hasezoey** [comment]
@brano93 if you have a similar issue, please open a new issue with all the information and maybe reference the old issue
