### ISSUE TITLE
Migration docs links logged to console are broken

### ISSUE THREAD

**Issue by ConorSheehan1** [nodkz/mongodb-memory-server#571]
## Versions
- NodeJS: any
- mongodb-memory-server: 7.5.1
- mongodb(the binary version): any
- system: MacOS

package: mongo-memory-server

## What is the Problem?

Looks like the url paths were updated on https://nodkz.github.io but not here.
e.g. when exceptions are thrown starting mongo memory server, the url logged to the console is https://nodkz.github.io/mongodb-memory-server/docs/guides/migrate7#no-function-other-than-start-create-ensureinstance-will-be-starting-anything
but that 404s. Seems `/migration` is missing, should be
https://nodkz.github.io/mongodb-memory-server/docs/guides/migration/migrate7#no-function-other-than-start-create-ensureinstance-will-be-starting-anything
```diff
-https://nodkz.github.io/mongodb-memory-server/docs/guides/migrate7#no-function-other-than-start-create-ensureinstance-will-be-starting-anything
+https://nodkz.github.io/mongodb-memory-server/docs/guides/migration/migrate7#no-function-other-than-start-create-ensureinstance-will-be-starting-anything
```

<img width="1411" alt="Screenshot 2021-11-05 at 15 31 16" src="https://user-images.githubusercontent.com/16896053/140536533-bd74abc3-dbe6-41e6-b6df-4d1df5d4bee5.png">

![Screenshot 2021-11-05 at 15 32 55](https://user-images.githubusercontent.com/16896053/140536728-259768f1-0bee-4565-88d1-a9bf68c781ea.png)

![Screenshot 2021-11-05 at 15 32 14](https://user-images.githubusercontent.com/16896053/140536642-c0a5616c-14c8-4b17-8355-47065cb075b4.png)

**Comment by hasezoey** [comment]
Note: this fix is also included ("backported") into 7.6.2
