### ISSUE TITLE
Variable `isNew` is wrongly inverted when `dbPath` is defined and a new instance is created

### ISSUE THREAD

**Issue by Steditor** [nodkz/mongodb-memory-server#573]
I think this should be the other way round: A dbPath is to be considered new if there are no files in it (`files.length === 0`).

https://github.com/nodkz/mongodb-memory-server/blob/2a94fb0b3b382ecad2cb72e17968e6ffcfaeb9ee/packages/mongodb-memory-server-core/src/MongoMemoryServer.ts#L363-L365

**Comment by hasezoey** [comment]
Note: this fix is also included ("backported") into 7.6.1
