### ISSUE TITLE
Root password in createAuth is constant

### ISSUE THREAD

**Issue by Steditor** [nodkz/mongodb-memory-server#575]
According to the types, one can customize the root password when using the database with `auth: true`:

https://github.com/nodkz/mongodb-memory-server/blob/d153b6532e8a9bd7317e9f22d942c3573606e3b9/packages/mongodb-memory-server-core/src/MongoMemoryServer.ts#L59

However, the customized root password is not used; instead a fixed password is always used:

https://github.com/nodkz/mongodb-memory-server/blob/d153b6532e8a9bd7317e9f22d942c3573606e3b9/packages/mongodb-memory-server-core/src/MongoMemoryServer.ts#L673

**Comment by hasezoey** [comment]
thanks for noticing this and pointing this out, this will be fixed with 8.0.2 and 7.6.3

---

next time please use a issue template
