### ISSUE TITLE
npm install hang when it run postinstall.js

### ISSUE THREAD

**Issue by mtruon11** [nodkz/mongodb-memory-server#592]
Hi, 

In my packages.json, I defined a postinstall script like this `"postinstall": "node -r mongodb-memory-server-global/postinstall.js"` when running npm install, npm postinstall will be run automatically. I expected this will not be hung and exit the process and carryon as a binary is already installed in my machine. I see in the postInstallHelper did not call process.exit(0) when it is successful. Can anyone tell if this is a bug or not? 

Node 12.22.8
typescript 4.2.3

**Comment by hasezoey** [comment]
i dont quite understand your question, why a extra top-level `postinstall` script executing the postinstall file?

also, the script "assumes" it is correctly started (from the package manager, like correct CWD) and so loads the postinstall (with a config from `-global`) from `-core` 

from what i know, `npm` and `yarn` post execute `postinstall` scripts from installed packages
