### ISSUE TITLE
Release is not part of the binary name identifier

### ISSUE THREAD

**Issue by skrtheboss** [nodkz/mongodb-memory-server#609]
## Versions

- NodeJS: 16.4.0 and 12.22.10
- mongodb-memory-server-*: 8.4.0 
- mongodb(the binary version): 5.0.3
- mongodb(the js package): 4.3.1
- mongoose: 6.2.3
- system: Linux

package: mongo-memory-server 

## What is the Problem?

I specified the `MONGOMS_DOWNLOAD_DIR` in my Jenkinsfile so that the tests could share the binaries between different runs and I encountered a problem when using different docker images of node:

- With docker.io/library/node:16.14.0 it downloads the following binary https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian10-5.0.3.tgz
- With docker.io/library/node:12.22.10 it downloads the following binary https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian92-5.0.3.tgz

However the output file name of both is just `mongod-x64-debian-5.0.3`, without the debian release version.
So when I try to run the test in the 12.22.10 container, after the binary has been downloaded in a 16.4.0 container, I get the following error: 

```txt
  MongoMS:MongoInstance Mongo[42073]: start: Starting Processes +8ms
  MongoMS:MongoInstance Mongo[42073]: _launchMongod: Launching Mongod Process +0ms
  MongoMS:MongoInstance Mongo[42073]: prepareCommandArgs +0ms
  MongoMS:MongoInstance Mongo[42073]: prepareCommandArgs: final argument array:["--port","42073","--dbpath","/tmp/mongo-mem--320-F3eEvdNstaky","--storageEngine","wiredTiger","--bind_ip","127.0.0.1","--noauth"] +0ms
  MongoMS:MongoInstance Mongo[42073]: _launchKiller: Launching Killer Process (parent: 320, child: 343) +21ms
  MongoMS:MongoInstance Mongo[42073]: stderrHandler: ""/shared_caches/mongodbms-binaries-cache/mongod-x64-debian-5.0.3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /shared_caches/mongodbms-binaries-cache/mongod-x64-debian-5.0.3)
  MongoMS:MongoInstance /shared_caches/mongodbms-binaries-cache/mongod-x64-debian-5.0.3: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by /shared_caches/mongodbms-binaries-cache/mongod-x64-debian-5.0.3)
  MongoMS:MongoInstance /shared_caches/mongodbms-binaries-cache/mongod-x64-debian-5.0.3: /usr/lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /shared_caches/mongodbms-binaries-cache/mongod-x64-debian-5.0.3)
  MongoMS:MongoInstance "" +25ms
  MongoMS:MongoInstance Mongo[42073]: closeHandler: Mongod instance closed with an non-0 (or non 12 on windows) code! +0ms
  MongoMS:MongoInstance Mongo[42073]: closeHandler: "1" "null" +0ms
  MongoMS:MongoMemoryServer Mongo[unknown]: stop: Called .stop() method +57ms
  MongoMS:MongoMemoryServer Mongo[unknown]: stop: "instanceInfo" is not defined (never ran?) +0ms
Error: Jest: Got error running globalSetup - /path-to-repo/test/e2e/setup.js, reason: Instance Exited before being ready and without throwing an error!
    at MongoInstance.<anonymous> (/path-to-repo/node_modules/mongodb-memory-server-core/lib/util/MongoInstance.js:140:25)
    at Object.onceWrapper (events.js:421:26)
    at MongoInstance.emit (events.js:314:20)
    at MongoInstance.closeHandler (/path-to-repo/node_modules/mongodb-memory-server-core/lib/util/MongoInstance.js:276:14)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Socket.<anonymous> (internal/child_process.js:444:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:675:12)
error Command failed with exit code 1.
```

## Do you know *why* it happenes?

Yes, the problem is, that the release is not part of the binary name. The [getBinaryName](https://github.com/nodkz/mongodb-memory-server/blob/bbddd350626950dffa89592e740420d31f07df93/packages/mongodb-memory-server-core/src/util/DryMongoBinary.ts#L216) function should also add the release to the binary name.

**Comment by hasezoey** [comment]
currently this is actually intended behavior, because getting the release information is sometimes not reliable and not really standardized (like some do `92` releases some do `9.2` releases and some do `92.0` releases, which all can mean the same thing, or be different)

but yes, i guess this should be part of it, but i would like to make one of the 2 things:
- add a flag (like config value / environment variable) to enable adding release numbers to names and have it off by default
- only add it on distros / systems where it actually matters (like on debian / ubuntu, but not arch)

also, if the second option should be used, it would be considered a breaking change, and users would have to manually clean-up the old binaries again (see [FAQ: Do binaries get automatically deleted?](https://nodkz.github.io/mongodb-memory-server/docs/guides/faq#do-binaries-get-automatically-deleted)

**Comment by skrtheboss** [comment]
@hasezoey thank for your response.
I  understand your arguments, and I would be okay with either of your proposed solutions.
Are you going to implement this? Can I help you in some way?

**Comment by hasezoey** [comment]
> Are you going to implement this?

i will probably implement this somehow, but i cannot give a ETA on when or in which version

> Can I help you in some way?

you can always try to make a PR implementing this
