### ISSUE TITLE
Win10 x64 - Download only extracts mongod.exe

### ISSUE THREAD

**Issue by Vitaefinis** [nodkz/mongodb-memory-server#61]
Hi,

On Win10 x64, it's only extracting mongod.exe and throwing various dll errors related to open ssl.
If I manually download and extract all files from the archive link given in the console, it works fine.

**Comment by nodkz** [comment]
Please try a new version of the package. Will be published in minutes.
But before please remove cache folder with already downloaded binaries. It should bi in your User folder with name `mongodb-binaries` or something like.

**Comment by Vitaefinis** [comment]
working as expected now, thank you.
