### ISSUE TITLE
Dropping DB hangs when using replica set

### ISSUE THREAD

**Issue by Grsz** [nodkz/mongodb-memory-server#619]
## Versions

- NodeJS: 16.11.1
- mongodb-memory-server-*:  
- mongodb(the binary version): "4.2.6"
- mongodb(the js package): 4.4.1
- mongoose: 6.0.11 
- system: MacOS 12.2.1 (M1 Pro)

package: mongo-memory-server 

## What is your question?
I'm trying to switch from standalone db to replica set because I want to use transactions. I have to rewrite my tests for that.

Previously the code looked like:
```ts
import mongoose from 'mongoose';
import { MongoMemoryServer } from 'mongodb-memory-server';

export const connectMongoose = async () => {
  const mongoServer = await MongoMemoryServer.create();
  const mongoUri = mongoServer.getUri();
  await mongoose.connect(mongoUri);

  return { mongoServer };
};

export const reset = async () => {
  await mongoose.connection.db.dropDatabase();
};

export const disconnectMongoose = async (mongoServer) => {
  await mongoose.disconnect();
  await mongoServer.stop();
};
```

And it was working fine.

Now I've transformed it into replica set:

```ts
import mongoose from 'mongoose';
import { MongoMemoryServer, MongoMemoryReplSet } from 'mongodb-memory-server';

export const connectMongoose = async () => {

  const mongoServer = await MongoMemoryReplSet.create({ replSet: { count: 1, storageEngine: 'wiredTiger' } });
  await mongoServer.waitUntilRunning();
  const mongoUri = mongoServer.getUri();
  console.log(mongoUri);
  await mongoose.connect(`${mongoUri}`);

  return { mongoServer };
};

export const resetDb = async () => {
  console.log('resetting db');
  await mongoose.connection.db.dropDatabase({ retryWrites: false, readConcern: 'majority' });
  // never reaches
  console.log('finished resetting');
};

export const disconnectMongoose = async (
  mongoServer
) => {
  await mongoose.disconnect();
  await mongoServer.stop();
};

```

I've tried lot of things, options, changed the arch as suggested if using ARM, but nothing works. The db drop just hangs. No errors, no anything. Any ideas?

**Comment by hasezoey** [comment]
> await mongoServer.waitUntilRunning();

the function `waitUntilRunning` does not need to be called if `start` has been awaited, because `start` itself uses the function (and by extension `create` is using `start`)

> await mongoose.connect(`${mongoUri}`);

why is it a (otherwise empty) template string?

> await mongoose.connection.db.dropDatabase({ retryWrites: false, readConcern: 'majority' });

wouldnt you want to use `writeConcern` in this case?

---

with the current information i dont see a reason on why this might fail, maybe try to "fix" the mentioned code above and provide [Debug Logs](https://nodkz.github.io/mongodb-memory-server/docs/guides/enable-debug-mode) (in full) while using the replset

**Comment by Vasile-Peste** [comment]
Same issue here

**Comment by hasezoey** [comment]
for anyone having this issue, please open a new issue with current mongodb-memory-server information, including logs and a repro script (if possible)
