### ISSUE TITLE
How to use ReplicaSet properly with NestJs Mongoose module?

### ISSUE THREAD

**Issue by vanuverma** [nodkz/mongodb-memory-server#627]
## Versions

- NodeJS: 16.14.0
- mongodb-memory-server: 8.4.0
- mongodb(the binary version): 5.0.3
- mongodb(the js package): 4.4.1
- mongoose: 6.2.4
- system: MacOS Monterey 12.3

package: mongo-memory-server

## What is your question?

**What is the correct way of using mongodb-memory-server `ReplicaSet` option with NestJs?**

According to the documentation, I have a file that creates a ReplicaSet based on the input param. 
Here is the code that creates a replicaSet:    
```ts
function createFactory(opts: Partial<MongooseModuleOptions>, useReplicaset: boolean) {
    return async () => {
        console.log('\n\nMONGOD STATUS::: ', mongod); // undefined
        const inMemoryDatabaseName = 'in-mem-db';
        if (!mongod) {
            // eslint-disable-next-line no-console
            console.log('Initialising MongoMemoryServer');

            mongod = useReplicaset
                ? MongoMemoryReplSet.create({
                      replSet: { storageEngine: 'wiredTiger', count: 3, dbName: inMemoryDatabaseName },
                  })
                : MongoMemoryServer.create();
        }
        initialized = true;
        const instance = await mongod;
        if (useReplicaset) {
            console.log('\n\nREPLICA SET STATUS::: ', instance.state); // running 
        }
        let uri = `${instance.getUri()}`;
        if (useReplicaset) {
            uri = uri + '&retryWrites=false&writeConcern=majority';
        } else {
            uri = uri + inMemoryDatabaseName;
        }
        console.log('\n\nREPLICA SET URI::: ', uri);
       // the above line writes this uri: mongodb://127.0.0.1:59100,127.0.0.1:59101,127.0.0.1:59102/?replicaSet=testset&retryWrites=false&writeConcern=majority

        return mongooseSettings(uri, opts);
    };
}
```
The above factory method is used when importing MongooseModule. Now when I run my tests using jest and one of my test tries to save some data into the memory server db, I am seeing below error thrown from my service class:   
```
MongoWriteConcernError: operation was interrupted
        at MessageStream.messageHandler (/Users/vanu.verma/PROJECTS/..../<microservice name>/node_modules/mongoose/node_modules/mongodb/src/cmap/connection.ts:748:20)
        at MessageStream.emit (node:events:520:28)
        at MessageStream.emit (node:domain:475:12)
        at processIncomingData (/Users/vanu.verma/PROJECTS/..../<microservice name>/node_modules/mongoose/node_modules/mongodb/src/cmap/message_stream.ts:168:12)
        at MessageStream._write (/Users/vanu.verma/PROJECTS/..../<microservice name>/node_modules/mongoose/node_modules/mongodb/src/cmap/message_stream.ts:65:5)
        at writeOrBuffer (node:internal/streams/writable:389:12)
        at _write (node:internal/streams/writable:330:10)
        at MessageStream.Writable.write (node:internal/streams/writable:334:10)
        at Socket.ondata (node:internal/streams/readable:754:22)
        at Socket.emit (node:events:520:28) {
      code: 11602,
      codeName: 'InterruptedDueToReplStateChange',
      errInfo: {
        writeConcern: { w: 'majority', wtimeout: 0, provenance: 'clientSupplied' }
      },
      result: {
        writeConcernError: {
          code: 11602,
          codeName: 'InterruptedDueToReplStateChange',
          errmsg: 'operation was interrupted',
          errInfo: [Object]
        },
        topologyVersion: { processId: new ObjectId("62451fcb04ed7a1fbcb512c5"), counter: 7 },
        ok: 1,
        '$clusterTime': {
          clusterTime: new Timestamp({ t: 1648697298, i: 4 }),
          signature: [Object]
        },
        operationTime: new Timestamp({ t: 1648697298, i: 2 })
      }
    }
```
And below are errors thrown from the mongodb-memory-server code ( I assume) 
```
console.warn
    MongoServerSelectionError: Error: connect ECONNREFUSED 127.0.0.1:59100
        at Timeout._onTimeout (/Users/vanu.verma/PROJECTS/.../common-lib/node_modules/mongodb-memory-server-core/node_modules/mongodb/src/sdam/topology.ts:618:30)
        at listOnTimeout (node:internal/timers:559:17)
        at processTimers (node:internal/timers:502:7) {
      reason: TopologyDescription {
        type: 'Single',
        servers: Map(1) { '127.0.0.1:59100' => [ServerDescription] },
        stale: false,
        compatible: true,
        heartbeatFrequencyMS: 10000,
        localThresholdMS: 15,
        logicalSessionTimeoutMinutes: undefined
      },
      code: undefined
    }

      at MongoInstance.<anonymous> (../../common-lib/node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:409:21)
          at Generator.throw (<anonymous>)
      at rejected (../../common-lib/node_modules/tslib/tslib.js:115:69)

  console.warn
    MongoServerSelectionError: Error: connect ECONNREFUSED 127.0.0.1:59101
        at Timeout._onTimeout (/Users/vanu.verma/PROJECTS/.../common-lib/node_modules/mongodb-memory-server-core/node_modules/mongodb/src/sdam/topology.ts:618:30)
        at listOnTimeout (node:internal/timers:559:17)
        at processTimers (node:internal/timers:502:7) {
      reason: TopologyDescription {
        type: 'Single',
        servers: Map(1) { '127.0.0.1:59101' => [ServerDescription] },
        stale: false,
        compatible: true,
        heartbeatFrequencyMS: 10000,
        localThresholdMS: 15,
        logicalSessionTimeoutMinutes: undefined
      },
      code: undefined
    }

      at MongoInstance.<anonymous> (../../common-lib/node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:409:21)
          at Generator.throw (<anonymous>)
      at rejected (../../common-lib/node_modules/tslib/tslib.js:115:69)

  console.warn
    MongoServerSelectionError: Error: connect ECONNREFUSED 127.0.0.1:59102
        at Timeout._onTimeout (/Users/vanu.verma/PROJECTS/.../common-lib/node_modules/mongodb-memory-server-core/node_modules/mongodb/src/sdam/topology.ts:618:30)
        at listOnTimeout (node:internal/timers:559:17)
        at processTimers (node:internal/timers:502:7) {
      reason: TopologyDescription {
        type: 'Single',
        servers: Map(1) { '127.0.0.1:59102' => [ServerDescription] },
        stale: false,
        compatible: true,
        heartbeatFrequencyMS: 10000,
        localThresholdMS: 15,
        logicalSessionTimeoutMinutes: undefined
      },
      code: undefined
    }

      at MongoInstance.<anonymous> (../../common-lib/node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:409:21)
          at Generator.throw (<anonymous>)
      at rejected (../../common-lib/node_modules/tslib/tslib.js:115:69)
```
Please note few things:
- The replicaSet uri does not contain the db name I have added to the `replSet`
- The memory server without replicaSet is working as expected
- I have configured jest default timeout to 60000
 Please advice. Thanks

**Comment by vanuverma** [comment]
Hi @hasezoey thanks for your reply. I do have debug mode enabled via package.json config, but that is not logging anything else except what I have already provided above. My mac is `x86_64`. And I am running the tests directly on my machine via VSCode terminal. My config for enabling debug mode: 
```
"config": {
        "mongodbMemoryServer": {
            "version": "5.0.3",
            "debug": "true"
        }
    },
```

**Comment by hasezoey** [comment]
sorry for the delayed response

---

> I do have debug mode enabled via package.json config, but that is not logging anything else except what I have already provided above

this *should* work normally, did you also already try with the environment variable? also, did you maybe configure another package.json closer to the installed dependency where `config.mongodbMemoryServer` is set, or are you maybe setting these options in a workspace project, but dependencies are installed in the workspace root?

the very least it should log is a message that debug log is enabled

> And I am running the tests directly on my machine via VSCode terminal

just for information, what testing environment are you using? (like jest or mocha+chai)

**Comment by vanuverma** [comment]
Hi @hasezoey thank you for your reply. I am using `NestJs` for code framework and `jest` for testing. I do have a package.json file close to the file that contains my factory function for creating mongo memory server instance. But in there, I don't have any configuration for mongodb-memory-server. I haven't tried with env variable yet. Maybe I will try that and get back to you

**Comment by vanuverma** [comment]
Hi @hasezoey I am getting below when using debug env variable. The command I am running is: 
```
"test": "env MONGOMS_DEBUG=1 yarn test:cov",
"test:cov": "jest src --coverage --forceExit --verbose",
```

And the debug logged into terminal (attached the file)

[debug-log.txt](https://github.com/nodkz/mongodb-memory-server/files/8406052/debug-log.txt)

**Comment by hasezoey** [comment]
> And the debug logged into terminal (attached the file)

thanks for providing, but it seems the file may be truncated (does not contain the start of the log, only everything after a `.create` call)

also the file looks slightly weirdly formatted, what did you use to record that file? (the easiest way in linux would be `MONGOMS_DEBUG=1 yarn run test 2&>1 | tee output.log`, this way it bring everything into the file while still printing to the console)

(Note: i replaced everything matching `/(?:\\$)|(?:\\(?=\{))|(?:\\(?=\}))/gmi`  with nothing to better look at it, in case it should matter)

---

from what i can tell in the log, there are not much problems (only the occasional "slow" messages), like:

> Slow query

i also found odd logs about `Member is now in state RS_DOWN`, even though `stop` was not called yet

---

are you maybe not closing the connections (of mongodb / mongoose) *before* the `stop` is called on the instance(s)?
also, maybe you forgot to await a query?

**Comment by vanuverma** [comment]
Hi @hasezoey sorry for the log. Maybe got truncated while copying. I am adding another file for the logs. I hope this contains everything you are looking for. I checked my code and test file again and below is 
[debug-log-v2.txt](https://github.com/nodkz/mongodb-memory-server/files/8413727/debug-log-v2.txt)
how it looks like
```
let repository: CredentialRepository;
        let module: TestingModule;

        beforeAll(async () => {
            module = await Test.createTestingModule({
                imports: [
                    MockMongooseModule.forTesting({}, 60000, true),
                    // other modules here
                ],
            }).compile();
            repository = module.get<CredentialRepository>(
                CredentialRepository
            );
        });

        afterEach(async () => {
            await MockMongooseModule.clean(module);
        });

        afterAll(async () => {
            await MockMongooseModule.close();
            await module.close();
        });
```

**Comment by hasezoey** [comment]
>  how it looks like

what you provided looks like it is just nestjs, which i dont know much about but will try

> MockMongooseModule

from what i know, this module is using `mockgoose`, which is a mongoose mock which should not be using any database connection (and is from what i know not updated / outdated / abandoned)

> [debug-log-v2.txt](https://github.com/nodkz/mongodb-memory-server/files/8413727/debug-log-v2.txt)

from what i can tell, there is nothing new that would hint to the issue, i will highlight the  again that i found:

```txt
Slow query (warning)
Member is now in state RS_DOWN (i dont quite know why this is triggered)
Interrupted operation as its client disconnected (i dont know if it is meaning a replset connection (between the replset's) or a client connection (from outside replset's)
```

**Comment by vanuverma** [comment]
Thanks @hasezoey for your time on this. I will try and see if I can identify the issue from my side. I will close this question for now as at the moment, I don't have any update to provide.

**Comment by noghartt** [comment]
Is there any update on this issue?

I'm having a similar issue trying to test `changeStreams` with replica set, and I'm taking the same error:

```
MongoWriteConcernError: operation was interrupted
```

Already change the `writeConcern` and other helpful queries for my URI, tried other solutions but isn't working too.

A weird behavior is that some times it's working, so seems like a _flaky_ test.

**Comment by hasezoey** [comment]
it is sadly known that mongodb's replsets may just decide to "step-down" to secondary and so interrupt any operations, there is no (to me known) way to force the replsets to stay the way they are, the only "workaround" would be to add a waiting time before actually connecting (like ~10 seconds), where it *could still happen* but *less likely*
