### ISSUE TITLE
Getting "RangeError: Maximum call stack size exceeded" when unit testing with mongodb-memory-server

### ISSUE THREAD

**Issue by Suson1478** [nodkz/mongodb-memory-server#628]
## Versions

- NodeJS: 14.18.2
- mongodb-memory-server-*: 8.4.2
- mongodb(the binary version): 5.5
- mongodb(the js package): N/A
- mongoose: 6.2.9
- system: MacOS, 12.3.1

package: mongo-memory-server

## What is the Problem?

I am trying to unit test some typescript logic with [jest](https://github.com/facebook/jest). I am using [mongoose](https://github.com/Automattic/mongoose) in order to interact with the mongo database and [mongo-memory-server](https://github.com/nodkz/mongodb-memory-server) in order to mock mongodb.

For unclear reason, I get the following error, which seems to result from cyclic dependencies, when running the below unit test.

# Code Example

Unit Test:

```ts
import mongoose, { Mongoose } from "mongoose";
import { MongoMemoryServer } from "mongodb-memory-server";

describe("test mongo memory server", () => {
    let client: Mongoose;
    let mongod;

    beforeAll(async () => {
      mongod = await MongoMemoryServer.create();
      client = await mongoose.connect(mongod.getUri());
    });

    afterAll(async () => {

      if (mongod) {
        await mongod.stop();
      }
    });

    it("empty test", async () => {
    });
});

```

## Debug Output

<details>
<summary>Debug Output</summary>

Error:
```
  ● Test suite failed to run

    RangeError: Maximum call stack size exceeded

      at Object.get [as ObjectId] (node_modules/mongoose/node_modules/mongodb/src/bson.ts:38:3)
      at Object.get [as ObjectId] (node_modules/mongoose/node_modules/mongodb/src/bson.ts:38:3)
```

</details>

## Do you know *why* it happens?

Seems related to cyclic dependencies caused by the version combination I am using (which I need in order to upgrade my mongodb to latest, 5.5)

1. When commenting out the connection to mongo (`client = await mongoose.connect(mongod.getUri());`), and using `mongo-memory-server` (version: 7.6.3) the below unit test passes. On the other hand, when the line is not commented out, it fails.
2. When commenting out the connection to mongo (`client = await mongoose.connect(mongod.getUri());`), but using latest `mongo-memory-server` (version 8.4.2), the test fails.
3. Seems link circular dependencies. When running with `mongoose: 5.13.14` and `mongo-memory-server: 7.6.3` there is no issue (alas I need to [upgrade mongoose](https://mongoosejs.com/docs/compatibility.html) in order to be compatible with mongodb 5.5).

**Comment by hasezoey** [comment]
dont just remove the issue template, please update your issue to the full issue template

**Comment by Suson1478** [comment]
> dont just remove the issue template, please update your issue to the full issue template

My bad, I updated the issue based on your template. Please let me know if something is missing and I will provide the input right away.

**Comment by hasezoey** [comment]
> mongodb(the binary version): 5.5

from what i know, this version does not exists (highest version currently out is 5.0.6)
(even if you would mean the driver, the highest version for that is 4.5.0)

> Seems link circular dependencies. When running with mongoose: 5.13.14 and mongo-memory-server: 7.6.3 there is no issue (alas I need to [upgrade mongoose](https://mongoosejs.com/docs/compatibility.html) in order to be compatible with mongodb 5.5).

mongoose `5.13.14` uses mongodb driver `3.7.3`(hard) and MMS-core `7.6.3` uses `^3.7.3`

> When commenting out the connection to mongo (client = await mongoose.connect(mongod.getUri());), but using latest mongo-memory-server (version 8.4.2), the test fails.

mongoose `6.2.9` uses mongodb driver `4.3.1`(hard) and MMS-core `8.4.2` uses `^4.4.0` (which should actually not pose a runtime problem, aside from slightly more ram usage)

---

> Error:

do you maybe have a longer stack-trace? because with just this error it is hard to say what is the problem (or where)

also could you maybe provide the output of either `yarn why mongodb` or `npm list mongodb` (when having the "new" versions installed)

**Comment by Suson1478** [comment]
> > mongodb(the binary version): 5.5
> 
> from what i know, this version does not exists (highest version currently out is 5.0.6) (even if you would mean the driver, the highest version for that is 4.5.0)
>

Indeed, I meant version 5.0 (sorry, was a typo). In order to upgrade my mongodb to version 5.0 I need to upgrade my mongoose package to `6.2.9`. 
 
> > Seems link circular dependencies. When running with mongoose: 5.13.14 and mongo-memory-server: 7.6.3 there is no issue (alas I need to [upgrade mongoose](https://mongoosejs.com/docs/compatibility.html) in order to be compatible with mongodb 5.5).
> 
> mongoose `5.13.14` uses mongodb driver `3.7.3`(hard) and MMS-core `7.6.3` uses `^3.7.3`
> 
> > When commenting out the connection to mongo (client = await mongoose.connect(mongod.getUri());), but using latest mongo-memory-server (version 8.4.2), the test fails.
> 
> mongoose `6.2.9` uses mongodb driver `4.3.1`(hard) and MMS-core `8.4.2` uses `^4.4.0` (which should actually not pose a runtime problem, aside from slightly more ram usage)
> 
> > Error:
> 
> do you maybe have a longer stack-trace? because with just this error it is hard to say what is the problem (or where)
> 
> also could you maybe provide the output of either `yarn why mongodb` or `npm list mongodb` (when having the "new" versions installed)

The output of `npm list mongodb` is as follows (seems that MMS is not supporting mongodb > 5.x.x?):

```
server@1.0.0 /Users/ysternbach/workspace/zoezoe-site/server
├─┬ connect-mongo@4.4.1
│ └── mongodb@3.6.5
├─┬ mongodb-memory-server@8.4.2
│ └─┬ mongodb-memory-server-core@8.4.2
│   └── mongodb@4.5.0
└─┬ mongoose@6.2.9
  └── mongodb@4.3.1
```


Here is the complete output of the unit test I posted:

```
cd '/Users/ysternbach/workspace/zoezoe-site/server'
node 'node_modules/.bin/jest' '/Users/ysternbach/workspace/zoezoe-site/server/src/health/mongo.spec.ts' -t 'test mongo memory server'
ysternbach@ip-192-168-252-15 server % cd '/Users/ysternbach/workspace/zoezoe-site/server'
ysternbach@ip-192-168-252-15 server % node 'node_modules/.bin/jest' '/Users/ysternbach/workspace/zoezoe-site/server/src/health/mongo.spec.ts' -t 't
est mongo memory server'
watchman warning:  Recrawled this watch 11 times, most recently because:
MustScanSubDirs UserDroppedTo resolve, please review the information on
https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
To clear this warning, run:
`watchman watch-del '/Users/ysternbach/workspace/zoezoe-site' ; watchman watch-project '/Users/ysternbach/workspace/zoezoe-site'`

 FAIL  src/health/mongo.spec.ts
  ● Test suite failed to run

    RangeError: Maximum call stack size exceeded

      at Object.get [as ObjectId] (node_modules/mongodb-memory-server-core/node_modules/mongodb/src/bson.ts:38:3)
      at Object.get [as ObjectId] (node_modules/mongodb-memory-server-core/node_modules/mongodb/src/bson.ts:38:3)
      at Object.get [as ObjectId] (node_modules/mongodb-memory-server-core/node_modules/mongodb/src/bson.ts:38:3)
      at Object.get [as ObjectId] (node_modules/mongodb-memory-server-core/node_modules/mongodb/src/bson.ts:38:3)
      at Object.get [as ObjectId] (node_modules/mongodb-memory-server-core/node_modules/mongodb/src/bson.ts:38:3)
      at Object.get [as ObjectId] (node_modules/mongodb-memory-server-core/node_modules/mongodb/src/bson.ts:38:3)
      at Object.get [as ObjectId] (node_modules/mongodb-memory-server-core/node_modules/mongodb/src/bson.ts:38:3)
      at Object.get [as ObjectId] (node_modules/mongodb-memory-server-core/node_modules/mongodb/src/bson.ts:38:3)
      at Object.get [as ObjectId] (node_modules/mongodb-memory-server-core/node_modules/mongodb/src/bson.ts:38:3)
      at Object.get [as ObjectId] (node_modules/mongodb-memory-server-core/node_modules/mongodb/src/bson.ts:38:3)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        10.451 s
Ran all test suites matching /\/Users\/ysternbach\/workspace\/zoezoe-site\/server\/src\/health\/mongo.spec.ts/i with tests matching "test mongo memory server".
```

**Comment by hasezoey** [comment]
>  In order to upgrade my mongodb to version 5.0 I need to upgrade my mongoose package to 6.2.9.

this is actually not true, mongodb driver `3.7.x` is supporting mongodb 5.0, and mongoose`5.13.x` is using mongodb driver `3.7.x`, see https://www.mongodb.com/docs/drivers/node/current/compatibility/ and https://unpkg.com/browse/mongoose@5.13.14/package.json

> (seems that MMS is not supporting mongodb > 5.x.x?):

i think you are misunderstanding something, there is a difference between the *binary version* (current latest is `5.0.6`, [which is the default in MMS `8.x`](https://nodkz.github.io/mongodb-memory-server/docs/guides/mongodb-server-versions#mongodb-memory-server-core-version-table)) and the nodejs mongodb *driver* (current latest is `4.5.0`)

> The output of npm list mongodb is as follows

it seems like you have mongodb (driver) installed 3 times, once for `mongoose`, once for `mongodb-memory-server-core` and once for `connect-mongo`

the version from MMS-core is not exposed to the outside and connections (currently) only happen in `start` / `stop`, so they should not be conflicting

also `connect-mongo` is using the old `3.x` driver where the other packages are using the `4.x`, which may be conflicting, so maybe try to upgrade that package (from what i can tell from [here](https://www.npmjs.com/package/connect-mongo) version `4.6.x` is supposed to use the `4.x` mongodb driver)

> Here is the complete output of the unit test I posted:

thanks, but this error is also not really telling much more

---

for now i would recommend:
- upgrade `connect-mongodb` to a version that uses the `4.x` mongodb driver
- completely clear `node_modules` (`rm -rf node_modules`) and re-install everything
- try to use a lower `mongodb-memory-server` version which uses the same version as `mongoose` (for example `8.3.x`)
- if everything above did not change anything, maybe try to remove the `.lock` file and re-generate it (`yarn.lock` / `package-lock.json`), with all the above steps applied

**Comment by Suson1478** [comment]
@hasezoey thanks for your detailed response. I will try it out.

**Comment by hasezoey** [comment]
@Suson1478 any updates on this? otherwise i would close this issue
