### ISSUE TITLE
Segmentation fault on downloaded binary

### ISSUE THREAD

**Issue by zeeshan595** [nodkz/mongodb-memory-server#635]
## Versions

- NodeJS: `18.0.0`
- mongodb-memory-server-*: `8.5.1`
- mongodb(the binary version): `mongodb-linux-x86_64-ubuntu2004-5.0.3`
- mongodb(the js package): `4.5.0`
- mongoose: `6.0.13`
- system: Linux Manjaro `21.2.6` Gnome `41.5`

package: mongodb-memory-server
Location of binary: `~/.cache/mongodb-binaries/mongod-x64-manjaro-5.0.3`

## What is the Problem?

The binary for manjaro that get's downloaded (mongod-x64-manjaro-5.0.3) is not working it just throws segmentation fault when you run it. Replacing the binary with a symlink to my globally installed mongod works and I am able to use the package fine.

**Comment by hasezoey** [comment]
As per the documentation [`Supported Systems: Arch`](https://nodkz.github.io/mongodb-memory-server/docs/guides/supported-systems#arch)

> There are no official mongodb builds for Arch Distributions, but the ubuntu binaries work on most Arch systems, so they are used

also, i am currently also running manjaro (21.2.6), where the binaries run just fine

---

for further help, please try to first remove the binary from the mentioned path and try to re-download it again and if it still does not work, please provide [Debug Output](https://nodkz.github.io/mongodb-memory-server/docs/guides/enable-debug-mode)

**Comment by zeeshan595** [comment]
@hasezoey 
Thanks for the reply! 
After looking more into it I realised why it is happening and this was an issue on my side. We are using this for unit testing and jest was killing the test before it had a chance finish / download the package properly, causing a faulty package to be downloaded which threw that segmentation fault.
I am going to close this. Sorry for any trouble i caused over this :p
