### ISSUE TITLE
Add Support for gentoo

### ISSUE THREAD

**Issue by uspasojevic96** [nodkz/mongodb-memory-server#639]
## Versions

- Wanted System: gentoo
- Architecture: x86_64

## Detection

```sh
$ uname -a

Linux blacktoo 5.15.32-gentoo-dist #1 SMP Wed Mar 30 08:46:54 -00 2022 x86_64 AMD Ryzen 9 5900X 12-Core Processor AuthenticAMD GNU/Linux

$ cat /etc/upstream-release/lsb-release

cat: /etc/upstream-release/lsb-release: No such file or directory

$ cat /etc/os-release

NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"

$ cat /usr/lib/os-release

NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"

$ cat /etc/lsb-release

cat: /etc/lsb-release: No such file or directory
```

**Comment by hasezoey** [comment]
thanks for the proposal, but i dont think gentoo will ever be supported, reasons:
- there are no official binaries (and i dont think we can just use a different distro's like in arch)
- this package will very likely never support compiling / building mongodb

workarounds:
- use a different distro
- compile mongodb beforehand and set [`SYSTEM_BINARY`](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#system_binary) to use a system-binary instead of downloading

**Comment by uspasojevic96** [comment]
Can you add detection whether there is system binary installed for gentoo or to specifically say to use `SYSTEM_BINARY` environment?

**Comment by uspasojevic96** [comment]
Just tested `mongodb-linux-x86_64-debian11-latest.tgz` and it works, links against system libraries though, but im not sure which ones come by default beside glibc and the usual stuff

```sh
~/m/mongodb-linux-x86_64-debian11-6.1.0-alpha-404-gbc04b68
➜ ldd bin/mongod
bin/mongod: /usr/lib64/libcurl.so.4: no version information available (required by bin/mongod)
linux-vdso.so.1 (0x00007ffe55fd6000)
libcurl.so.4 => /usr/lib64/libcurl.so.4 (0x00007f3986a2a000)
liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f3986a02000)
libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f39869ef000)
libcrypto.so.1.1 => /usr/lib64/libcrypto.so.1.1 (0x00007f3986729000)
libssl.so.1.1 => /usr/lib64/libssl.so.1.1 (0x00007f3986695000)
libdl.so.2 => /lib64/libdl.so.2 (0x00007f3986690000)
librt.so.1 => /lib64/librt.so.1 (0x00007f3986689000)
libm.so.6 => /lib64/libm.so.6 (0x00007f39865b0000)
libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libgcc_s.so.1 (0x00007f3986596000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f3986591000)
libc.so.6 => /lib64/libc.so.6 (0x00007f398639c000)
/lib64/ld-linux-x86-64.so.2 (0x00007f398d2b8000)
libnghttp2.so.14 => /usr/lib64/libnghttp2.so.14 (0x00007f3986370000)
libz.so.1 => /lib64/libz.so.1 (0x00007f3986354000)
```

**Comment by hasezoey** [comment]
> Just tested `mongodb-linux-x86_64-debian11-latest.tgz` and it works, links against system libraries though, but im not sure which ones come by default beside glibc and the usual stuff
> 
> ```shell
> ~/m/mongodb-linux-x86_64-debian11-6.1.0-alpha-404-gbc04b68
> ➜ ldd bin/mongod
> bin/mongod: /usr/lib64/libcurl.so.4: no version information available (required by bin/mongod)
> linux-vdso.so.1 (0x00007ffe55fd6000)
> libcurl.so.4 => /usr/lib64/libcurl.so.4 (0x00007f3986a2a000)
> liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f3986a02000)
> libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f39869ef000)
> libcrypto.so.1.1 => /usr/lib64/libcrypto.so.1.1 (0x00007f3986729000)
> libssl.so.1.1 => /usr/lib64/libssl.so.1.1 (0x00007f3986695000)
> libdl.so.2 => /lib64/libdl.so.2 (0x00007f3986690000)
> librt.so.1 => /lib64/librt.so.1 (0x00007f3986689000)
> libm.so.6 => /lib64/libm.so.6 (0x00007f39865b0000)
> libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libgcc_s.so.1 (0x00007f3986596000)
> libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f3986591000)
> libc.so.6 => /lib64/libc.so.6 (0x00007f398639c000)
> /lib64/ld-linux-x86-64.so.2 (0x00007f398d2b8000)
> libnghttp2.so.14 => /usr/lib64/libnghttp2.so.14 (0x00007f3986370000)
> libz.so.1 => /lib64/libz.so.1 (0x00007f3986354000)
> ```

if it works, then we could maybe make the same that we currently do with arch(based) systems, having a warning but falling back to a binary that works in most common systems

**Comment by hasezoey** [comment]
with 39b0a3da5253180e5a87dec61cfd33258bd6d68d i have added basic gentoo support defaulting to debian (11) binaries, please test if possible

**Comment by uspasojevic96** [comment]
Will do in a bit, thanks for your effort

**Comment by uspasojevic96** [comment]
Tested with `mongodb-memory-server@beta` and all 709 tests passed, thank you
