### ISSUE TITLE
Not downloading behind proxy

### ISSUE THREAD

**Issue by ChrisSG** [nodkz/mongodb-memory-server#65]
Won't download mongodb if started behind a proxy server even with env vars set.

**Comment by nodkz** [comment]
Mongodb binary is downloading in this lines:
- https://github.com/nodkz/mongodb-memory-server/blob/master/src/util/MongoBinaryDownload.js#L147 - downloads binary
- https://github.com/nodkz/mongodb-memory-server/blob/master/src/util/MongoBinaryDownload.js#L101 - downloads MD5 signature

Will be cool if somebody makes PR with adding proxy support. Sorry I do not use the proxy and have no time to do it myself.

**Comment by ChrisSG** [comment]
See https://github.com/nodkz/mongodb-memory-server/pull/66

**Comment by nodkz** [comment]
Fixed in 1.9.0
