### ISSUE TITLE
Consider removing NodeJS 12 support

### ISSUE THREAD

**Issue by hasezoey** [nodkz/mongodb-memory-server#654]
Remove NodeJS 12 Support because it is EOL

This needs to be done because it is a blocker for many dependency upgrades that require node 14 or higher, like:
- #567
- #652
- #653

Things that would have to be done when removing NodeJS 12 support:
- change tests coverage upload to be from a higher nodejs version
- remove code specific to nodejs 12 (like the recursive deleting code)

---

Personally i would like to keep NodeJS 12 around for as long as it needs to be (it has not caused much burden yet) and should keep the support range about the same as mongoose (because it is a very popular mongodb "driver")

**Comment by shakaran** [comment]
See #691 for a start

**Comment by hasezoey** [comment]
like i said in https://github.com/nodkz/mongodb-memory-server/pull/691#issuecomment-1237818108, i think i will put this off for now (note the tile had been changed to "consider"), because some projects i help maintain use this package and still support node 12 (example: typegoose & mongoose)

**Comment by hasezoey** [comment]
done with edc3a31c9c71b53e266606d6eb6b2572f4ccba0f
