### ISSUE TITLE
Possible Memory Leak?

### ISSUE THREAD

**Issue by colematthew4** [nodkz/mongodb-memory-server#655]
## Versions

- NodeJS: 16.10.0 and 16.14.2
- mongodb-memory-server: 8.6.0
- mongodb(the binary version): 5.0.7
- mongodb(the js package): 4.6.0
- jest: 27.2.1
- weak-napi: 2.0.2
- ts-jest: 27.1.3
- ts-node: 10.7.0
- system: MacOS Catalina

package: mongo-memory-server

## What is the Problem?

When even the most basic setup is used, jest reports a memory leak. I tried using the below and using async/await in the beforeAll/afterAll but they both produce the problem. Also tried without passing flags to the stop function. I investigated it potentially being a false positive from jest after finding [this issue](https://github.com/facebook/jest/issues/7874), but it does not appear to be the case. Am I doing something wrong setting up the tests or is this a genuine issue?

## Code Example

```ts
import { MongoMemoryServer } from 'mongodb-memory-server';

describe('MongoMemoryServer memory leak testing', () => {
  let mongoServer: MongoMemoryServer;

  beforeAll((done) => {
    mongoServer = new MongoMemoryServer();
    mongoServer.start().then(() => {
      done();
    });
  });

  afterAll((done) => {
    mongoServer
      .stop({
        doCleanup: true,
        force: true,
      })
      .then(done);
  });

  describe('One', () => {
    it('Testing', () => {
      expect(1).toBe(1);
    });
  });
});
```

## Debug Output

https://gist.github.com/colematthew4/975e1f8d4da7a47a5d2dc560517ad58a

## Do you know *why* it happens?

*no*

**Comment by hasezoey** [comment]
i dont see a problem from the logs at first glance, so i would like to ask where you see a memory leak, like in the test suites themself or after stopping?

did you also already try the latest nodejs version for your major version (which is 16.15.0)?

>  I tried using the below and using async/await in the beforeAll/afterAll but they both produce the problem.

i would recommend to continue to use async-await in those hooks over callbacks

also if using simple things i would recommend to use `.create` over `new` & `start`

---

also maybe read [Integration with Test Runners: jest](https://nodkz.github.io/mongodb-memory-server/docs/guides/integration-examples/test-runners#jest) if wanting to use MMS for larger projects than just a single test suite

**Comment by colematthew4** [comment]
The memory leak is reported by jest using the --detectLeaks cmdline option (output below). I will look into that integration page and update.

```txt
● Test suite failed to run

    EXPERIMENTAL FEATURE!
    Your test suite is leaking memory. Please ensure all references are cleaned.

    There is a number of things that can leak memory:
      - Async operations that have not finished (e.g. fs.readFile).
      - Timers not properly mocked (e.g. setInterval, setTimeout).
      - Keeping references to the global scope.

      at onResult (node_modules/@jest/core/build/TestScheduler.js:190:18)
      at node_modules/@jest/core/build/TestScheduler.js:316:17
      at node_modules/emittery/index.js:260:13
          at Array.map (<anonymous>)
      at Emittery.emit (node_modules/emittery/index.js:258:23)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        9.217 s
```

**Comment by colematthew4** [comment]
I can't believe I didn't find that integration page after doing research all day long. That fixed it along with the larger test suite I've been working on. Thanks!

**Comment by hasezoey** [comment]
> I can't believe I didn't find that integration page after doing research all day long. That fixed it along with the larger test suite I've been working on. Thanks!

if that fixed your issue and were on a larger scale (more than one test suite that uses MMS), my guess would be that somehow jest keeps the old environment of the run test suite around but somehow resets the cache values but not cleaning them (like replacing a pointer but freeing the previous one)
