### ISSUE TITLE
The documentation section: Guides>Integration Examples>Integration with Test Runners>jest appears to be incomplete 

### ISSUE THREAD

**Issue by jimmythecode** [nodkz/mongodb-memory-server#657]
## Versions

- NodeJS: 16.15.0
- mongodb-memory-server-*: 8.6.0 
- mongodb(the binary version): 0.0.0 (not using?)
- mongodb(the js package): 0.0.0 (not using?)
- mongoose: 6.3.6 
- system: Linux (Ubuntu 20.04)

package: mongo-memory-server

## What is the Problem?

I'm trying to follow this (https://nodkz.github.io/mongodb-memory-server/docs/guides/integration-examples/test-runners#jest) guide, but it appears to be incomplete and I'm not sure what to do to complete the example.

## Code Example
I've set up my best interpretation of the guide into a (formerly) working repo: https://github.com/jimmythecode/mongodbmemoryserver-guide

```ts
// There was an error in setupFile.ts:
import { connect, disconnect } from './utils/connect'; // Cannot find module './utils/connect' or its corresponding type declarations.ts(2307)
```
No "utils/connect.ts" file was described in the guide, so I tried to make my own. I now have an error:

## Debug Output
```
TypeError: Jest: Got error running globalSetup - /home/jimmythecode/Code/mfa-bot-server/src/test/globalSetup.ts, reason: mongoose.connect is not a function
```

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment]
Thanks for reporting, originally the jest example was adapted from typegoose for the documentation, and some fragments seem to still be there, see [`connect.ts` file](https://github.com/typegoose/typegoose/blob/5755670530254d416ee321806be8d40baa78a0f8/test/utils/connect.ts) for the full file that was where that came from

**Comment by hasezoey** [comment]
With 1a0ddf583a5653a890716ed7ae0a80823f1da016 the documentation is updated to not use non-visible files, this should be up in ~10minutes
