### ISSUE TITLE
User roles not working with storageEngine "ephemeralForTest"

### ISSUE THREAD

**Issue by SamyLegal** [nodkz/mongodb-memory-server#670]
## Versions

- NodeJS: v16.15.1
- mongodb-memory-server: 8.7.2 
- mongodb(the binary version): 5.0.8
- mongodb(the js package): 4.7.0
- system: MacOs

package: mongo-memory-server 

## What is your question?

Hello,

As part of the development of my application, I use the "mongo-memory-server" package for my tests.
In my test, I create a "mongo-memory-server" instance with a custom user and specific MongoDB roles.

When I use "mongo-memory-server" with "ephemeralForTest" storage engine, rights management does not work.
When I try to create a document in a database on which I should not have rights, I do not have an exception that is triggered.

If I use the storageEngine "wiredTiger", an exception is triggered but this mode is much slower and less efficient than the "ephemeralForTest" storageEngine.

Is that the normal behavior?
If not, what is the solution to make rights management work with "ephemeralForTest" storageEngine ?

A jest test that presents the problem.

```js
import { MongoMemoryServer } from 'mongodb-memory-server';
import { MongoClient } from 'mongodb';

describe('Mongo Memory Server', () => {
  it('should instance an authenticated mongo memory server with custom users', async () => {
    const instance = new MongoMemoryServer({
      auth: {
        customRootName: 'root',
        customRootPwd: 'pass',
        extraUsers: [
          {
            createUser: 'my-user',
            pwd: 'my-password',
            roles: [
              { role: 'read', db: 'db-read' },
              { role: 'readWrite', db: 'db-write' },
            ],
          },
        ],
      },
      instance: { storageEngine: 'ephemeralForTest' },
    });

    await instance.start();

    const baseUrl = instance.getUri('db-read');
    const url = new URL(baseUrl);
    url.username = 'my-user';
    url.password = 'my-password';
    url.pathname = 'db-read';
    url.searchParams.append('authSource', 'admin');

    const client = new MongoClient(url.href);
    const db = await client.db();

    // Exception is not throw with "ephemeralForTest" storage engine
    await expect(() => db.collection('events').insertOne({ id: 1, title: 'my-test-01' })).rejects.toThrow();

    await client.close();

    await instance.stop();
  });
});
```

**Comment by hasezoey** [comment]
> If I use the storageEngine "wiredTiger", an exception is triggered but this mode is much slower and less efficient than the "ephemeralForTest" storageEngine ?

that is to be expected, because `ephemeralForTest` completely lives only in RAM and only `wiredTiger` saves to the disk and has to sync with the disk (can be read at [Helper Type StorageEngine](https://nodkz.github.io/mongodb-memory-server/docs/api/interfaces/mongo-memory-instance-opts#helper-type-storageengine))

> When I use "mongo-memory-server" with "ephemeralForTest" storage engine, rights management does not work.
> Is that the normal behavior?

sadly, this is to be expected, because of how mongodb works:
you can only enable auth requirement or no auth requirement as a cli option and not at runtime, so you would have to re-start the server to enforce it, but `ephemeralForTest` never saves or loads from disk (even on shutdown) and (from what i know) it cannot be forced to do so.
the only workaround is to use a different storage engine, where the only other option would be `wiredTiger` (but for because `ephemeralForTest` is enough for most cases, it is the default)

>  When I try to create a document in a database on which I should not have rights, I do not have an exception that is triggered.

i am not sure how mongodb handles having specific roles with `--noauth` but still being logged in as a specific user, maybe it does never apply any rules with that option

---

This is currently not documented well, so i would like to keep this issue open as a tracker for that

**Comment by hasezoey** [comment]
>  We can use the "localhost exception" of MongoDB for avoid to restart the server ?

thanks, i didnt know this existed, i have just tried locally and everything through the mongodb nodejs driver and it seems to be working, i will make a new issue explaining everything that is needed (though i dont know when this will be done)

**Comment by SamyLegal** [comment]
Good news !

When you have some time, can you try this configuration with my unit test in this conversation ?

Is an exception triggered saying that the user does not have the right to insert a document in the "events" collection?

Thank you

**Comment by hasezoey** [comment]
> Is an exception triggered saying that the user does not have the right to insert a document in the "events" collection?

i had tested it when trying, and the answer is yes

though some special conditions (that will probably not matter to the end user once implemented, but nice to know) apply:
on instances started with `--auth` directly and not having users created, you can login without a user from localhost, but the only thing you will be able to do is create 1 user in `admin`, you cannot do any other CRUD operation anywhere, and once that one user (regardless of role) is created, your existing connection will not have any permissions anymore and need to re-login with the created user and do anything from there (so be careful to create a user with `root` or anything that is needed for admin work)

**Comment by hasezoey** [comment]
MMS `8.8.0-beta.1` should be released soon, could you test if this fixes your issue (and maybe also performance)?

**Comment by SamyLegal** [comment]
Thank you for the beta. 

I try this version today and I'll come back to you to tell you if it works

**Comment by SamyLegal** [comment]
It works perfectly for me. Thank you for your time and work.
