### ISSUE TITLE
npm build error module not found 

### ISSUE THREAD

**Issue by nitinmagdumvista** [nodkz/mongodb-memory-server#675]
Hello,

i am getting below error

Cannot find module 'mongodb-memory-server' or its corresponding type declarations.

====== package.json dependencies details 

"@types/mongodb-memory-server": "^2.3.0", 
"mongodb-memory-server": "^8.7.2",

"node": ">= 14.17.0",
    "npm": ">=5.4.1"

========== 

nest build && npm run copy:build-assets
src/common/mongodbMemoryServer.ts:1:35 - error TS2307: Cannot find module 'mongodb-memory-server' or its corresponding type declarations.
1 import { MongoMemoryServer } from 'mongodb-memory-server';

===========

**Comment by hasezoey** [comment]
`mongodb-memory-server` provides it own types, i does not need a `@types` package

aside from that i cannot tell why the error exists, the package does exist at npmjs: https://www.npmjs.com/package/mongodb-memory-server/v/8.7.2

**Comment by nitinmagdumvista** [comment]
@nodkz

**Comment by hasezoey** [comment]
now it seems like you are trying to run MMS in Alpine Linux (probably docker), which is not supported (or really possible) with mongodb, see [Supported Systems: Alpine](https://nodkz.github.io/mongodb-memory-server/docs/guides/supported-systems#alpine) and [Known-Issues: Alpine](https://nodkz.github.io/mongodb-memory-server/docs/guides/known-issues#no-build-available-for-alpine-linux)

Workarounds are:
- use a nodejs image that does not use alpine (like debian)

**Comment by hasezoey** [comment]
closing because questions seem to be solved
