### ISSUE TITLE
"Jest failed to parse a file" ... "SyntaxError: Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by hems** [nodkz/mongodb-memory-server#679]
Today i started a new project from scratch using JEST and to my surprised i encountered this error when trying to create a server using MongoMemoryServer on my `beforeEach` hook.

Do i have to tweak something on jest config to make it work? I have used this setup before with an older version of mongodb-memory-server and it worked like a charm.. Something must have changed either on mongodb-memory-server or i haven't noticed

### jest.config
```js
/** @type {import('ts-jest/dist/types').InitialOptionsTsJest} */
module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  roots: ["<rootDir>/src"],
  // the following line is needed in order to grab modules from the
  // src folder without the need to write them relatively
  moduleDirectories: ["node_modules", "src"],
};
````
### typescript test file

```ts
...
describe("POST /my-end-point", () => {
  beforeAll(async () => {
    mongod = await MongoMemoryServer.create();
    // const uri = mongod.getUri();
    // await ConnectMongoose(uri);
  });
  ...
}
```

### error
 ... " Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax." ...
 ... "/home/.../node_modules/mongodb-memory-server-core/node_modules/mongodb/src/bson.ts:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import type {"""

![image](https://user-images.githubusercontent.com/27327/179889097-85182026-8623-4230-a9be-6d42f67e10ac.png)

**Comment by hems** [comment]
Even when copying the tsconfig.json from and jest.config from the repo example i'm getting the same error :(

 - https://github.com/nodkz/mongodb-memory-server/blob/master/packages/mongodb-memory-server-core/tsconfig.json
 - https://github.com/nodkz/mongodb-memory-server/blob/master/packages/mongodb-memory-server-core/jest.config.js

here is my package.json for good measure:

````json
{
  ...
  "scripts": {
    "test": "jest",
    "test:coverage": "jest --coverage",
    "test:watch": "jest --watchAll",
    "build": "npx tsc",
    "start": "node dist/index.js",
    "dev": "concurrently \"npx tsc --watch\" \"nodemon -q dist/index.js\""
  },
  "dependencies": {
    "dayjs": "^1.11.4",
    "dotenv": "^16.0.1",
    "express": "^4.18.1",
    "mongoose": "^6.4.5",
    "tvcd": "^1.5.22"
  },
  "devDependencies": {
    "@types/express": "^4.17.13",
    "@types/jest": "^28.1.6",
    "@types/node": "^18.0.6",
    "@types/supertest": "^2.0.12",
    "concurrently": "^7.3.0",
    "jest": "^28.1.3",
    "mongodb-memory-server": "^8.7.2",
    "nock": "^13.2.9",
    "nodemon": "^2.0.19",
    "supertest": "^6.2.4",
    "ts-jest": "^28.0.7",
    "typescript": "^4.7.4"
  }
}
````

**Comment by hasezoey** [comment]
What package manager are you using?

Because it currently seems like jest somehow imports the raw `.ts` source for `mongodb` instead of the compiled `.js` files.
This behavior does not happen in plain npm and plain yarn.

PS: dont ignore the issue template, please fill it out and not remove it

**Comment by hems** [comment]
> What package manager are you using?

yarn: 1.22.17

> PS: dont ignore the issue template, please fill it out and not remove it

Sorry my bad, didn't mean to have done that it was an accident see the answers below!

I also have uploaded an example code to this public repository: https://github.com/hems/memory-mongo-error

You can ( hopefully ) reproduce the error by

```shell
git clone git@github.com:hems/memory-mongo-error.git
cd memory-mongo-error/backend
yarn install
yarn test
```

thank you for your quick reply!

## Versions

- NodeJS: 16.13.2
- mongodb-memory-server-*: ^8.7.2
- mongodb(the binary version): 0.0.0 
- mongoose: 6.4.5
- system: manjaro linux

package: mongo-memory-server 

## What is the Problem?
described up in the first post

## Code Example

see original post

**Comment by hasezoey** [comment]
i have tried the reproduction-repo and can reproduce it, i could also single it down to the jest option `moduleDirectories`, which when manually set seems like jest will search all specified paths for all possible file extension (seemingly regardless what nested `package.json` files specify)

things you could try to workaround this issue:
- change the option from just `src` to `<rootdir>/src`
- replace the option with option `modulePaths: ["<rootdir>/src"]`
- disable the option and use [tsconfig `paths`](https://www.typescriptlang.org/tsconfig#paths)
- disable the option and use relative paths

Note: i have never used such path mapping before, so i dont know if the listed workaround will work properly, i also have never used this jest option, so i also dont know how to handle that properly
but i know that this does not seem to be a problem with MMS

**Comment by hems** [comment]
> i have tried the reproduction-repo and can reproduce it, i could also single it down to the jest option `moduleDirectories`, which when manually set seems like jest will search all specified paths for all possible file extension (seemingly regardless what nested `package.json` files specify)
> 
> things you could try to workaround this issue:
> 
> * change the option from just `src` to `<rootdir>/src`
> * replace the option with option `modulePaths: ["<rootdir>/src"]`
> * disable the option and use [tsconfig `paths`](https://www.typescriptlang.org/tsconfig#paths)
> * disable the option and use relative paths
> 
> Note: i have never used such path mapping before, so i dont know if the listed workaround will work properly, i also have never used this jest option, so i also dont know how to handle that properly but i know that this does not seem to be a problem with MMS

thanks a lot for having a look at this, i'll report back on how i worked around this.

**Comment by hems** [comment]
> * change the option from just `src` to `<rootdir>/src`

this seems to solve the situation!

**Comment by Serge-boro** [comment]
in package.json add (in my case I'm testing components in node.js)
  "jest": {
    "preset": "ts-jest",
    "testEnvironment": "node",
    "setupFilesAfterEnv": [
      "./src_root_for_test_file.ts"
    ]
  },
