### ISSUE TITLE
drop fs-extra dependency to avoid memory leak on jest tests

### ISSUE THREAD

**Issue by sibelius** [nodkz/mongodb-memory-server#68]
it looks like fs-extra depends on graceful-fs that is causing jest to leak

check this https://github.com/facebook/jest/issues/6738
and https://github.com/isaacs/node-graceful-fs/issues/102

can we avoid using fs-extra in this module?

**Comment by nodkz** [comment]
Сool research! Thanks!

**Comment by sibelius** [comment]
tks, our tests are still leaking
