### ISSUE TITLE
HTTP Redirection cause download to fail

### ISSUE THREAD

**Issue by jcviau** [nodkz/mongodb-memory-server#689]
## Versions

- NodeJS: 13.7
- mongodb-memory-server-*:  6.6.1, 8.9.0
- mongodb(the binary version): 4.2.8 or default 
- mongoose: 5.9.20 
- system: Linux

package: 
mongo-memory-server
mongo-memory-server-core

## What is the Problem?

When doing npm install, the download of mongodb fail with this error: Mongodb-Memory-Server* failed to find an binary:
 Status Code isnt 200!

The http call that fail is https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian92-4.2.8.tgz. This call return a status code 302 (redirection) with a new url to continue the download. Since the status code is not 200, the code raise an error (https://github.com/nodkz/mongodb-memory-server/blob/master/packages/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts#L434). 

Note: If I paste that url in a browser, it will download the file as it follow the redirection.

## Do you know *why* it happenes?

Could fix the issue by doing another http request with the response.headers.location when the status code is 302. The response header contains the redirection url.

**Comment by hasezoey** [comment]
currently the download that is made is not following any redirections and will only given back the status code (plus the redirection header), so another request has to be made, but this is currently not implemented

also i have tried the URL and at least for me there is no redirection, are you maybe behind a proxy?

**Comment by jcviau** [comment]
I am probably behind a proxy, that would explain the redirection. Will close this issue as the documentation mention it.
