### ISSUE TITLE
Can I use watch() (change streams) with mongodb-memory-service?

### ISSUE THREAD

**Issue by ErlendFax** [nodkz/mongodb-memory-server#694]
When using `watch(...).on(...)` with tests I get `Unhandled error. (MongoServerError: The $changeStream stage is only supported on replica sets`. 

Is it possible to configure it to work?

**Comment by hasezoey** [comment]
like the error says, Change-Streams are only available on Replica Sets, read [Change Streams
](https://www.mongodb.com/docs/manual/changeStreams/)

in MMS you can configure a ReplicaSet with the class `MongoMemoryReplSet`, read [Quick-Start-Guide: ReplicaSet](https://nodkz.github.io/mongodb-memory-server/docs/guides/quick-start-guide#replicaset)

**Comment by hasezoey** [comment]
>     this.model.watch().on("change", callback);

that code looks like it will block until it gets *something*, and so your callback will not get executed until it gets something

aside from that i cannot really help with the information provided because i dont know where or how this will be executed

> But, when using watch in jest it seems like it makes all calls to MMS hang

make sure the instances get created and stay open, see [Integration with Test Runners: jest](https://nodkz.github.io/mongodb-memory-server/docs/guides/integration-examples/test-runners#jest) for how to set-up MMS for jest

**Comment by ErlendFax** [comment]
Tried the code in a working environment now and `watch` works fine there. Still can't get this working with tests and MMS.

MMS works fine with the current configuration for all other tests. If the only thing `watch` need is replica sets, then I don't really know what to try. Setting up a similar mockup project to debug this will take some time, we have a few files spread out to setup and config our tests.

**Comment by hasezoey** [comment]
> If the only thing watch need is replica sets, then I don't really know what to try

i dont know what you had already tried, but replacing a mms instance with a mms replica set instance should be "as easy as" replacing:
```ts
const instance = new MongoMemoryServer({ ...option });
await instance.start();
```
with
```ts
const instance = new MongoMemoryReplSet({ ...replsetOptions }); // without custom options, the default replset count is 1
await instance.start();
```
i dont know what custom options are used, so i cant quite tell how to migrate them (the options are not yet easy to migrate from instance to replset, depending on the option), but for all options see [MongoMemoryReplSetOpts](https://github.com/nodkz/mongodb-memory-server/blob/edb003f5b46be100cca8fd08c9779159891962b5/packages/mongodb-memory-server-core/src/MongoMemoryReplSet.ts#L109-L123) (not yet included in the documentation, will add later)

**Comment by ErlendFax** [comment]
Hmm, we start the instance using the address in another package, maybe that has something to do with it?

Below is how we setup stuff (renamed some vars and functions), lots of wrappers, sorry about that. But the TLDR is that we create a replica set with MMS, get the adress with `getUri`, then in another package we import a new `mongoose` like this: `import mongoose, { Mongoose } from "mongoose";` and then use **that** to `connect(address)`.

Regular tests run fine with replicaset it seems, but the second I use watch it all hangs.

<details>
<summary>How we set up mongoose</summary>

```typescript
// ... main-ish.ts
const mongodb = await MongoMemoryReplSet.create({ replSet: { count: 3 } });
const mongoConnectionUrl = mongodb.getUri();

const mongooseInstance = await setupMongoose(mongoConnectionUrl);
const repository = bootstrapRepository({
    mongooseInstance,
  });

const settings = await repository.readAll(...)
// ...
```

```typescript
// setupMongoose.ts
import { connectToMongoose } from "@erlend/util";
import mongoose, { Mongoose } from "mongoose";

export async function setupMongoose(connectionUri: string): Promise<Mongoose> {
  await connectToMongoose(mongoose, connectionUri);
  return mongoose;
}
```


```typescript
export function bootstrapRepository({
  mongooseInstance,
}: {
  mongooseInstance: Mongoose;
}): MongooseRepository {
  const model = mongooseInstance.model<MongooseDocument>(
    MONGOOSE_COLLECTION_NAME,
    MongooseSchema
  );
  return new MongooseRepository({
    model,
  });
}
```

```typescript
// connectToMongoose.ts
import { Mongoose } from "mongoose";

export function connectToMongoose(
  mongooseInstance: Mongoose,
  connectionUri: string
): Promise<Mongoose> {
  return mongooseInstance.connect(connectionUri);
}
}
```

</details>

**Comment by hasezoey** [comment]
i just tried it locally (i did not before, because i never used changestreams), and noticed that you need to set the `storageEngine` to `wiredTiger` (default is `ephermeralForTest`), because otherwise the connection will hang and eventually result in a `ECONNREFUSED` (with a weird error saying `no primary`)

For the full code / example i used, see Repository / Branch: https://github.com/typegoose/typegoose-testing/tree/mmsChangeStreams

**Comment by ErlendFax** [comment]
Thanks for taking a look. Unfortunately, changing the `storageEngine` did not help.

When using `wiredTiger` it also hangs when calling watch. The default storageEngine hangs when writing or reading from mms.

"mongodb-memory-server": "^8.9.2

**Comment by hasezoey** [comment]
> When using wiredTiger it also hangs when calling watch.

weird, maybe make sure that at the point of calling `.watch` your mongoose instance / connection is connected before calling the function

> The default storageEngine hangs when writing or reading from mms.

in relation to watch or also in general? if in general, it shouldnt do this - make sure the instance is running and the connection is connected

**Comment by ErlendFax** [comment]
I actually just disabeld watch for

**Comment by hasezoey** [comment]
> Any tips on how I can debug this, or test the connection and ensure its kept open?

if you use mongoose, you could before the watch call log out `connection._readyState` and `connection.states`(the enum for states) and compare those 2 to be connected (the enum does not did not change in recent versions, so look for `readyState` `1`)
i dont know if mongoose will log anything for this in debug, but you could also try setting `mongoose.set('debug', true)`
Note: replace `connection` with the connection you are using, for example `Model.db._readyState` (`db` is the connection the model uses)

**Comment by Rushabh1798** [comment]
Hi All,

Recently I tried using `watch` with `MongoMemoryReplSet` and getting following error,

> `MongoTopologyClosedError: Topology is closed`

`MongoMemoryReplSet`  is configured as below,
> `await MongoMemoryReplSet.create({
                    instanceOpts: [
                        { port: 27017 },
                        { port: 27018 },
                        { port: 27019 }
                    ]
                });`

Created and Used `ChangeStream` as follows,
> `const changeStream = collection.watch();`
> `changeStream.on("change",  (change) => {
console.log(change);
}`
> `changeStream.on("error", async (error) => {
console.error(error);
}`

I am sure that the connection to the server is kept alive, still `MongoTopologyClosedError: Topology is closed` is sent in `error` event of `changeStream`.

Also tried configuring different numbers of replicas in `instanceOpts` option, with distinct ports.

Is there any `MongoMemoryReplSet` configuration mistake or other suggestion to try and make this working..?? 

Thanks & Regards,
Rushabh.

**Comment by hasezoey** [comment]
@Rushabh1798 aside from `watch` needing ReplSet's, it also has the requirement of the `storageEngine` to be `wiredTiger`, but by default the engine is `ephermeralForTest`, try setting `storageEngine: "wiredTiger"` (because you are defining individual instances with ` instanceOpts`, you will need to put it in each object in the array)

**Comment by Rushabh1798** [comment]
Thank you very much @hasezoey. It worked like a charm..!!
Following configuration of `MongoMemoryReplSet` worked for me,

> `await MongoMemoryReplSet.create({
                    instanceOpts: [
                        { port: 27017, storageEngine: "wiredTiger" },
                        { port: 27018, storageEngine: "wiredTiger" },
                        { port: 27019, storageEngine: "wiredTiger" }
                    ]
                })`

Also, `watch` works with single replica set too,
> `await MongoMemoryReplSet.create({
                    instanceOpts: [
                        { port: 27017, storageEngine: "wiredTiger" }
                    ]
                })`

Thanks for quick reply..!!
Regards,
Rushabh.
