### ISSUE TITLE
Consider adding `mongodChildProcess.unref()`

### ISSUE THREAD

**Issue by hasezoey** [nodkz/mongodb-memory-server#696]
Consider adding `mongodChildProcess.unref()`, this should make it possible for nodejs to exit even if the mongod process did not exit yet, this should be good for when no `.stop` is called or some tests terminate early and somehow dont call `.stop`

**Comment by meyfa** [comment]
This would be a very welcome change, indeed! We are currently struggling with unit tests not exiting, which is near impossible to debug. This change would either fix the problem or indicate that the problem lies elsewhere.

**Comment by hasezoey** [comment]
done with 59ec785e59f206e78093e96a0652466730650136
