### ISSUE TITLE
Ship with MongoDB version 6 by default

### ISSUE THREAD

**Issue by meyfa** [nodkz/mongodb-memory-server#699]
mongodb-memory server 8.9.3 uses MongoDB 5.0.8 by default. Currently, MongoDB 6.0.1 is available and 6.0.2 is upcoming: https://www.mongodb.com/docs/manual/release-notes/6.0/

I'd like to ask whether mongodb-memory-server can use version 6 by default? Currently I am setting it manually:

```
const mongod = await MongoMemoryServer.create({
    binary: {
      version: '6.0.1'
    }
  })
```

This has worked absolutely flawlessly, but I'd prefer not having to override the version.

**Comment by hasezoey** [comment]
Please dont ignore the issue template

---

We have a plan for this, see [When a Version gets upgraded](https://nodkz.github.io/mongodb-memory-server/docs/guides/mongodb-server-versions#when-a-version-gets-upgraded)

also there are some other ways to define a version in case you want it more "outside" of your code:
- with a option in the package.json
- with a environment variable

both of which also affect the version installed in the postinstall script
