### ISSUE TITLE
Deprecation warning in Mongoose 4.11.0

### ISSUE THREAD

**Issue by zellwk** [nodkz/mongodb-memory-server#7]
Got a warning when using with Mongoose 4.11.0 and above: 

(node:9265) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client

**Comment by aluxian** [comment]
https://github.com/Automattic/mongoose/issues/5399

Upgrade to 4.11.1 or newer

**Comment by nodkz** [comment]
Yep, this is mongoose problem.
Had the same warnings about 2 weeks. Now it is fixed in last version of mongoose.
