### ISSUE TITLE
add documentation website to github website repo settings

### ISSUE THREAD

**Issue by sibelius** [nodkz/mongodb-memory-server#700]
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/2005841/193300033-505a86ac-ff3c-4584-a572-f7e24aaec7d8.png">

**Comment by hasezoey** [comment]
please explain what this issue is about, i dont quite understand from just the title
this project has a documentation already up at https://nodkz.github.io/mongodb-memory-server/ and is also mentioned in the main README

**Comment by sibelius** [comment]
like this

<img width="283" alt="image" src="https://user-images.githubusercontent.com/2005841/193318976-d1808f1c-f253-448a-9599-90bf36ba3cbd.png">

inside About

**Comment by nodkz** [comment]
Tnx, I just added it.
