### ISSUE TITLE
Question: Mongo binary being downloaded twice in CI/CD

### ISSUE THREAD

**Issue by svitekpavel** [nodkz/mongodb-memory-server#704]
## Versions

- NodeJS: 14.20.1
- mongodb-memory-server-global-*: 8.9.3
- mongodb(the binary version): 4.0.28
- mongodb(the js package): 0.0.0
- mongoose: 5.9.7 
- system: Linux (Docker image gliderlabs/herokuish:latest), x64-ubuntu-4.0.28

package: mongo-memory-server-global-4.0 

## What is your question?

I'm running tests in Gitlab CI/CD with `gliderlabs/herokuish:latest`. For some reason, the binary is downloaded twice. 

1. First time it's downloaded (correctly) in `post_install` hook
2. Second time, it's downloaded when 1st test (where MongoDB is used) is run. 

It seems that I'm doing something wrong in how I configure/connect to Mongo memory server.

```ts
import consola from 'consola'
import mongoose from 'mongoose'
import { MongoMemoryServer } from 'mongodb-memory-server-global-4.0'
import Container from 'typedi'

// import all models (code removed)

let mongoServer: MongoMemoryServer

export const mongoMemory = {
  async connect() {
    try {
      const instance = await MongoMemoryServer.create()
      mongoServer = instance

      const uri = instance.getUri()
      // console.log({ uri })
      // Do NOT set global MONGOINSTANCE, otherwise only one will be created
      // ;(global as any).__MONGOINSTANCE = instance
      process.env.MONGO_URI = uri.slice(0, uri.lastIndexOf('/'))

      const dbUri = process.env.MONGO_URI as string
      // consola.info(`Connecting to Mongo memory server: ${dbUri}`)
      const connection = await mongoose.connect(dbUri, {
        useNewUrlParser: true,
        useUnifiedTopology: true,
      })

      Container.set('db', connection)

      // Configure models
      // ...

      // The following is to make sure the database is clean before a test starts
      await mongoose.connection.db.dropDatabase()

      return connection
    } catch (err) {
      consola.error(err)
      throw err
    }
  },

  async close() {
    await mongoose.disconnect()
    await mongoServer.stop()
  },

  getUri() {
    return mongoServer.getUri()
  },

  async clear() {
    const collections = mongoose.connection.collections

    for (const key in collections) {
      const collection = collections[key]
      await collection.deleteMany({})
    }
  },
}
```

This is how I import in tests (I want to have new/clean database instance for every unit test

```ts
import Container from 'typedi'
import mongoose, { Mongoose } from 'mongoose'

import { mongoMemory } from '../../testing/mongo-memory-utils'

beforeAll(async () => {
  jest.setTimeout(60000)

  // Create connection
  const db = await mongoMemory.connect()

  // Create Agenda
  const dbUri = await mongoMemory.getUri()

  Container.set('db', db)
})

afterEach(async () => {
  await mongoMemory.clear()
})

afterAll(async () => {
  const agenda: Agenda = Container.get('agenda')
  await agenda.stop()
  // @ts-ignore
  await agenda._db.close(true)

  await mongoMemory.close()
})

```

⬇️ Download: post_install (good)

<img width="1144" alt="post-install-download" src="https://user-images.githubusercontent.com/988706/195308933-697a8170-4958-47f7-9001-3f0366d40c8f.png">

⬇️ Download: when running first test (not good)

<img width="1111" alt="first-test-download" src="https://user-images.githubusercontent.com/988706/195308957-113a2677-d57b-4608-9d60-b243321f7ccc.png">

**Comment by hasezoey** [comment]
> mongodb-memory-server-global-*: 0.4.0

that does not look correct, guessing from the screenshot you are using `8.9.0` (latest is `8.9.3`)

---

could you provide the gitlab CI config? (it may be that something is cleared or not transferred between jobs)

also it would be helpful if you could provide [Debug Logs](https://nodkz.github.io/mongodb-memory-server/docs/guides/enable-debug-mode) for both runs (both postinstall and runtime)

**Comment by svitekpavel** [comment]
> > mongodb-memory-server-global-*: 0.4.0
> 
> that does not look correct, guessing from the screenshot you are using `8.9.0` (latest is `8.9.3`)
> 
> could you provide the gitlab CI config? (it may be that something is cleared or not transferred between jobs)
> 
> also it would be helpful if you could provide [Debug Logs](https://nodkz.github.io/mongodb-memory-server/docs/guides/enable-debug-mode) for both runs (both postinstall and runtime)

Thanks a lot for prompt reply!

1. You are correct. It was `8.9.3`, upgraded now to `8.9.3` for the debug run
2. Extract from `gitlab-ci.yml`
3. I'm attaching logs from the CI test job with enabled debug [tetst-job-logs.txt](https://github.com/nodkz/mongodb-memory-server/files/9764516/tetst-job-logs.txt)



```yaml
stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: gliderlabs/herokuish:latest
  variables:
    CI_ENVIRONMENT_NAME: app-development
  needs: []
  script:
    - cp -R . /tmp/app
    - /bin/herokuish buildpack test
  tags:
    - test, development
  rules:
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'
```

**Comment by hasezoey** [comment]
> Extract from gitlab-ci.yml

i dont quite understand your gitlab ci, from what i can tell `/bin/herokuish buildpack test` is the thing that actually runs the tests, but where does it get installed and also why is there a extra `cp -R . /tmp/app` (asking just to be sure)

---

i can confirm from the log that somehow the file does not exist anymore when going to the test step, could you maybe add the following command before running tests: `ls -al /app/.cache/mongodb-binaries/` (put before your testing line) and provide the output?

**Comment by svitekpavel** [comment]
> > Extract from gitlab-ci.yml
> 
> i dont quite understand your gitlab ci, from what i can tell `/bin/herokuish buildpack test` is the thing that actually runs the tests, but where does it get installed and also why is there a extra `cp -R . /tmp/app` (asking just to be sure)
> 
> i can confirm from the log that somehow the file does not exist anymore when going to the test step, could you maybe add the following command before running tests: `ls -al /app/.cache/mongodb-binaries/` (put before your testing line) and provide the output?

You are right, the `herokuish` image (for some reason) cleans/removes the `/app/.cache` directory after the `npm install` script. It's quite strange. I think I will have to use another image for running tests.

Thanks a lot for help.

**Comment by hasezoey** [comment]
> You are right, the `herokuish` image (for some reason) cleans/removes the `/app/.cache` directory after the `npm install` script. It's quite strange. I think I will have to use another image for running tests.

thanks for the information, though this is definitely weird

if you want to keep using that image, you can try the following workarounds:
- set [`PREFER_GLOBAL_PATH`](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#prefer_global_path) to `false`
- set [`DOWNLOAD_DIR`](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#download_dir) to a custom path that you know wont be cleared

(also read [How to use them in the package.json](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#how-to-use-them-in-the-packagejson) and [How to use them as Environment Variables](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#how-to-use-them-as-environment-variables), also some options can also be set as options at instance creation time)
