### ISSUE TITLE
unnable to insert data with new Date() with node javascript

### ISSUE THREAD

**Issue by chengtangzheng2021** [nodkz/mongodb-memory-server#708]
## Versions

- NodeJS: 0.0.0
- mongodb-memory-server-*: 0.0.0 
- mongodb(the binary version): 0.0.0 
- mongodb(the js package): 0.0.0 
- mongoose: 0.0.0 
- system: 

package: mongo-memory-server 

## What is the Problem?

The tested application mongodb has data as:
`"startOn" : ISODate("2022-01-25T00:00:00.000Z")`
Mongodb memory server can not insert `{"startOn" : ISODate("2022-01-25T00:00:00.000Z")}`
But can instert `{"startOn" : "2022-01-25T00:00:00.000Z" }`
This format inserted data, can not be queried by app's query
The app's query is working with data `{"startOn" : ISODate("2022-01-25T00:00:00.000Z")}` in Mongo 
insert `{"startOn" : new Date("2022-01-25T00:00:00.000Z")}` also not working
how to get `{"startOn" : ISODate("2022-01-25T00:00:00.000Z")}` into memory db?

## Code Example
```ts
const connect = async () => {
    mongod = await MongoMemoryServer.create();
    const uri = mongod.getUri();
    process.env.MONGO_URL = uri;
    process.env.MDB_NAME = 'PricerDB_EMEA';
    const db = await mongoHelper.getMongoClientDb();
    db.collection('adjustmentsDetails').insertOne({"startOn" : new Date("2022-01-25T00:00:00.000Z")} );
}
```

## Debug Output

<details>
<summary>Debug Output</summary>

```txt
Put The Debugout output here
```

</details>

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment]
i dont see any reason on why it would not work, it is a normal mongodb server instance, and the operation used is not something that is limited to something like atlas.

please provide more information on what is not working (like errors) and [debug output](https://nodkz.github.io/mongodb-memory-server/docs/guides/enable-debug-mode).

also, you did not correctly fill out the template (like versions, debug output, or putting the code example in the code block).
