### ISSUE TITLE
MongoDB always runs on default random port

### ISSUE THREAD

**Issue by Lanchi** [nodkz/mongodb-memory-server#71]
In memory Mongo is instantiated like this:
`const mongod = new MongodbMemoryServer.default({
    instance: {
        dbName: 'my-test-db',
        port: 12345
    }
})`

It's expected to have MongoDB running on port 12345, but that's not the case. Calling `getConnectionString` and `getPort` show that MongoDB is actually running on some default random port (e.g. `mongodb://localhost:54271/my-test-db`).

This started happening on version `1.9.3` and also happens on `2.0.0`.

**Comment by sjones6** [comment]
I'm also experiencing this issue. I've downgraded to `1.9.1` and it continues to work. 

Looks like (this commit)[https://github.com/nodkz/mongodb-memory-server/commit/0c030fc37da7aa654d783ac8d5446d201457a8d9] updated the `get-port` to next major version which could be causing the trouble.
