### ISSUE TITLE
Problem with `ps` not there when installing

### ISSUE THREAD

**Issue by bacloud23** [nodkz/mongodb-memory-server#711]
I have a docker image which does not have `ps` installed (https://stackoverflow.com/a/26982502).  When I run `yarn add mongodb-memory-server` I have such error:

> imggg          |
> imggg          | [11:42:16 AM] Found 0 errors. Watching for file changes.
> imggg          |
> imggg          | /bin/sh: 1: ps: not found
> imggg          | events.js:377
> imggg          |       throw er; // Unhandled 'error' event
> imggg          |       ^
> imggg          |
> imggg          | Error: spawn ps ENOENT
> imggg          |     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
> imggg          |     at onErrorNT (internal/child_process.js:469:16)
> imggg          |     at processTicksAndRejections (internal/process/task_queues.js:82:21)
> imggg          | Emitted 'error' event on ChildProcess instance at:
> imggg          |     at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
> imggg          |     at onErrorNT (internal/child_process.js:469:16)
> imggg          |     at processTicksAndRejections (internal/process/task_queues.js:82:21) {
> imggg          |   errno: -2,
> imggg          |   code: 'ENOENT',
> imggg          |   syscall: 'spawn ps',
> imggg          |   path: 'ps',
> imggg          |   spawnargs: [ '-o', 'pid', '--no-headers', '--ppid', 115 ]
> imggg          | }
> imggg          | error Command failed with exit code 1.
> imggg          | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I strongly believe this is because of `mongodb-memory-server`

**Comment by hasezoey** [comment]
from what i know, MMS does not have any script that uses `ps`.
`sh` is only set and used for development scripts (like git pre-commit), and is not used at runtime / package-install time.

**Comment by bacloud23** [comment]
ok, thanks for the quick reply !
when I do as they suggest: `apt-get update && apt-get install procps`, I no longer have an error, I then have another error (but I know what's about: node-gyp complaining about `make` not found :))

**Comment by hasezoey** [comment]
`node-gyp` is not used by MMS, so this is not the place for questions about it (i could not help with it)

**Comment by bacloud23** [comment]
true; it is about `unix-dgram`, but as I said, this is not the first problem to begin with, this was an indication for me when I installed `ps` that was a sollution ! I hope you get the idae

**Comment by bacloud23** [comment]
Excuse me, this is irrelevant to this package. My error I believe was because of my process manager.
