### ISSUE TITLE
Should allow native Apple Sillicon support since Mongo 6.X

### ISSUE THREAD

**Issue by Moumouls** [nodkz/mongodb-memory-server#714]
## Versions

- NodeJS: 16
- mongodb-memory-server-*: 8.9.5 
- mongodb(the binary version): 6.X 
- mongodb(the js package): 0.0.0 
- mongoose: 0.0.0 
- system: Mac OS Apple Sillicon

package: mongo-memory-server

## What is the Problem?

MongoDB now support Apple Sillicon natively (bin download URL example: https://fastdl.mongodb.org/osx/mongodb-macos-arm64-6.0.2.tgz)

I found the following code

```js
        if (this.arch === 'aarch64') {
            log('getArchiveNameOsx: Arch is "aarch64", using x64 binary');
            this.arch = 'x86_64';
        }
```

Starting mongo 6.X, the arch x86 should not be forced.

The current workaround I'm using to be able to use native MongoDB on M1

```js
if (process.arch === "arm64" && process.platform === "darwin") {
  process.env.MONGOMS_DOWNLOAD_URL = "https://fastdl.mongodb.org/osx/mongodb-macos-arm64-6.0.2.tgz"
}
```

## Code Example

No code

## Debug Output

<details>
<summary>Debug Output</summary>

```txt
spawn Unknown system error -86spawn Unknown system error -86, Is Rosetta Installed and Setup correctly?
```

</details>

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment]
the support for `6.0.0` and up is in `8.10.0`, please test to confirm that these binaries actually work as intended (i dont have a mac device)

**Comment by Moumouls** [comment]
@hasezoey it's working perfectly and is also see that you updated the docs so it's perfect !

Thanks for your reactivity!

**Comment by maximilianschmid** [comment]
Thanks for supporting Apple Silicon!

**Comment by hasezoey** [comment]
@Attrash-Islam if you dont set a custom version, then 5.0.x will be used, to get macos arm binaries you will have to manually set a version that is 6.0.2 or higher, see [Config Options: VERSION](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#version)

**Comment by Attrash-Islam** [comment]
Will try this next week! Thanks!
