### ISSUE TITLE
Mongo 6.0 support

### ISSUE THREAD

**Issue by k2xl** [nodkz/mongodb-memory-server#718]
How does Mongo Memory Server work with new features in Mongo 6 and new features that it supports? For example, `partialFilterExpression` supports `$or` and `$in` in Mongo 6 but not Mongo 5.

**Comment by hasezoey** [comment]
i dont quite understand your question, MMS (short for mongodb-memory-server) supports mongodb binary version 6.x, and MMS does not interfere with queries, that is as if you run your own `mongod` instance manually (which this package just automates)
