### ISSUE TITLE
Launch timeout triggers during lazy download

### ISSUE THREAD

**Issue by Jomshir98** [nodkz/mongodb-memory-server#719]
## Versions

- NodeJS: v18.12.1
- mongodb-memory-server-core: 8.10.0
- system: Tested on multiple platforms (Win+Linux)

package: mongo-memory-server-core

## What is the Problem?

When mongodb binary isn't already downloaded, the launch timeout triggers during the download process

## Code Example

```ts
return await MongoMemoryServer.create({
	binary: {
		version: '5.0.6',
		checkMD5: false,
	},
	instance: {
		args: ['--setParameter', 'diagnosticDataCollectionEnabled=false'],
	},
});
```

## Debug Output

```txt
Instance failed to start within 10000ms
```

## Do you know *why* it happens?

Yes: Timeout created at https://github.com/nodkz/mongodb-memory-server/blob/c4756c43475991bc68a0be66e4531041b73dfa13/packages/mongodb-memory-server-core/src/util/MongoInstance.ts#L348-L374
starts before call to `await MongoBinary.getPath(this.binaryOpts);` (which lazy-downloads the binary), meaning the timeout times out during slow download too.
Fix could be moving `await MongoBinary.getPath(this.binaryOpts);` before the timeout start.

**Comment by hasezoey** [comment]
thanks for reporting, didnt consider this - version should be published in ~10min as `8.10.1`
