### ISSUE TITLE
ENOTFOUND when trying to connect 

### ISSUE THREAD

**Issue by rommguy** [nodkz/mongodb-memory-server#73]
After coping the code from the Readme, when trying to connect I get this error - 

failed to connect to server [localhost:52141] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND localhost localhost:52141]

The mongoUri returned from  getConnectionString is 
"mongodb://localhost:52141/62448dc5-37f7-4158-a47e-e8e3b3b4a2c9"

I'm using mongoose 5.2.9
What am I missing ?
Thanks

**Comment by nodkz** [comment]
Please use `debug: true` option and post here your output.

**Comment by rommguy** [comment]
Mongo[53357] Starting MongoDB instance with following options: {"port":53357,"dbName":"c7f67e84-beb8-4c69-8c5c-d6f884924534","uri":"mongodb://localhost:53357/c7f67e84-beb8-4c69-8c5c-d6f884924534","storageEngine":"ephemeralForTest","dbPath":"/var/folders/81/v_z30jtn7rx1l6jwphrbr5000000gn/T/mongo-mem-449442g7byUjJf2dF"} +0ms
  Mongo[53357] MongoBinary: Mongod binary path: /Users/guyromm/.mongodb-binaries/latest/mongod +2ms
  Mongo[53357] MongoBinary: Download lock removed +6ms
  Mongo[53357] 2018-08-27T06:44:24.285+0300 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
  Mongo[53357]  +26ms
  Mongo[53357] 2018-08-27T06:44:24.297+0300 I CONTROL  [initandlisten] MongoDB starting : pid=44945 port=53357 dbpath=/var/folders/81/v_z30jtn7rx1l6jwphrbr5000000gn/T/mongo-mem-449442g7byUjJf2dF 64-bit host=Guys-MacBook-Pro.local
  Mongo[53357] 2018-08-27T06:44:24.297+0300 I CONTROL  [initandlisten] db version v3.7.9-154-g51dce76
  Mongo[53357]  +11ms
  Mongo[53357] 2018-08-27T06:44:24.297+0300 I CONTROL  [initandlisten] git version: 51dce76324173089098e8c9fd09e46b98b32adc4
  Mongo[53357] 2018-08-27T06:44:24.297+0300 I CONTROL  [initandlisten] allocator: system
  Mongo[53357] 2018-08-27T06:44:24.297+0300 I CONTROL  [initandlisten] modules: none
  Mongo[53357] 2018-08-27T06:44:24.297+0300 I CONTROL  [initandlisten] build environment:
  Mongo[53357] 2018-08-27T06:44:24.297+0300 I CONTROL  [initandlisten]     distarch: x86_64
  Mongo[53357] 2018-08-27T06:44:24.297+0300 I CONTROL  [initandlisten]     target_arch: x86_64
  Mongo[53357] 2018-08-27T06:44:24.297+0300 I CONTROL  [initandlisten] options: { net: { port: 53357 }, security: { authorization: "disabled" }, storage: { dbPath: "/var/folders/81/v_z30jtn7rx1l6jwphrbr5000000gn/T/mongo-mem-449442g7byUjJf2dF", engine: "ephemeralForTest" } }
  Mongo[53357]  +0ms
  Mongo[53357] 2018-08-27T06:44:24.303+0300 I CONTROL  [initandlisten] 
  Mongo[53357] 2018-08-27T06:44:24.303+0300 I CONTROL  [initandlisten] ** NOTE: This is a development version (3.7.9-154-g51dce76) of MongoDB.
  Mongo[53357] 2018-08-27T06:44:24.303+0300 I CONTROL  [initandlisten] **       Not recommended for production.
  Mongo[53357] 2018-08-27T06:44:24.303+0300 I CONTROL  [initandlisten] 
  Mongo[53357] 2018-08-27T06:44:24.303+0300 I CONTROL  [initandlisten] ** WARNING: This server is bound to localhost.
  Mongo[53357]  +6ms
  Mongo[53357] 2018-08-27T06:44:24.303+0300 I CONTROL  [initandlisten] **          Remote systems will be unable to connect to this server. 
  Mongo[53357] 2018-08-27T06:44:24.303+0300 I CONTROL  [initandlisten] **          Start the server with --bind_ip <address> to specify which IP 
  Mongo[53357] 2018-08-27T06:44:24.303+0300 I CONTROL  [initandlisten] **          addresses it should serve responses from, or with --bind_ip_all to
  Mongo[53357] 2018-08-27T06:44:24.303+0300 I CONTROL  [initandlisten] **          bind to all interfaces. If this behavior is desired, start the
  Mongo[53357] 2018-08-27T06:44:24.303+0300 I CONTROL  [initandlisten] **          server with --bind_ip 127.0.0.1 to disable this warning.
  Mongo[53357] 2018-08-27T06:44:24.303+0300 I CONTROL  [initandlisten] 
  Mongo[53357] 2018-08-27T06:44:24.303+0300 I CONTROL  [initandlisten] 
  Mongo[53357] 2018-08-27T06:44:24.303+0300 I CONTROL  [initandlisten] ** NOTE: The ephemeralForTest storage engine is for testing only. 
  Mongo[53357] 2018-08-27T06:44:24.303+0300 I CONTROL  [initandlisten] **       Do not use in production.
  Mongo[53357]  +0ms
  Mongo[53357] 2018-08-27T06:44:24.303+0300 I CONTROL  [initandlisten] 
  Mongo[53357]  +1ms
  Mongo[53357] 2018-08-27T06:44:24.308+0300 I STORAGE  [initandlisten] createCollection: admin.system.version with provided UUID: 32c711d6-c0c5-44bd-8f0f-539902c3b457
  Mongo[53357]  +4ms
  Mongo[53357] 2018-08-27T06:44:24.308+0300 I COMMAND  [initandlisten] setting featureCompatibilityVersion to 4.0
  Mongo[53357]  +1ms
  Mongo[53357] 2018-08-27T06:44:24.309+0300 I STORAGE  [initandlisten] createCollection: local.startup_log with generated UUID: 505eae10-04c7-42c6-9e38-6b8038c037b8
  Mongo[53357]  +0ms
  Mongo[53357] 2018-08-27T06:44:24.309+0300 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/var/folders/81/v_z30jtn7rx1l6jwphrbr5000000gn/T/mongo-mem-449442g7byUjJf2dF/diagnostic.data'
  Mongo[53357]  +0ms
  Mongo[53357] 2018-08-27T06:44:24.311+0300 I NETWORK  [initandlisten] waiting for connections on port 53357
  Mongo[53357]  +2ms
  Mongo[53357] MongodbInstance: is ready! +0ms

Than this error on connect - 
failed to connect to server [localhost:53357] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND localhost localhost:53357]

**Comment by nodkz** [comment]
It's very strange. By provided debug output all looks legit. mongodb-memory-server works as expected. The problem somewhere in your test file or machine.
Can you provide your test case?

PS. Also try to change obtained host in `uri`:
```js
let uri = await mongod.getConnectionString();
uri = uri.replace('localhost', '127.0.0.1'); // maybe some problems with resolving `localhost` on you machine, eg. it points on ipv6 or other ip address than 127.0.0.1
```

PSS. Maybe helps some timeout before connection:
```js
const uri = await mongod.getConnectionString();
await new Promise(resolve => { setTimeout(resolve, 5000); }); // lets wait 5 second before connection to MongoDB
```

----

Firstly we need to resolve the error and obtain a working solution. After that we can optimize it, put fix to the code or add some note to README.md.

**Comment by nodkz** [comment]
BTW what OS do you using?

**Comment by rommguy** [comment]
Thank you very much.
This fixed it - uri = uri.replace('localhost', '127.0.0.1')

I'm, using OSX

**Comment by nodkz** [comment]
Thanks for the feedback. For a new package version, this problem will be fixed.
