### ISSUE TITLE
Using MongoDB version 6

### ISSUE THREAD

**Issue by geryb-bg** [nodkz/mongodb-memory-server#741]
## Versions

- NodeJS: 16.18.1
- mongodb-memory-server: 8.11.4
- mongodb(the binary version): 6.0.4
- mongodb(the js package): 4.13.0
- system: MacOS 13.1 (22C65)

package: mongo-memory-server

## What is your question?

Trying to run [this example test](https://github.com/nodkz/mongodb-memory-server/blob/master/packages/mongodb-memory-server-core/src/__tests__/replset-multi.test.ts) with the latest version of MongoDB. I have my environment variables set p as follows:
```
export MONGOMS_DOWNLOAD_URL=https://fastdl.mongodb.org/osx/mongodb-macos-x86_64-6.0.4.tgz
export MONGOMS_VERSION=6.0.4
```

I am getting an error `Instance closed unexpectedly with code "null" and signal "SIGKILL"`

I have attached the debug log.

Any help would be appreciated.
[debug-log.txt](https://github.com/nodkz/mongodb-memory-server/files/10697490/debug-log.txt)

**Comment by hasezoey** [comment]
the log is not really giving anything more specific. to confirm, you are running a x86_64 mac system (not a arm64 (M1/M2)) system?

from what i can tell, the mongod process gets immediately killed with `SIGKILL`, not `SIGILL` or some library warning, which leads me to believe something external is preventing the process from starting (security?)

could you maybe try to manually run the binary and see what it outputs (if anything)?
(your binary is located at `/.cache/mongodb-binaries/mongod-x86_64-macos-6.0.4`)

**Comment by geryb-bg** [comment]
Hi there, yes I am running a x86_64 mac. I tried what you suggested and it just gets killed straight away. Weirdly, I tried another version of MongoDB (5.0.14) and it did not get killed. Maybe its a problem with the binary or my mac.

I guess this isn't really a problem with the mongodb-memory-server. Thanks for the help. Will close this.

**Comment by FloUz-ai** [comment]
I have the exact same pb every time I try to change the version

any solution?
