### ISSUE TITLE
TTL Index doesn't work

### ISSUE THREAD

**Issue by nikolayg** [nodkz/mongodb-memory-server#743]
## Versions

- NodeJS: 16.19.0
- mongodb-memory-server-*: 8.11.4
- mongodb(the binary version): 3.6.3
- mongoose: 6.9.0
- system: MacOS
- package: mongo-memory-server

## What is the Problem?

I created a TTL index, but the documents do not expire.

## Code Example

```ts
    // Create db - MongoMemoryServer.create(), etc

    // Create the test collection
    await db.createCollection("locks");

    // Based on https://www.mongodb.com/docs/manual/tutorial/expire-data/#expire-documents-at-a-specific-clock-time
    await db.collection("locks").createIndex({ expiresAt: 1 }, { expireAfterSeconds: 0 });

    // Insert element which expires in 5 seconds
    await db.collection("locks").insertOne({ _id: "test" as any, expiresAt: new Date(Date.now() + 5000) });

    // wait 10 seconds
    await sleep(10000);

    // Get all the locks
    const allLocks = await db.collection("locks").find({}).toArray();

    // Prints 1, but it should have expired
    console.log(">>>>>>>>>", allLocks.length);
```

## Do you know *why* it happens?

No, but I suspect there's [no background thread](https://www.mongodb.com/docs/manual/core/index-ttl/#delete-operations) which removes expired elements.

**Comment by hasezoey** [comment]
[from the documentation](https://www.mongodb.com/docs/manual/core/index-ttl/#timing-of-the-delete-operation)

> The TTL index does not guarantee that expired data will be deleted immediately upon expiration. There may be a delay between the time that a document expires and the time that MongoDB removes the document from the database.

> The background task that removes expired documents runs every 60 seconds. As a result, documents may remain in a collection during the period between the expiration of the document and the running of the background task. MongoDB starts deleting documents 0 to 60 seconds after the index completes.

---

if there really is no background deletion, then there is nothing MMS can really do, because behind MMS there still runs a normal `mongod` binary (and MMS does not set any options to disable that)
(MMS is short for `mongodb-memory-server`, this project)

**Comment by nikolayg** [comment]
Thanks @hasezoey ,

Thanks for the pointer to the documentation. Indeed it takes more than 10secs for the background job to run. When I increased the waiting to 60secs, it all works.
