### ISSUE TITLE
Debug mode enabled twice

### ISSUE THREAD

**Issue by jimzezz** [nodkz/mongodb-memory-server#745]
## Versions

- NodeJS: n/a
- mongodb-memory-server-*: 8.11.4 
- mongodb(the binary version): n/a 
- mongodb(the js package): n/a 
- mongoose: n/a 
- system: n/a 

package: mongo-memory-server 

## What is the Problem?

Minor issue but if debug mode is enabled via environment variable the log will also print 
`MongoMS:ResolveConfig Debug Mode Enabled, through package.json`

## Do you know *why* it happens?

This is caused by duplicated if conditions on lines [164](https://github.com/nodkz/mongodb-memory-server/blob/master/packages/mongodb-memory-server-core/src/util/resolveConfig.ts#L164) and [173](https://github.com/nodkz/mongodb-memory-server/blob/master/packages/mongodb-memory-server-core/src/util/resolveConfig.ts#L164)
`if (envToBool(resolveConfig(ResolveConfigVariables.DEBUG))) {`

I guess an easy fix is to just change line 173 to 
```diff
- if (envToBool(resolveConfig(ResolveConfigVariables.DEBUG))) {
+ if (!debug.enabled('MongoMS:*') && envToBool(resolveConfig(ResolveConfigVariables.DEBUG))) {
```

**Comment by hasezoey** [comment]
i knew, but never annoyed me enough to change it, might consider it
