### ISSUE TITLE
UnexpectedCloseError with code "3221225785" and signal "null"

### ISSUE THREAD

**Issue by Some14u** [nodkz/mongodb-memory-server#748]
## Versions

- NodeJS: 18.13.0
- mongodb-memory-server-*: 8.11.5 
- mongodb(the binary version): 0.0.0 
- mongodb(the js package): 0.0.0 
- mongoose: 0.0.0 
- system: Windows 7 sp1 

package: mongo-memory-server 

## What is the Problem?

I am encountering an issue with the mongodb-memory-server package where the MongoInstance is closing unexpectedly with an exit code of 3221225785. This error occurs in the MongoInstance.closeHandler function, which is part of the mongodb-memory-server-core package.

## Code Example

```js
const { MongoMemoryServer } = require("mongodb-memory-server");

(async () => {
  const mongod = await MongoMemoryServer.create();

  const uri = mongod.getUri();

  await mongod.stop();
})();
```

## Debug Output

<details>
<summary>Debug Output</summary>

```txt
node --max-old-space-size=4096 ./test1.js

Starting the MongoMemoryServer Instance failed, enable debug log for more information. Error:
 UnexpectedCloseError: Instance closed unexpectedly with code "3221225785" and signal "null"
    at MongoInstance.closeHandler (D:\Работа\git_repository\4 part node.js\hw05-avatars\node_modules\mongodb-memory-server-core\lib\util\MongoInstance.js:289:58)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:320:12)
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

UnexpectedCloseError: Instance closed unexpectedly with code "3221225785" and signal "null"
    at MongoInstance.closeHandler (D:\Работа\git_repository\4 part node.js\hw05-avatars\node_modules\mongodb-memory-server-core\lib\util\MongoInstance.js:289:58)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:320:12)

Node.js v18.13.0
```

</details>

## Do you know *why* it happenes?

No. I have tried the following steps to troubleshoot the issue:

- Ensured that all calls to the MongoMemoryServer and MongoClient instances are properly handled.
- Checked that I am using the latest version of the mongodb-memory-server package.
- Confirmed that my system meets the minimum requirements for running mongodb-memory-server.
- Disabled antivirus software that may be interfering with the operation of the mongodb-memory-server instance.

I suspect, that the problem might be in my operating system version (windows 7) which is outdated and not fully compatible with my node (which is 18+), however I haven't found anything about this in documentation here.

**Comment by hasezoey** [comment]
a high exit code on windows for mongodb usually means your are missing some library, in most cases a compatible version of vc_redist, [find a version here](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170) or [use the latest x86_64 download link directly](https://aka.ms/vs/17/release/vc_redist.x64.exe)

**Comment by Some14u** [comment]
The distributive you provided has installed successfully, hovewer it didn't help. Anything else I can do?

B.t.w. I don't have mongoDB core installed myself, because I'm working with Atlas. But for testing purposes I wanted to use mongodb-memory-server.

**Comment by Some14u** [comment]
I found out, that latest mongoDB doesn't support Windows 7. The last version that does work is 4.2.14 (next version listed oficially is 4.4.19, and it isn't working anymore, not sure if there is something in between).

Should I add this to the first message?

**Comment by hasezoey** [comment]
>  Should I add this to the first message?

i dont think so

> I had configured the mongodb-memory-server to download 4.2.24 and it worked

good to know

is your issue resolved?

**Comment by benjaminrae** [comment]
> a high exit code on windows for mongodb usually means your are missing some library, in most cases a compatible version of vc_redist, [find a version here](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170) or [use the latest x86_64 download link directly](https://aka.ms/vs/17/release/vc_redist.x64.exe)

This resolved the same issue for me today on a Windows 11 machine

**Comment by Some14u** [comment]
> docker-compose.yml

Yes, sorry for delayed answer.
