### ISSUE TITLE
Not running with openssl3

### ISSUE THREAD

**Issue by cherviakovtaskworld** [nodkz/mongodb-memory-server#750]
## Versions

- NodeJS: v19.6.0
- mongodb-memory-server-*: 8.10.2
- mongodb(the binary version): mongod-x64-arch-5.0.13
- system: archlinux 6.2.2-arch1-1

package: mongo-memory-server

## What is the Problem?

Cannot run code if openssl3 installed in my system

## Code Example

```ts
  const replset = new MongoMemoryReplSet({
    instanceOpts: [
      {
        port: 27017, // primary to default port
      },
    ],
    replSet: {
      name: 'rs0',
      ip: '0.0.0.0',
      count: 2, // 1 primary + 2 secondaries
    },
  })

  await replset.start()
```

## Debug Output

% openssl version  
OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)

Starting the MongoMemoryServer Instance failed, enable debug log for more information. Error:
 StdoutInstanceError: Instance failed to start because a library is missing or cannot be opened: "libcrypto.so.1.1"
    at MongoInstance.checkErrorInLine (/home/taskworld/projects/tw-platform/jobs/migrations/node_modules/.pnpm/mongodb-memory-server-core@8.10.2/node_modules/mongodb-memory-server-core/lib/util/MongoInstance.js:381:62)
    at MongoInstance.stderrHandler (/home/taskworld/projects/tw-platform/jobs/migrations/node_modules/.pnpm/mongodb-memory-server-core@8.10.2/node_modules/mongodb-memory-server-core/lib/util/MongoInstance.js:303:14)

## Do you know *why* it happenes?

Apparently there some dependency to openssl1.1 present

**Comment by hasezoey** [comment]
downloads for arch (and related systems like manjaro) use ubuntu binaries, because mongodb does not have official binaries for arch, and all mongodb versions below 6.0.4 require OpenSSL 1.1, so on arch you need to also install `core/openssl-1.1` OR use 6.0.4 via the [VERSION](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#version) option

**Comment by cherviakovtaskworld** [comment]
I see, thanks for clarification.
