### ISSUE TITLE
MongoMemoryServer Instance failed

### ISSUE THREAD

**Issue by kamalkech** [nodkz/mongodb-memory-server#759]
- Node: v16.16.0
- "mongodb-memory-server": "^8.12.1"

```typescript
import { MongooseModule } from '@nestjs/mongoose';
import { MongoMemoryServer } from 'mongodb-memory-server';

let mongod: MongoMemoryServer;

export const rootMongooseTestModule = async () =>
  MongooseModule.forRootAsync({
    useFactory: async () => {
      const mongod = await MongoMemoryServer.create({});
      const mongoUri = await mongod.getUri();
      return {
        uri: mongoUri,
        useNewUrlParser: true,
        useUnifiedTopology: true,
      };
    },
  });

export const closeInMongodConnection = async () => {
  if (mongod) await mongod.stop();
};
```

after run test i get this issue:

```
console.warn
    Starting the MongoMemoryServer Instance failed, enable debug log for more information. Error:
     UnexpectedCloseError: Instance closed unexpectedly with code "null" and signal "SIGSEGV"
        at MongoInstance.closeHandler (/mnt/E656FADC56FAAC85/Projects/Nest/onplad/node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:546:52)
        at ChildProcess.emit (node:events:527:28)
        at maybeClose (node:internal/child_process:1092:16)
        at Socket.<anonymous> (node:internal/child_process:451:11)
        at Socket.emit (node:events:527:28)
        at Pipe.<anonymous> (node:net:709:12)

      at MongoMemoryServer.<anonymous> (../node_modules/mongodb-memory-server-core/src/MongoMemoryServer.ts:293:17)
      at ../node_modules/tslib/tslib.js:167:75
      at __awaiter (../node_modules/tslib/tslib.js:163:16)
      at ../node_modules/mongodb-memory-server-core/src/MongoMemoryServer.ts:284:68
```

any idea to fixe this ??

**Comment by hasezoey** [comment]
please dont ignore the issue template

>      UnexpectedCloseError: Instance closed unexpectedly with code "null" and signal "SIGSEGV"

indicates that you are either running a different architecture than the binary expect (like trying to run x86_64 on arm without translation) or using a instruction which your CPU does not support (mongodb since 5.0 requires AVX instructions)

**Comment by kamalkech** [comment]
@hasezoey  thank you for response, but why working good when i downground to old version ```^8.10.1``` ??!

**Comment by hasezoey** [comment]
> but why working good when i downground to old version ^8.10.1 ??!

i dont know, 8.10 still uses binary 5.0.x as the default (though a older version)

here are some things you can try (please report back in which worked or not):
- upgrade to the latest version and remove the binary cache (by default it should be in `~/.cache/mongodb-binaries/`, actual path can be gotten by running with [Debug logs](https://nodkz.github.io/mongodb-memory-server/docs/guides/enable-debug-mode))
- upgrade through the versions and see which one starts to fail (try `8.10.2`, `8.11.0`, `8.11.5`, `8.12.0`, `8.12.1`)
