### ISSUE TITLE
Mongodb Stopped shipping non-distro tagged linux binaries since versions after 4.0

### ISSUE THREAD

**Issue by hasezoey** [nodkz/mongodb-memory-server#761]
## Versions

- Wanted System: `generic linux binary`
- Architecture: `x86_64`

## Detection

Linux fallback, no distro tag, like `mongodb-linux-x86_64-4.0.0.tgz` (example with distro tag: `mongodb-linux-x86_x64-ubuntu2004-4.0.0.tgz`)

## Current Error

Currently MMS falls-back to generic linux binaries for version that dont have it anymore

## Extra

The last version that shipped with "generic linux" (Linux (legacy)) is `4.0`, see [MongoDB Archive](https://www.mongodb.com/download-center/community/releases/archive)

**Comment by JackInTaiwan** [comment]
Same! +1

**Comment by hasezoey** [comment]
closing, done for 9.0 with fe76b56191d9a87e1c1702af5de47b8df4b5a809
