### ISSUE TITLE
Cannot Run Example Script

### ISSUE THREAD

**Issue by BrandonMan123** [nodkz/mongodb-memory-server#778]
## Versions

- NodeJS: 18.9.0
- mongodb-memory-server-*: ^8.13.0 
- mongodb(the binary version): 0.0.0
- mongodb(the js package): 5.6.0
- mongoose: ^7.3.0
- system: MacOS Ventura 13.4.1

package: mongo-memory-server 

## What is your question?

I am using mongo-memory-server to test with jest and I am trying to run the example test file for a single mongo memory server within jest on the github page. My code is below:
```
/* eslint-disable @typescript-eslint/no-non-null-assertion */
import { MongoClient } from 'mongodb';
import { MongoMemoryServer } from 'mongodb-memory-server';

// This is an Example test, do not merge it with others and do not delete this file

describe('Single MongoMemoryServer', () => {
  let con: MongoClient;
  let mongoServer: MongoMemoryServer;

  beforeAll(async () => {
    mongoServer = await MongoMemoryServer.create();
    con = await MongoClient.connect(mongoServer.getUri(), {});
  });

  afterAll(async () => {
    if (con) {
      await con.close();
    }
    if (mongoServer) {
      await mongoServer.stop();
    }
  });

  it('should successfully set & get information from the database', async () => {
    const db = con.db(mongoServer.instanceInfo!.dbName);

    expect(db).toBeDefined();
    const col = db.collection('test');
    const result = await col.insertMany([{ a: 1 }, { b: 1 }]);
    expect(result.insertedCount).toStrictEqual(2);
    expect(await col.countDocuments({})).toBe(2);
  });
});
```
But I get a timeout error as shown below. 

![Screenshot 2023-07-11 at 6 49 21 PM](https://github.com/nodkz/mongodb-memory-server/assets/40282816/53ee2a91-bb2a-498d-818a-795edf01cc97)

Here are my jest configs:
`module.exports = {
    preset: 'ts-jest',
    transform: {
      '^.+\\.(ts|tsx)?$': 'ts-jest',
      "^.+\\.(js|jsx)$": "babel-jest",
    }
  };`

I am currently using "mongodb-memory-server": "", typescript 5.1.3 and node . Would appreciate any help and let me know if I can provide more details. Thanks!

**Comment by BrandonMan123** [comment]
I didn't install the binary (more specifically did not run the export commands) which caused the issue to time out. Also as a side note the server seems to be timing out when using it in conjuction with jest.useFakeTimers(), though I will put that in a separate issue.

**Comment by hasezoey** [comment]
> Also as a side note the server seems to be timing out when using it in conjuction with jest.useFakeTimers(), though I will put that in a separate issue.

that is somewhat to be expected, because MMS uses a timeout to detect if a child-process in nodejs does not respond, and i think mongodb also uses timeouts somewhere for connection handling

> I didn't install the binary (more specifically did not run the export commands) which caused the issue to time out

more likely it timed-out because it was trying to download the binary in the test, but before finishing it timed-out.
it is recommended to put this into a `globalSetup` (at the very least the binary download) because those have higher / no timeouts, see how MMS does this for multiple versions:

https://github.com/nodkz/mongodb-memory-server/blob/78699ee06e3c4da768aef79d9a4d400bccac25ea/packages/mongodb-memory-server-core/src/__tests__/testUtils/globalSetup.ts#L8-L12
