### ISSUE TITLE
When running the tests, not all the temp directories are deleted

### ISSUE THREAD

**Issue by orgads** [nodkz/mongodb-memory-server#788]
## Versions

- NodeJS: v18.17.1
- mongodb-memory-server-*: v8.15.0
- mongodb(the binary version): 0
- system: Linux (Debian testing)

package: mongo-memory-server

## What is the Problem?
After running the tests, some directories named `/tmp/mongo-mem-*` are cleaned up, but 16 directories remain.

Example:
```
$ ls -F | grep mongo
mongo-mem-1Uvw57/
mongo-mem-3p8Ht8/
mongo-mem-3uX5zS/
mongo-mem-72lMFJ/
mongo-mem-92wykg/
mongo-mem-C1j0Y3/
mongo-mem-CagqwH/
mongo-mem-cCQi1V/
mongo-mem-d4QVf8/
mongo-mem-gksG2o/
mongo-mem-JPRDDc/
mongo-mem-keyfile-r4ZApt/
mongo-mem-mgKdm7/
mongo-mem-PbU7F0/
mongo-mem-wA4Et7/
mongo-mem-YFzWa8/
mongo-mem-yJXnvv/
mongodb-42303.sock=
reuse-mongo-mem-tdFMBT/
```

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment]
were the tests successful or did they error? also, is this from the MMS test-suite?

**Comment by orgads** [comment]
1 test failed:
```
    console.warn
      An Process didnt exit with signal "SIGINT" within 10 seconds, using "SIGKILL"!
      Enable debug logs for more information

      125 |
      126 |       if (!debug.enabled('MongoMS:utils')) {
    > 127 |         console.warn(
          |                 ^
      128 |           'An Process didnt exit with signal "SIGINT" within 10 seconds, using "SIGKILL"!\n' +
      129 |             'Enable debug logs for more information'
      130 |         );

      at console.<anonymous> (../../node_modules/jest-mock/build/index.js:839:25)
      at Timeout.warn [as _onTimeout] (src/util/utils.ts:127:17)

  ● single server replset › should make use of "AutomaticAuth" (wiredTiger)

    MongoWriteConcernError: operation was interrupted

      at Connection.onMessage (../../node_modules/mongodb/src/cmap/connection.ts:444:20)
      at MessageStream.<anonymous> (../../node_modules/mongodb/src/cmap/connection.ts:241:56)
      at processIncomingData (../../node_modules/mongodb/src/cmap/message_stream.ts:188:12)
      at MessageStream._write (../../node_modules/mongodb/src/cmap/message_stream.ts:69:5)
```

I ran `npm test` in my MMS clone.

**Comment by hasezoey** [comment]
temporary directories only get cleaned up when calling `.stop` (without disabling it in the arguments) or calling `.cleanup`, so if a test fails the temporary directory will stay

but yes, current `master` does not clean-up some directories, but current `beta` (9.0) does, i will probably not backport all of the changes, but maybe some

**Comment by hasezoey** [comment]
backported ead795866054e11d133f497118f31cb9ca776c1b and 2cbfb585365b101038d0e5dd98ea2316db5515fc, so now there are no temporary directories anymore (for successful tests at least)

**Comment by orgads** [comment]
Thank you!
