### ISSUE TITLE
Problem with local jest Unit test with Change Stream

### ISSUE THREAD

**Issue by fangdanzai** [nodkz/mongodb-memory-server#793]
## Versions

- NodeJS: 16.20.0
- mongodb-memory-server-*: 8.15.1 
- mongodb(the binary version):5.0.13
- 
- system:  MacOS

package: mongo-memory-server : mongo-memory-server

## What is your question?

I tried to use mongodb-memory-server to create a local unit test, and here's my setup:

```ts
this.mongoServer = await MongoMemoryReplSet.create({
      replSet: {
        dbName: this.database,
        storageEngine: "wiredTiger",
      },
      binary: {
        version: "5.0.13",
        downloadDir: "etc/mongo_binaries",
      },
    });
```

I also created a changeStreamClient to connect to the database I built. Once the program start to watch the data-set, I tried to delete one Document in the watched collection but changeStream.on() is not triggered in unit test.
    
Any one knows the reason?

**Comment by hasezoey** [comment]
please provide a full reproduction example, as it likely is related to how it is used

PS: next time please use [proper code-formatting](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) (ie no spaces for a code-block and add the language)

**Comment by hasezoey** [comment]
> You can't test changeStream with wiredTiger storage engine

did you mean to say `ephermeralForTest`? because official mongodb docs say this about `Availability` for `Change Streams`:

> The replica sets and sharded clusters must use the [WiredTiger](https://www.mongodb.com/docs/manual/core/wiredtiger/#std-label-storage-wiredtiger) storage engine. Change streams can also be used on deployments that employ MongoDB's [encryption-at-rest](https://www.mongodb.com/docs/manual/core/security-encryption-at-rest/#std-label-encrypted-storage-engine) feature.

[source](https://www.mongodb.com/docs/manual/changeStreams/)

**Comment by noghartt** [comment]
> > You can't test changeStream with wiredTiger storage engine
> 
> did you mean to say `ephermeralForTest`? because official mongodb docs say this about `Availability` for `Change Streams`:
> 
> > The replica sets and sharded clusters must use the [WiredTiger](https://www.mongodb.com/docs/manual/core/wiredtiger/#std-label-storage-wiredtiger) storage engine. Change streams can also be used on deployments that employ MongoDB's [encryption-at-rest](https://www.mongodb.com/docs/manual/core/security-encryption-at-rest/#std-label-encrypted-storage-engine) feature.
> 
> [source](https://www.mongodb.com/docs/manual/changeStreams/)

Sorry, you're right. In case, we need to handle a replset instance with `wiredTiger`, I was wrong.
