### ISSUE TITLE
README default `downloadDir` is outdated

### ISSUE THREAD

**Issue by nicolaschambrier** [nodkz/mongodb-memory-server#799]
README says:

```
    downloadDir?: string, // by default node_modules/.cache/mongodb-memory-server/mongodb-binaries
```

but when I installed the `mongodb-memory-server`, either locally or on CircleCI it definitely downloaded globally (in `~/.cache/mongodb-binaries`). Did I do something wrong or doc is outdated?

**Comment by hasezoey** [comment]
yes that documentation is outdated, more up-to-date can be found at [`DOWNLOAD_DIR`](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#download_dir)

i will let this issue stay open until fixed
