### ISSUE TITLE
MongoMemoryReplSet hangs tests in Bun

### ISSUE THREAD

**Issue by robertherber** [nodkz/mongodb-memory-server#800]
## Versions

- NodeJS: N/A
- mongodb-memory-server-*: 8.15.1
- mongodb(the binary version): 5.0.19
- mongodb(the js package): 5.9.0
- system: MacOS 13.5.2

package: mongo-memory-server

## What is the Problem?

When running `bun test` it hangs on `mongodb.stop()`. It does work with `MongoMemoryServer` but not  with `MongoMemoryReplSet`.

## Code Example

```ts
import {
  expect, beforeAll, test, afterAll,
} from 'bun:test'

let mongodb
beforeAll(async () => {
  const memoryServer = await import('mongodb-memory-server')
  mongodb = await memoryServer.MongoMemoryReplSet.create()
})

test('a test', () => {
  expect(1 + 1).toEqual(2)
})

afterAll(async () => {
  console.log('stopping mongodb')
  await mongodb.stop() // <-- hangs here
  console.log('stopping mongodb')
})
```

Not sure why it happens, and not really getting any useful output. This issue might very well belong in the bun repo. I'm happy to move the issue there - but any context as to what could be different between the two implementations might be helpful when moving it there :)

**Comment by hasezoey** [comment]
please provide [Debug Output](https://nodkz.github.io/mongodb-memory-server/docs/guides/enable-debug-mode)

also note that other engines other than nodejs are not *officially* supported, though deno is tested through mongoose (not the full suite though) and a lot of issues (mostly inside the mongodb driver) have come up with deno

also maybe try the latest beta [`9.0.0-beta.2`](https://github.com/nodkz/mongodb-memory-server/releases/tag/v9.0.0-beta.2)
