### ISSUE TITLE
Use RHEL 9 binaries

### ISSUE THREAD

**Issue by cinder-fish** [nodkz/mongodb-memory-server#820]
## Versions

- NodeJS: 18
- mongodb-memory-server-*: 9.0.1 
- system: Rocky Linux 9

## What is the Problem?

On rocky 9 the library appears to download the rhel 8 binaries which depend on libssl 1.x which is no longer available

```
Instance failed to start because a library is missing or cannot be opened: "libcrypto.so.1.1"
```

I think following on from https://github.com/nodkz/mongodb-memory-server/issues/726 the rhel 9 binaries are available now

e.g. overriding to use one of these works
```
MONGOMS_DOWNLOAD_URL='https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-rhel90-6.0.9.tgz'
```

**Comment by hasezoey** [comment]
wrong issue template, please create a new one with all the information for `Distribution support`

**Comment by cinder-fish** [comment]
https://github.com/nodkz/mongodb-memory-server/issues/821
