### ISSUE TITLE
[SOLUTION] Jest and Fake Timers

### ISSUE THREAD

**Issue by DominicVonkPON** [nodkz/mongodb-memory-server#824]
### Discussed in https://github.com/nodkz/mongodb-memory-server/discussions/823

<div type='discussions-op-text'>

<sup>Originally posted by **DominicVonkPON** October 30, 2023</sup>
If you encounter a problem with Jest where the tests are not running due to the fake timers, it could be because MongoDB memory server relies on ﻿nextTick. To resolve this issue, you should avoid faking the ﻿nextTick function. By allowing the natural behavior of ﻿nextTick, you should be able to run the tests successfully with Jest.

```javascript
jest.useFakeTimers({
      doNotFake: ['nextTick'], // do not fake nextTick behavior for mongo in memory
});
```

</div>

**Comment by hasezoey** [comment]
why exactly was this opened as a issue too?
