### ISSUE TITLE
Issue downloading mongo binaries with Nexus set as  MONGOMS_DOWNLOAD_MIRROR

### ISSUE THREAD

**Issue by SimoneDutto** [nodkz/mongodb-memory-server#865]
Hi, I am having issue downloading mongo-binaries using a Nexus as the mirror.

After having spent some time debugging, I found the root cause of the problem to be that my nexus is not setting the `content-length` header.
Manually removing the check at this [line](https://github.com/nodkz/mongodb-memory-server/blob/fdf3d641c37b69c52819d25c1e29b64c96b8a33a/packages/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts#L402) solved my issue.

I am willing to help solving the issue and creating a PR if needed.

**Comment by hasezoey** [comment]
if you want you can make a PR for that.

**Comment by SimoneDutto** [comment]
is it enough to remove the check or do you want something like a config variable?

**Comment by hasezoey** [comment]
well that check is there to ensure that the progress does not have "10MB/0MB" or something, in addition also i guess it is a slight security thing to not download unknown length for a unknown amount of time (though we dont enforce that)

i can also put out a quick fix, if you want

**Comment by SimoneDutto** [comment]
You are right about the security thing, but my nexus does not set this header. I don't see a way around it, besides removing the check if an env var is set. In a similar fashion to [line](https://github.com/nodkz/mongodb-memory-server/blob/fdf3d641c37b69c52819d25c1e29b64c96b8a33a/packages/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts#L187)

**Comment by hasezoey** [comment]
a fix has been made in f3f7764dc2c61bb7897cc340f2a1544d87937461, if you enable config option [`DOWNLOAD_IGNORE_MISSING_HEADER`](https://nodkz.github.io/mongodb-memory-server/versions/beta/docs/api/config-options#download_ignore_missing_header), please test this works for you.

**Comment by SimoneDutto** [comment]
That solved the issue! Thanks a lot.
