### ISSUE TITLE
Instance failed to start because a library is missing or cannot be opened: "libcrypto.so.1.1"

### ISSUE THREAD

**Issue by Sangyog10** [nodkz/mongodb-memory-server#869]
## Versions
- NodeJS: 20.12.2
- mongodb-memory-server:9.2.0
- mongodb: 7.0.9
- mongoose: 8.3.3
- system: fedora 40
- 
## What is your question?
I am running the test in Fedora 40 and got this error. I do have "libcrypto.so.1.1" installed 

Starting the MongoMemoryServer Instance failed, enable debug log for more information. Error:
     StdoutInstanceError: Instance failed to start because a library is missing or cannot be opened: "libcrypto.so.1.1"
        at MongoInstance.checkErrorInLine (/home/sangyog/Projects/MIcroservices/Ticket app/tickets/node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:708:11)
        at MongoInstance.stderrHandler (/home/sangyog/Projects/MIcroservices/Ticket app/tickets/node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:595:10)
        at Socket.emit (node:events:518:28)
        at addChunk (node:internal/streams/readable:559:12)
        at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
        at Socket.Readable.push (node:internal/streams/readable:390:5)
        at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

**Comment by hasezoey** [comment]
> I do have "libcrypto.so.1.1" installed

if that error is present, then you either dont have it installed, or it is not available to be found. you can check with `ldconfig -p | grep libcrypto`.

**Comment by Sangyog10** [comment]
I get the following result by running the given command: $ldconfig -p | grep libcrypto
	libcrypto.so.3 (libc6,x86-64) => /lib64/libcrypto.so.3
	libcrypto.so.1.1 (libc6) => /lib/libcrypto.so.1.1
	libcrypto.so (libc6,x86-64) => /lib64/libcrypto.so

**Comment by hasezoey** [comment]
if that is your output and you are not running mongodb-memory-server / the resulting started binary in a separate environment, i dont know what could be wrong with linking, maybe it would help to have the full [debug log](https://nodkz.github.io/mongodb-memory-server/docs/guides/enable-debug-mode)?

**Comment by Yarkhan** [comment]
Having this issue as well on a docker container. Using the image `node:20-buster` solved the issue for me.

**Comment by mpsebastianvidiv** [comment]
Same on Node 20.14.0

**Comment by steven-supersolid** [comment]
This is an issue on Debian 10 Buster https://github.com/nodejs/docker-node/issues/1916

**Comment by steven-supersolid** [comment]
How did you solve this @Sangyog10? In case anyone finds this issue in the future

**Comment by Sangyog10** [comment]
> How did you solve this @Sangyog10? In case anyone finds this issue in the future
I could not solve this issue in fedora 40. So i switched to mint and everything is working fine. I guess the issue is with fedora 40

**Comment by natlibfi-jonollil** [comment]
Got it working by installing fedora 39 package
`dnf install https://nic.funet.fi/pub/Linux/mirrors/fedora/linux/releases/39/Everything/x86_64/os/Packages/o/openssl1.1-1.1.1q-5.fc39.x86_64.rpm`
