### ISSUE TITLE
Flow error in optional chaining?

### ISSUE THREAD

**Issue by pronebird** [nodkz/mongodb-memory-server#87]
That's what I get when running flow against my project:

```
yarn flow       
yarn run v1.10.1
$ flow
Error: node_modules/mongodb-memory-server/lib/util/MongoBinary.js.flow:27
 27:         process.env?.MONGOMS_DOWNLOAD_DIR || path.resolve(os.homedir(), '.mongodb-binaries'),
                         ^ Unexpected token .
```

Perhaps I can add `node_modules/mongodb-memory-server` to flow's ignore file but still.

**Comment by nodkz** [comment]
Just add this line to your flowconfig

https://github.com/nodkz/mongodb-memory-server/blob/master/.flowconfig#L43
