### ISSUE TITLE
Probably incorrect documentation

### ISSUE THREAD

**Issue by kbychkov** [nodkz/mongodb-memory-server#88]
I'm trying to use the module as described in docs.

```javascript
const MongodbMemoryServer = require('mongodb-memory-server');
const mongoServer = new MongodbMemoryServer();
```

But I got the error `TypeError: MongodbMemoryServer is not a constructor`.

At [this page](https://jestjs.io/docs/en/mongodb) I've found another piece of code

```javascript
const mongoServer = new MongodbMemoryServer.MongoMemoryServer();
```

and that works. Is that an error in the documentation or in the code?

**Comment by AJRdev** [comment]
@kbychkov The documentation is actually using the ES6 equivalent syntax of require that is import : 
```javascript
import MongodbMemoryServer from 'mongodb-memory-server';

const mongod = new MongodbMemoryServer();
```

By using import like that, it is actually importing the default export of the mongodb-memory-server library that is MongodbMemoryServer. A easy way to do that with require is this : 
```javascript
const MongodbMemoryServer = require('mongodb-memory-server').default
const mongoServer = new MongodbMemoryServer()
```

**Comment by kbychkov** [comment]
Ahhh, I see. Thank you for the explanation!
