### ISSUE TITLE
Auto-download of binaries on install

### ISSUE THREAD

**Issue by guillaumervls** [nodkz/mongodb-memory-server#95]
Hi and thanks for this module,

I use the `downloadDir` options in my code, so my home folder stays clean of `.mongodb-binaries`. However the `postinstall` script is not aware of that and downloads in my home folder. Shouldn't the downloading of binaries after `npm install` be optional ? (I mean opt-in instead of opt-out)

Am I missing something ?

Cheers

**Comment by AJRdev** [comment]
@guillaumervls You should use the environnement variable MONGOMS_DOWNLOAD_DIR that specify a path where to download the mongodb binaries instead of the downloadDir option, because it will be used in the postinstall script as well :)

**Comment by nodkz** [comment]
In some cases, mongod binary may download about 1 minute the first time.

Most developers don't know how to increase timeouts in test runners. And by default after 5 seconds tests halts.

So for making testing without additional setups I decide to download latest verson on postinstall script.It allows to start testing with zero configuration.

**Comment by nodkz** [comment]
Disabling downloading via `MONGOMS_DISABLE_POSTINSTALL` env variable is less evil.

**Comment by guillaumervls** [comment]
Ok then isn't there a more appropriate place to download them (more local to the project) ?

**Comment by guillaumervls** [comment]
Or read a setting from `package.json` ? Setting an environment variable puts this responsibility on the users of the package using this lib, forcing them to use `MONGOMS_DISABLE_POSTINSTALL=1 npm install`. With a setting in `package.json` they could just `npm install`.

**Comment by nodkz** [comment]
Sounds sweet if we can provide some vars via package.json or even .dot file.

Any proposal how it can be implemented? Need to use expierence from jest, babel, ts or any other implementation.

I feel your tension and dissapoinment about current ways of configuration. no one has raised this problem yet and you are the first!  So let's solve this problem.

**Comment by guillaumervls** [comment]
Cool ! From what I've seen popular modules like Husky, Babel, and Jest, use a `package.json` key matching their `npm` name (`babel`, `husky`, `jest`). Only ESLint uses `eslintConfig`. In our case it could be `mongodb-memory-server`.

IMHO, special config files like `.babelrc` should be used if they were so many config option that it could bloat `package.json`. It may not be necessary for the 7 options available here (the 7 `MONGOMS_XXX` env vars).

To implement this, I suggest the use of https://www.npmjs.com/package/pkg-conf which seems quite popular, and does exactly what we want.

**Comment by nodkz** [comment]
@guillaumervls if you have free time you may implement this feature with `mongodb-memory-server`  key in package.json.

My current bandwidth till the end of year does not allow to do it myself 😞

And I will be very glad if somebody takes care about this feature. 🙏
Thanks.

**Comment by guillaumervls** [comment]
@nodkz Just found this : https://www.npmjs.com/package/find-cache-dir (it's even more popular than 
https://www.npmjs.com/package/pkg-conf)

Wouldn't it be even simpler to just use this instead of `%HOME/.mongodb-binaries` as the default ? Is would solve the problem of polluting the `HOME` folder and wouldn't require any config !

What do you think ?

**Comment by nodkz** [comment]
Implemented in https://github.com/nodkz/mongodb-memory-server/releases/tag/v2.7.0
